// Code generated by `ubx sdk gen` from digitalocean_database_user. DO NOT EDIT.
package database

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type User_Users_MysqlSettings struct {
	AuthPlugin any
}

type User_Users_Settings_Acl struct {
	Id any
	Permission any
	Topic any
}

type User_Users_Settings_MongoUserSettings struct {
	Databases any
	Role any
}

type User_Users_Settings_OpensearchAcl struct {
	Index any
	Permission any
}

type User_Users_Settings struct {
	Acl any
	MongoUserSettings any
	OpensearchAcl any
	PgAllowReplication any
}

type User_Users struct {
	AccessCert any
	AccessKey any
	MysqlSettings any
	Name any
	Password any
	Role any
	Settings any
}

type UserConfig struct {
	DatabaseClusterUuid any
}

type UserAttrs struct {
	DatabaseClusterUuid any
	Users any
}

var User = ubx.DataSourceBinding{
	WireType: "digitalocean_database_user",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
	},
}
