// Code generated by `ubx sdk gen` from digitalocean_garbage_collection. DO NOT EDIT.
package containerregistries

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GarbageCollection_GarbageCollection struct {
	// The number of blobs deleted as a result of this garbage collection.
	BlobsDeleted any
	// The time the garbage collection was created.
	CreatedAt any
	// The number of bytes freed as a result of this garbage collection.
	FreedBytes any
	// The name of the container registry.
	RegistryName any
	// The current status of this garbage collection.
	Status any
	// The time the garbage collection was last updated.
	UpdatedAt any
	// A string specifying the UUID of the garbage collection.
	Uuid any
}

type GarbageCollectionConfig struct {
	RegistryName any
}

type GarbageCollectionAttrs struct {
	GarbageCollection any
	RegistryName      any
}

var GarbageCollection = ubx.DataSourceBinding{
	WireType: "digitalocean_garbage_collection",
	Fields: ubx.FieldMap{
		"RegistryName": ubx.FieldSpec{WireName: "registry_name"},
	},
}
