// Code generated by `ubx sdk gen` from digitalocean_subscription. DO NOT EDIT.
package containerregistries

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Subscription_Subscription_Tier struct {
	// A boolean indicating whether the subscription tier supports additional storage above what is included in the base plan at an additional cost per GiB used.
	AllowStorageOverage any
	// The amount of outbound data transfer included in the subscription tier in bytes.
	IncludedBandwidthBytes any
	// The number of repositories included in the subscription tier. `0` indicates that the subscription tier includes unlimited repositories.
	IncludedRepositories any
	// The amount of storage included in the subscription tier in bytes.
	IncludedStorageBytes any
	// The monthly cost of the subscription tier in cents.
	MonthlyPriceInCents any
	// The name of the subscription tier.
	Name any
	// The slug identifier of the subscription tier.
	Slug any
	// The price paid in cents per GiB for additional storage beyond what is included in the subscription plan.
	StorageOveragePriceInCents any
}

type Subscription_Subscription struct {
	// The time at which the subscription was created.
	CreatedAt any
	Tier      any
	// The time at which the subscription was last updated.
	UpdatedAt any
}

type SubscriptionConfig struct {
}

type SubscriptionAttrs struct {
	Subscription any
}

var Subscription = ubx.DataSourceBinding{
	WireType: "digitalocean_subscription",
	Fields:   ubx.FieldMap{},
}
