// Code generated by `ubx sdk gen` from digitalocean_app. DO NOT EDIT.
package app

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type App_Metadata struct {
	Description any
	DisplayName any
	Id any
	Name any
	Options any
	Type any
}

type AppConfig struct {
	AppSlug any
}

type AppAttrs struct {
	AppSlug any
	Metadata any
}

var App = ubx.DataSourceBinding{
	WireType: "digitalocean_app",
	Fields: ubx.FieldMap{
		"AppSlug": ubx.FieldSpec{WireName: "app_slug"},
	},
}
