# Code generated by `ubx sdk gen` from digitalocean_api_anthropic_apikey_info. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AnthropicApikeyInfo_ApiKeyInfos:
    created_at: Any = None
    created_by: Any = None
    deleted_at: Any = None
    name: Any = None
    updated_at: Any = None
    uuid: Any = None

@dataclasses.dataclass
class AnthropicApikeyInfo_Links_Pages:
    # First page
    first: Any = None
    # Last page
    last: Any = None
    # Next page
    next: Any = None
    # Previous page
    previous: Any = None

@dataclasses.dataclass
class AnthropicApikeyInfo_Links:
    # Information about how to reach other pages
    pages: Any = None

@dataclasses.dataclass
class AnthropicApikeyInfo_Meta:
    # The current page
    page: Any = None
    # Total number of pages
    pages: Any = None
    # Total amount of items over all pages
    total: Any = None

@dataclasses.dataclass
class AnthropicApikeyInfoConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class AnthropicApikeyInfoAttrs:
    # Api key infos
    api_key_infos: Any = None
    # Links to other pages
    links: Any = None
    # Meta information about the data set
    meta: Any = None
    page: Any = None
    per_page: Any = None

AnthropicApikeyInfo = ubx.DataSourceBinding(
    wire_type="digitalocean_api_anthropic_apikey_info",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
