# Code generated by `ubx sdk gen` from digitalocean_api_get_scheduled_indexing_output. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GetScheduledIndexingOutput_IndexingInfo:
    # Created at timestamp
    created_at: Any = None
    # Days for execution (day is represented same as in a cron expression, e.g. Monday begins with 1 )
    days: Any = None
    # Deleted at timestamp (if soft deleted)
    deleted_at: Any = None
    # Whether the schedule is currently active
    is_active: Any = None
    # Knowledge base uuid associated with this schedule
    knowledge_base_uuid: Any = None
    # Last time the schedule was executed
    last_ran_at: Any = None
    # Next scheduled run
    next_run_at: Any = None
    # Scheduled time of execution (HH:MM:SS format)
    time: Any = None
    # Updated at timestamp
    updated_at: Any = None
    # Unique identifier for the scheduled indexing entry
    uuid: Any = None

@dataclasses.dataclass
class GetScheduledIndexingOutputConfig:
    knowledge_base_uuid: Any = None

@dataclasses.dataclass
class GetScheduledIndexingOutputAttrs:
    # Metadata for scheduled indexing entries
    indexing_info: Any = None
    knowledge_base_uuid: Any = None

GetScheduledIndexingOutput = ubx.DataSourceBinding(
    wire_type="digitalocean_api_get_scheduled_indexing_output",
    fields={
        "knowledge_base_uuid": ubx.FieldSpec(wire_name="knowledge_base_uuid"),
    },
)
