# Code generated by `ubx sdk gen` from digitalocean_api_model_router_preset. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ModelRouterPreset_Links_Pages:
    # First page
    first: Any = None
    # Last page
    last: Any = None
    # Next page
    next: Any = None
    # Previous page
    previous: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Links:
    # Information about how to reach other pages
    pages: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Meta:
    # The current page
    page: Any = None
    # Total number of pages
    pages: Any = None
    # Total amount of items over all pages
    total: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Presets_Config_Policies_CustomTask:
    description: Any = None
    name: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Presets_Config_Policies_SelectionPolicy:
    prefer: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Presets_Config_Policies:
    custom_task: Any = None
    models: Any = None
    selection_policy: Any = None
    task_slug: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Presets_Config:
    fallback_models: Any = None
    policies: Any = None

@dataclasses.dataclass
class ModelRouterPreset_Presets:
    config: Any = None
    display_name: Any = None
    long_description: Any = None
    short_description: Any = None
    slug: Any = None

@dataclasses.dataclass
class ModelRouterPresetConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class ModelRouterPresetAttrs:
    # Links to other pages
    links: Any = None
    # Meta information about the data set
    meta: Any = None
    page: Any = None
    per_page: Any = None
    # The model router presets
    presets: Any = None

ModelRouterPreset = ubx.DataSourceBinding(
    wire_type="digitalocean_api_model_router_preset",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
