// Code generated by `ubx sdk gen` from digitalocean_database. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Database_Autoscale_Storage {
  enabled?: boolean | Computed<boolean>;
  incrementGib?: number | Computed<number>;
  thresholdPercent?: number | Computed<number>;
}

export interface Database_Autoscale {
  storage?: Database_Autoscale_Storage | Computed<Database_Autoscale_Storage>;
}

export interface DatabaseConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface DatabaseAttrs {
  /** Contains all autoscaling configuration for a database cluster */
  autoscale: Database_Autoscale;
  databaseClusterUuid: string;
}

export const Database: DataSourceBinding<DatabaseConfig, DatabaseAttrs> = {
  wireType: "digitalocean_database",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
