// Code generated by `ubx sdk gen` from digitalocean_bgp_auth_key. DO NOT EDIT.
package partnernetworkconnect

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BgpAuthKeyConfig struct {
	PaId any
}

type BgpAuthKeyAttrs struct {
	BgpAuthKey any
	PaId       any
}

var BgpAuthKey = ubx.DataSourceBinding{
	WireType: "digitalocean_bgp_auth_key",
	Fields: ubx.FieldMap{
		"PaId": ubx.FieldSpec{WireName: "pa_id"},
	},
}
