// Code generated by `ubx sdk gen` from digitalocean_remote_route. DO NOT EDIT.
package partnernetworkconnect

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RemoteRoute_Links struct {
	Pages any
}

type RemoteRoute_Meta struct {
	Total any
}

type RemoteRoute_RemoteRoutes struct {
	Cidr any
}

type RemoteRouteConfig struct {
	PaId    any
	Page    any
	PerPage any
}

type RemoteRouteAttrs struct {
	Links        any
	Meta         any
	PaId         any
	Page         any
	PerPage      any
	RemoteRoutes any
}

var RemoteRoute = ubx.DataSourceBinding{
	WireType: "digitalocean_remote_route",
	Fields: ubx.FieldMap{
		"PaId":    ubx.FieldSpec{WireName: "pa_id"},
		"Page":    ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
