// Code generated by `ubx sdk gen` from digitalocean_repositories_v2. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RepositoriesV2_Links {
  pages?: unknown | Computed<unknown>;
}

export interface RepositoriesV2_Meta {
  total?: number | Computed<number>;
}

export interface RepositoriesV2_Repositories_LatestManifest_Blobs {
  compressedSizeBytes?: number | Computed<number>;
  digest?: string | Computed<string>;
}

export interface RepositoriesV2_Repositories_LatestManifest {
  blobs?: RepositoriesV2_Repositories_LatestManifest_Blobs[] | Computed<RepositoriesV2_Repositories_LatestManifest_Blobs[]>;
  compressedSizeBytes?: number | Computed<number>;
  digest?: string | Computed<string>;
  registryName?: string | Computed<string>;
  repository?: string | Computed<string>;
  sizeBytes?: number | Computed<number>;
  tags?: string[] | Computed<string[]>;
  updatedAt?: string | Computed<string>;
}

export interface RepositoriesV2_Repositories {
  latestManifest?: RepositoriesV2_Repositories_LatestManifest | Computed<RepositoriesV2_Repositories_LatestManifest>;
  manifestCount?: number | Computed<number>;
  name?: string | Computed<string>;
  registryName?: string | Computed<string>;
  tagCount?: number | Computed<number>;
}

export interface RepositoriesV2Config {
  page?: number | Computed<number>;
  pageToken?: string | Computed<string>;
  perPage?: number | Computed<number>;
  registryName: string | Computed<string>;
}

export interface RepositoriesV2Attrs {
  links: RepositoriesV2_Links;
  meta: RepositoriesV2_Meta;
  page: number;
  pageToken: string;
  perPage: number;
  registryName: string;
  repositories: RepositoriesV2_Repositories[];
}

export const RepositoriesV2: DataSourceBinding<RepositoriesV2Config, RepositoriesV2Attrs> = {
  wireType: "digitalocean_repositories_v2",
  fields: {
    page: "page",
    pageToken: "page_token",
    perPage: "per_page",
    registryName: "registry_name",
  },
};
