// Code generated by `ubx sdk gen` from digitalocean_uptime. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface UptimeConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface UptimeAttrs {
  page: number;
  perPage: number;
}

export const Uptime: DataSourceBinding<UptimeConfig, UptimeAttrs> = {
  wireType: "digitalocean_uptime",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
