// Code generated by `ubx sdk gen` from digitalocean_api_knowledge_base. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApiKnowledgeBase_KnowledgeBases_LastIndexingJob_DataSourceJobs {
  completedAt?: string | Computed<string>;
  dataSourceUuid?: string | Computed<string>;
  errorDetails?: string | Computed<string>;
  errorMsg?: string | Computed<string>;
  failedItemCount?: string | Computed<string>;
  indexedFileCount?: string | Computed<string>;
  indexedItemCount?: string | Computed<string>;
  removedItemCount?: string | Computed<string>;
  skippedItemCount?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  totalBytes?: string | Computed<string>;
  totalBytesIndexed?: string | Computed<string>;
  totalFileCount?: string | Computed<string>;
}

export interface ApiKnowledgeBase_KnowledgeBases_LastIndexingJob {
  completedDatasources?: number | Computed<number>;
  createdAt?: string | Computed<string>;
  dataSourceJobs?: ApiKnowledgeBase_KnowledgeBases_LastIndexingJob_DataSourceJobs[] | Computed<ApiKnowledgeBase_KnowledgeBases_LastIndexingJob_DataSourceJobs[]>;
  dataSourceUuids?: string[] | Computed<string[]>;
  finishedAt?: string | Computed<string>;
  isReportAvailable?: boolean | Computed<boolean>;
  knowledgeBaseUuid?: string | Computed<string>;
  phase?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  tokens?: number | Computed<number>;
  totalDatasources?: number | Computed<number>;
  totalTokens?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiKnowledgeBase_KnowledgeBases_RerankingConfig {
  enabled?: boolean | Computed<boolean>;
  model?: string | Computed<string>;
}

export interface ApiKnowledgeBase_KnowledgeBases {
  addedToAgentAt?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  databaseId?: string | Computed<string>;
  embeddingModelUuid?: string | Computed<string>;
  isPublic?: boolean | Computed<boolean>;
  lastIndexingJob?: ApiKnowledgeBase_KnowledgeBases_LastIndexingJob | Computed<ApiKnowledgeBase_KnowledgeBases_LastIndexingJob>;
  name?: string | Computed<string>;
  projectId?: string | Computed<string>;
  region?: string | Computed<string>;
  rerankingConfig?: ApiKnowledgeBase_KnowledgeBases_RerankingConfig | Computed<ApiKnowledgeBase_KnowledgeBases_RerankingConfig>;
  tags?: string[] | Computed<string[]>;
  updatedAt?: string | Computed<string>;
  userId?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiKnowledgeBase_Links_Pages {
  /** First page */
  first?: string | Computed<string>;
  /** Last page */
  last?: string | Computed<string>;
  /** Next page */
  next?: string | Computed<string>;
  /** Previous page */
  previous?: string | Computed<string>;
}

export interface ApiKnowledgeBase_Links {
  /** Information about how to reach other pages */
  pages?: ApiKnowledgeBase_Links_Pages | Computed<ApiKnowledgeBase_Links_Pages>;
}

export interface ApiKnowledgeBase_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface ApiKnowledgeBaseConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface ApiKnowledgeBaseAttrs {
  /** The knowledge bases */
  knowledgeBases: ApiKnowledgeBase_KnowledgeBases[];
  /** Links to other pages */
  links: ApiKnowledgeBase_Links;
  /** Meta information about the data set */
  meta: ApiKnowledgeBase_Meta;
  page: number;
  perPage: number;
}

export const ApiKnowledgeBase: DataSourceBinding<ApiKnowledgeBaseConfig, ApiKnowledgeBaseAttrs> = {
  wireType: "digitalocean_api_knowledge_base",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
