// Code generated by `ubx sdk gen` from digitalocean_api_workspace. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApiWorkspace_Workspaces_Agents_AnthropicApiKey {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ApiKeyInfos {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  name?: string | Computed<string>;
  secretKey?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ApiKeys {
  apiKey?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Chatbot {
  allowedDomains?: string[] | Computed<string[]>;
  buttonBackgroundColor?: string | Computed<string>;
  logo?: string | Computed<string>;
  name?: string | Computed<string>;
  primaryColor?: string | Computed<string>;
  secondaryColor?: string | Computed<string>;
  startingMessage?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ChatbotIdentifiers {
  agentChatbotIdentifier?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ChildAgents {
}

export interface ApiWorkspace_Workspaces_Agents_Deployment {
  createdAt?: string | Computed<string>;
  name?: string | Computed<string>;
  status?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  uuid?: string | Computed<string>;
  visibility?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Functions {
  apiKey?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  description?: string | Computed<string>;
  faasName?: string | Computed<string>;
  faasNamespace?: string | Computed<string>;
  inputSchema?: unknown | Computed<unknown>;
  name?: string | Computed<string>;
  outputSchema?: unknown | Computed<unknown>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Guardrails {
  agentUuid?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  defaultResponse?: string | Computed<string>;
  description?: string | Computed<string>;
  guardrailUuid?: string | Computed<string>;
  isAttached?: boolean | Computed<boolean>;
  isDefault?: boolean | Computed<boolean>;
  metadata?: unknown | Computed<unknown>;
  name?: string | Computed<string>;
  priority?: number | Computed<number>;
  type?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_KnowledgeBases_LastIndexingJob_DataSourceJobs {
  completedAt?: string | Computed<string>;
  dataSourceUuid?: string | Computed<string>;
  errorDetails?: string | Computed<string>;
  errorMsg?: string | Computed<string>;
  failedItemCount?: string | Computed<string>;
  indexedFileCount?: string | Computed<string>;
  indexedItemCount?: string | Computed<string>;
  removedItemCount?: string | Computed<string>;
  skippedItemCount?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  totalBytes?: string | Computed<string>;
  totalBytesIndexed?: string | Computed<string>;
  totalFileCount?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_KnowledgeBases_LastIndexingJob {
  completedDatasources?: number | Computed<number>;
  createdAt?: string | Computed<string>;
  dataSourceJobs?: ApiWorkspace_Workspaces_Agents_KnowledgeBases_LastIndexingJob_DataSourceJobs[] | Computed<ApiWorkspace_Workspaces_Agents_KnowledgeBases_LastIndexingJob_DataSourceJobs[]>;
  dataSourceUuids?: string[] | Computed<string[]>;
  finishedAt?: string | Computed<string>;
  isReportAvailable?: boolean | Computed<boolean>;
  knowledgeBaseUuid?: string | Computed<string>;
  phase?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  tokens?: number | Computed<number>;
  totalDatasources?: number | Computed<number>;
  totalTokens?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_KnowledgeBases_RerankingConfig {
  enabled?: boolean | Computed<boolean>;
  model?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_KnowledgeBases {
  addedToAgentAt?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  databaseId?: string | Computed<string>;
  embeddingModelUuid?: string | Computed<string>;
  isPublic?: boolean | Computed<boolean>;
  lastIndexingJob?: ApiWorkspace_Workspaces_Agents_KnowledgeBases_LastIndexingJob | Computed<ApiWorkspace_Workspaces_Agents_KnowledgeBases_LastIndexingJob>;
  name?: string | Computed<string>;
  projectId?: string | Computed<string>;
  region?: string | Computed<string>;
  rerankingConfig?: ApiWorkspace_Workspaces_Agents_KnowledgeBases_RerankingConfig | Computed<ApiWorkspace_Workspaces_Agents_KnowledgeBases_RerankingConfig>;
  tags?: string[] | Computed<string[]>;
  updatedAt?: string | Computed<string>;
  userId?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_LoggingConfig {
  galileoProjectId?: string | Computed<string>;
  galileoProjectName?: string | Computed<string>;
  insightsEnabled?: boolean | Computed<boolean>;
  insightsEnabledAt?: string | Computed<string>;
  logStreamId?: string | Computed<string>;
  logStreamName?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_McpServers {
  allowedTools?: string[] | Computed<string[]>;
  authorization?: string | Computed<string>;
  headers?: Record<string, string> | Computed<Record<string, string>>;
  serverLabel?: string | Computed<string>;
  serverUrl?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Model_Agreement {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  url?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Model_Endpoints {
  capabilities?: string[] | Computed<string[]>;
  endpoint?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Model_Modalities {
  input?: string[] | Computed<string[]>;
  output?: string[] | Computed<string[]>;
}

export interface ApiWorkspace_Workspaces_Agents_Model_Settings {
  defaultString?: string | Computed<string>;
  defaultValue?: number | Computed<number>;
  max?: number | Computed<number>;
  min?: number | Computed<number>;
  name?: string | Computed<string>;
  options?: string[] | Computed<string[]>;
  step?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Model_Version {
  major?: number | Computed<number>;
  minor?: number | Computed<number>;
  patch?: number | Computed<number>;
}

export interface ApiWorkspace_Workspaces_Agents_Model {
  agreement?: ApiWorkspace_Workspaces_Agents_Model_Agreement | Computed<ApiWorkspace_Workspaces_Agents_Model_Agreement>;
  benchmarkScore?: unknown | Computed<unknown>;
  capabilities?: string[] | Computed<string[]>;
  contextWindow?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  endpoints?: ApiWorkspace_Workspaces_Agents_Model_Endpoints[] | Computed<ApiWorkspace_Workspaces_Agents_Model_Endpoints[]>;
  inferenceName?: string | Computed<string>;
  inferenceVersion?: string | Computed<string>;
  isFoundational?: boolean | Computed<boolean>;
  kbDefaultChunkSize?: number | Computed<number>;
  kbMaxChunkSize?: number | Computed<number>;
  kbMinChunkSize?: number | Computed<number>;
  lifecycleStatus?: string | Computed<string>;
  metadata?: unknown | Computed<unknown>;
  modalities?: ApiWorkspace_Workspaces_Agents_Model_Modalities | Computed<ApiWorkspace_Workspaces_Agents_Model_Modalities>;
  name?: string | Computed<string>;
  parameterCount?: number | Computed<number>;
  parentUuid?: string | Computed<string>;
  provider?: string | Computed<string>;
  reasoningEfforts?: string[] | Computed<string[]>;
  settings?: ApiWorkspace_Workspaces_Agents_Model_Settings[] | Computed<ApiWorkspace_Workspaces_Agents_Model_Settings[]>;
  thinking?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uploadComplete?: boolean | Computed<boolean>;
  url?: string | Computed<string>;
  usecases?: string[] | Computed<string[]>;
  uuid?: string | Computed<string>;
  version?: ApiWorkspace_Workspaces_Agents_Model_Version | Computed<ApiWorkspace_Workspaces_Agents_Model_Version>;
}

export interface ApiWorkspace_Workspaces_Agents_ModelProviderKey {
  apiKeyUuid?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  models?: ApiWorkspace_Workspaces_Agents_Model[] | Computed<ApiWorkspace_Workspaces_Agents_Model[]>;
  name?: string | Computed<string>;
  provider?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies_CustomTask {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies_SelectionPolicy {
  prefer?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies {
  customTask?: ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies_CustomTask | Computed<ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies_CustomTask>;
  models?: string[] | Computed<string[]>;
  selectionPolicy?: ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies_SelectionPolicy | Computed<ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies_SelectionPolicy>;
  taskSlug?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_ModelRouter_Config {
  fallbackModels?: string[] | Computed<string[]>;
  policies?: ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies[] | Computed<ApiWorkspace_Workspaces_Agents_ModelRouter_Config_Policies[]>;
}

export interface ApiWorkspace_Workspaces_Agents_ModelRouter {
  config?: ApiWorkspace_Workspaces_Agents_ModelRouter_Config | Computed<ApiWorkspace_Workspaces_Agents_ModelRouter_Config>;
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  regions?: string[] | Computed<string[]>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_OpenaiApiKey {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  models?: ApiWorkspace_Workspaces_Agents_Model[] | Computed<ApiWorkspace_Workspaces_Agents_Model[]>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Template_Guardrails {
  priority?: number | Computed<number>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents_Template {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  guardrails?: ApiWorkspace_Workspaces_Agents_Template_Guardrails[] | Computed<ApiWorkspace_Workspaces_Agents_Template_Guardrails[]>;
  instruction?: string | Computed<string>;
  k?: number | Computed<number>;
  knowledgeBases?: ApiWorkspace_Workspaces_Agents_KnowledgeBases[] | Computed<ApiWorkspace_Workspaces_Agents_KnowledgeBases[]>;
  longDescription?: string | Computed<string>;
  maxTokens?: number | Computed<number>;
  model?: ApiWorkspace_Workspaces_Agents_Model | Computed<ApiWorkspace_Workspaces_Agents_Model>;
  name?: string | Computed<string>;
  shortDescription?: string | Computed<string>;
  summary?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  temperature?: number | Computed<number>;
  templateType?: string | Computed<string>;
  topP?: number | Computed<number>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_Agents {
  anthropicApiKey?: ApiWorkspace_Workspaces_Agents_AnthropicApiKey | Computed<ApiWorkspace_Workspaces_Agents_AnthropicApiKey>;
  apiKeyInfos?: ApiWorkspace_Workspaces_Agents_ApiKeyInfos[] | Computed<ApiWorkspace_Workspaces_Agents_ApiKeyInfos[]>;
  apiKeys?: ApiWorkspace_Workspaces_Agents_ApiKeys[] | Computed<ApiWorkspace_Workspaces_Agents_ApiKeys[]>;
  chatbot?: ApiWorkspace_Workspaces_Agents_Chatbot | Computed<ApiWorkspace_Workspaces_Agents_Chatbot>;
  chatbotIdentifiers?: ApiWorkspace_Workspaces_Agents_ChatbotIdentifiers[] | Computed<ApiWorkspace_Workspaces_Agents_ChatbotIdentifiers[]>;
  childAgents?: ApiWorkspace_Workspaces_Agents_ChildAgents[] | Computed<ApiWorkspace_Workspaces_Agents_ChildAgents[]>;
  conversationLogsEnabled?: boolean | Computed<boolean>;
  createdAt?: string | Computed<string>;
  deployment?: ApiWorkspace_Workspaces_Agents_Deployment | Computed<ApiWorkspace_Workspaces_Agents_Deployment>;
  description?: string | Computed<string>;
  functions?: ApiWorkspace_Workspaces_Agents_Functions[] | Computed<ApiWorkspace_Workspaces_Agents_Functions[]>;
  guardrails?: ApiWorkspace_Workspaces_Agents_Guardrails[] | Computed<ApiWorkspace_Workspaces_Agents_Guardrails[]>;
  ifCase?: string | Computed<string>;
  instruction?: string | Computed<string>;
  k?: number | Computed<number>;
  knowledgeBases?: ApiWorkspace_Workspaces_Agents_KnowledgeBases[] | Computed<ApiWorkspace_Workspaces_Agents_KnowledgeBases[]>;
  loggingConfig?: ApiWorkspace_Workspaces_Agents_LoggingConfig | Computed<ApiWorkspace_Workspaces_Agents_LoggingConfig>;
  maxTokens?: number | Computed<number>;
  mcpServers?: ApiWorkspace_Workspaces_Agents_McpServers[] | Computed<ApiWorkspace_Workspaces_Agents_McpServers[]>;
  model?: ApiWorkspace_Workspaces_Agents_Model | Computed<ApiWorkspace_Workspaces_Agents_Model>;
  modelProviderKey?: ApiWorkspace_Workspaces_Agents_ModelProviderKey | Computed<ApiWorkspace_Workspaces_Agents_ModelProviderKey>;
  modelRouter?: ApiWorkspace_Workspaces_Agents_ModelRouter | Computed<ApiWorkspace_Workspaces_Agents_ModelRouter>;
  name?: string | Computed<string>;
  openaiApiKey?: ApiWorkspace_Workspaces_Agents_OpenaiApiKey | Computed<ApiWorkspace_Workspaces_Agents_OpenaiApiKey>;
  parentAgents?: ApiWorkspace_Workspaces_Agents_ChildAgents[] | Computed<ApiWorkspace_Workspaces_Agents_ChildAgents[]>;
  projectId?: string | Computed<string>;
  provideCitations?: boolean | Computed<boolean>;
  reasoningEffort?: string | Computed<string>;
  region?: string | Computed<string>;
  retrievalMethod?: string | Computed<string>;
  routeCreatedAt?: string | Computed<string>;
  routeCreatedBy?: string | Computed<string>;
  routeName?: string | Computed<string>;
  routeUuid?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  temperature?: number | Computed<number>;
  template?: ApiWorkspace_Workspaces_Agents_Template | Computed<ApiWorkspace_Workspaces_Agents_Template>;
  thinkingTokenBudget?: number | Computed<number>;
  topP?: number | Computed<number>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  userId?: string | Computed<string>;
  uuid?: string | Computed<string>;
  versionHash?: string | Computed<string>;
  vpcEgressIps?: string[] | Computed<string[]>;
  vpcUuid?: string | Computed<string>;
  webFetchEnabled?: boolean | Computed<boolean>;
  webSearchEnabled?: boolean | Computed<boolean>;
  workspace?: unknown | Computed<unknown>;
}

export interface ApiWorkspace_Workspaces_EvaluationTestCases_Dataset {
  createdAt?: string | Computed<string>;
  datasetName?: string | Computed<string>;
  datasetType?: string | Computed<string>;
  datasetUuid?: string | Computed<string>;
  fileSize?: string | Computed<string>;
  hasGroundTruth?: boolean | Computed<boolean>;
  rowCount?: number | Computed<number>;
}

export interface ApiWorkspace_Workspaces_EvaluationTestCases_Metrics_AssociatedPresets {
  evalPresetUuid?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_EvaluationTestCases_Metrics_CustomEvalConfig {
  createdAt?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  requiresGroundTruth?: boolean | Computed<boolean>;
  scoringPrompt?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_EvaluationTestCases_Metrics {
  associatedPresets?: ApiWorkspace_Workspaces_EvaluationTestCases_Metrics_AssociatedPresets[] | Computed<ApiWorkspace_Workspaces_EvaluationTestCases_Metrics_AssociatedPresets[]>;
  category?: string | Computed<string>;
  customEvalConfig?: ApiWorkspace_Workspaces_EvaluationTestCases_Metrics_CustomEvalConfig | Computed<ApiWorkspace_Workspaces_EvaluationTestCases_Metrics_CustomEvalConfig>;
  description?: string | Computed<string>;
  evaluationScope?: string | Computed<string>;
  inverted?: boolean | Computed<boolean>;
  isMetricGoal?: boolean | Computed<boolean>;
  metricName?: string | Computed<string>;
  metricRank?: number | Computed<number>;
  metricType?: string | Computed<string>;
  metricUuid?: string | Computed<string>;
  metricValueType?: string | Computed<string>;
  rangeMax?: number | Computed<number>;
  rangeMin?: number | Computed<number>;
  source?: string | Computed<string>;
}

export interface ApiWorkspace_Workspaces_EvaluationTestCases_StarMetric {
  metricUuid?: string | Computed<string>;
  name?: string | Computed<string>;
  successThreshold?: number | Computed<number>;
  successThresholdPct?: number | Computed<number>;
}

export interface ApiWorkspace_Workspaces_EvaluationTestCases {
  archivedAt?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  createdByUserEmail?: string | Computed<string>;
  createdByUserId?: string | Computed<string>;
  dataset?: ApiWorkspace_Workspaces_EvaluationTestCases_Dataset | Computed<ApiWorkspace_Workspaces_EvaluationTestCases_Dataset>;
  datasetName?: string | Computed<string>;
  datasetUuid?: string | Computed<string>;
  description?: string | Computed<string>;
  latestVersionNumberOfRuns?: number | Computed<number>;
  metrics?: ApiWorkspace_Workspaces_EvaluationTestCases_Metrics[] | Computed<ApiWorkspace_Workspaces_EvaluationTestCases_Metrics[]>;
  name?: string | Computed<string>;
  starMetric?: ApiWorkspace_Workspaces_EvaluationTestCases_StarMetric | Computed<ApiWorkspace_Workspaces_EvaluationTestCases_StarMetric>;
  testCaseUuid?: string | Computed<string>;
  totalRuns?: number | Computed<number>;
  updatedAt?: string | Computed<string>;
  updatedByUserEmail?: string | Computed<string>;
  updatedByUserId?: string | Computed<string>;
  version?: number | Computed<number>;
}

export interface ApiWorkspace_Workspaces {
  agents?: ApiWorkspace_Workspaces_Agents[] | Computed<ApiWorkspace_Workspaces_Agents[]>;
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  createdByEmail?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  description?: string | Computed<string>;
  evaluationTestCases?: ApiWorkspace_Workspaces_EvaluationTestCases[] | Computed<ApiWorkspace_Workspaces_EvaluationTestCases[]>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiWorkspaceConfig {
}

export interface ApiWorkspaceAttrs {
  /** Workspaces */
  workspaces: ApiWorkspace_Workspaces[];
}

export const ApiWorkspace: DataSourceBinding<ApiWorkspaceConfig, ApiWorkspaceAttrs> = {
  wireType: "digitalocean_api_workspace",
  fields: {
  },
};
