// Code generated by `ubx sdk gen` from digitalocean_api_list_model_catalog_output. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApiListModelCatalogOutput_Data_Pricing {
  cacheReadInputPricePerMillion?: number | Computed<number>;
  cacheWrite1hInputPricePerMillion?: number | Computed<number>;
  cacheWrite5mInputPricePerMillion?: number | Computed<number>;
  imageCacheReadInputPricePerMillion?: number | Computed<number>;
  imageInputPricePerMillion?: number | Computed<number>;
  imageOutputPricePerMillion?: number | Computed<number>;
  inputCacheRead?: number | Computed<number>;
  inputPricePerMillion?: number | Computed<number>;
  outputPricePerMillion?: number | Computed<number>;
  pricePerAudio?: number | Computed<number>;
  pricePerImage?: number | Computed<number>;
  pricePerMegapixel?: number | Computed<number>;
  pricePerSecond?: number | Computed<number>;
  pricePerThousandCharacters?: number | Computed<number>;
  pricePerVideo?: number | Computed<number>;
  reasoningPricePerMillion?: number | Computed<number>;
  textCacheReadInputPricePerMillion?: number | Computed<number>;
  textInputPricePerMillion?: number | Computed<number>;
  textOutputPricePerMillion?: number | Computed<number>;
}

export interface ApiListModelCatalogOutput_Data {
  availability?: string[] | Computed<string[]>;
  badges?: string[] | Computed<string[]>;
  benchmarkScore?: unknown | Computed<unknown>;
  capabilities?: string[] | Computed<string[]>;
  contextWindow?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  creator?: string | Computed<string>;
  huggingFaceId?: string | Computed<string>;
  id?: string | Computed<string>;
  maxOutputTokens?: string | Computed<string>;
  modelId?: string | Computed<string>;
  name?: string | Computed<string>;
  parameterCount?: number | Computed<number>;
  pricing?: ApiListModelCatalogOutput_Data_Pricing | Computed<ApiListModelCatalogOutput_Data_Pricing>;
  provider?: string | Computed<string>;
  scaledPricingEnabled?: boolean | Computed<boolean>;
  shortDescription?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface ApiListModelCatalogOutput_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface ApiListModelCatalogOutputConfig {
  availability?: string[] | Computed<string[]>;
  badges?: string[] | Computed<string[]>;
  limit?: number | Computed<number>;
  modelType?: string[] | Computed<string[]>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  provider?: string[] | Computed<string[]>;
  search?: string | Computed<string>;
  sortBy?: string | Computed<string>;
  sortDirection?: string | Computed<string>;
  useCase?: string | Computed<string>;
}

export interface ApiListModelCatalogOutputAttrs {
  availability: string[];
  /** All deployment availability values the client can offer in the availability filter UI. */
  availableAvailability: string[];
  /** All badge values the client can offer in the badges filter UI. */
  availableBadges: string[];
  /** All model type values the client can offer in the type filter UI. */
  availableModelTypes: string[];
  /** All provider values the client can offer in the provider filter UI. */
  availableProviders: string[];
  /** All sort-by field values the client can offer in the sort UI. */
  availableSortBy: string[];
  /** All sort-direction values the client can offer in the sort UI. */
  availableSortDirections: string[];
  badges: string[];
  data: ApiListModelCatalogOutput_Data[];
  limit: number;
  /** Meta information about the data set */
  meta: ApiListModelCatalogOutput_Meta;
  modelType: string[];
  page: number;
  perPage: number;
  provider: string[];
  search: string;
  sortBy: string;
  sortDirection: string;
  useCase: string;
}

export const ApiListModelCatalogOutput: DataSourceBinding<ApiListModelCatalogOutputConfig, ApiListModelCatalogOutputAttrs> = {
  wireType: "digitalocean_api_list_model_catalog_output",
  fields: {
    availability: "availability",
    badges: "badges",
    limit: "limit",
    modelType: "model_type",
    page: "page",
    perPage: "per_page",
    provider: "provider",
    search: "search",
    sortBy: "sort_by",
    sortDirection: "sort_direction",
    useCase: "use_case",
  },
};
