// Code generated by `ubx sdk gen` from digitalocean_api_get_indexing_job_details_signed_urloutput. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApiGetIndexingJobDetailsSignedUrloutputConfig {
  indexingJobUuid: string | Computed<string>;
}

export interface ApiGetIndexingJobDetailsSignedUrloutputAttrs {
  indexingJobUuid: string;
  /** The signed url for downloading the indexing job details */
  signedUrl: string;
}

export const ApiGetIndexingJobDetailsSignedUrloutput: DataSourceBinding<ApiGetIndexingJobDetailsSignedUrloutputConfig, ApiGetIndexingJobDetailsSignedUrloutputAttrs> = {
  wireType: "digitalocean_api_get_indexing_job_details_signed_urloutput",
  fields: {
    indexingJobUuid: "indexing_job_uuid",
  },
};
