// Code generated by `ubx sdk gen` from digitalocean_api_model_apikey_info. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ApiModelApikeyInfo_ApiKeyInfos {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  name?: string | Computed<string>;
  secretKey?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ApiModelApikeyInfo_Links_Pages {
  /** First page */
  first?: string | Computed<string>;
  /** Last page */
  last?: string | Computed<string>;
  /** Next page */
  next?: string | Computed<string>;
  /** Previous page */
  previous?: string | Computed<string>;
}

export interface ApiModelApikeyInfo_Links {
  /** Information about how to reach other pages */
  pages?: ApiModelApikeyInfo_Links_Pages | Computed<ApiModelApikeyInfo_Links_Pages>;
}

export interface ApiModelApikeyInfo_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface ApiModelApikeyInfoConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface ApiModelApikeyInfoAttrs {
  /** Api key infos */
  apiKeyInfos: ApiModelApikeyInfo_ApiKeyInfos[];
  /** Links to other pages */
  links: ApiModelApikeyInfo_Links;
  /** Meta information about the data set */
  meta: ApiModelApikeyInfo_Meta;
  page: number;
  perPage: number;
}

export const ApiModelApikeyInfo: DataSourceBinding<ApiModelApikeyInfoConfig, ApiModelApikeyInfoAttrs> = {
  wireType: "digitalocean_api_model_apikey_info",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
