// Code generated by `ubx sdk gen` from digitalocean_droplet. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Droplet_Droplets_DiskInfo_Size {
  amount?: number | Computed<number>;
  unit?: string | Computed<string>;
}

export interface Droplet_Droplets_DiskInfo {
  size?: Droplet_Droplets_DiskInfo_Size | Computed<Droplet_Droplets_DiskInfo_Size>;
  type?: string | Computed<string>;
}

export interface Droplet_Droplets_GpuInfo {
  count?: number | Computed<number>;
  model?: string | Computed<string>;
  vram?: Droplet_Droplets_DiskInfo_Size | Computed<Droplet_Droplets_DiskInfo_Size>;
}

export interface Droplet_Droplets_Image {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  distribution?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
  id?: number | Computed<number>;
  minDiskSize?: number | Computed<number>;
  name?: string | Computed<string>;
  public?: boolean | Computed<boolean>;
  regions?: string[] | Computed<string[]>;
  sizeGigabytes?: number | Computed<number>;
  slug?: string | Computed<string>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  type?: string | Computed<string>;
}

export interface Droplet_Droplets_Kernel {
  id?: number | Computed<number>;
  name?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface Droplet_Droplets_Networks_V4 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Droplet_Droplets_Networks_V6 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface Droplet_Droplets_Networks {
  v4?: Droplet_Droplets_Networks_V4[] | Computed<Droplet_Droplets_Networks_V4[]>;
  v6?: Droplet_Droplets_Networks_V6[] | Computed<Droplet_Droplets_Networks_V6[]>;
}

export interface Droplet_Droplets_NextBackupWindow {
  end?: string | Computed<string>;
  start?: string | Computed<string>;
}

export interface Droplet_Droplets_Region {
  available?: boolean | Computed<boolean>;
  features?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  sizes?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
}

export interface Droplet_Droplets_Size {
  available?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: Droplet_Droplets_DiskInfo[] | Computed<Droplet_Droplets_DiskInfo[]>;
  gpuInfo?: Droplet_Droplets_GpuInfo | Computed<Droplet_Droplets_GpuInfo>;
  memory?: number | Computed<number>;
  priceHourly?: number | Computed<number>;
  priceMonthly?: number | Computed<number>;
  regions?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
  transfer?: number | Computed<number>;
  vcpus?: number | Computed<number>;
}

export interface Droplet_Droplets {
  backupIds?: number[] | Computed<number[]>;
  createdAt?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: Droplet_Droplets_DiskInfo[] | Computed<Droplet_Droplets_DiskInfo[]>;
  features?: string[] | Computed<string[]>;
  gpuInfo?: Droplet_Droplets_GpuInfo | Computed<Droplet_Droplets_GpuInfo>;
  id?: number | Computed<number>;
  image?: Droplet_Droplets_Image | Computed<Droplet_Droplets_Image>;
  kernel?: Droplet_Droplets_Kernel | Computed<Droplet_Droplets_Kernel>;
  locked?: boolean | Computed<boolean>;
  memory?: number | Computed<number>;
  name?: string | Computed<string>;
  networks?: Droplet_Droplets_Networks | Computed<Droplet_Droplets_Networks>;
  nextBackupWindow?: Droplet_Droplets_NextBackupWindow | Computed<Droplet_Droplets_NextBackupWindow>;
  region?: Droplet_Droplets_Region | Computed<Droplet_Droplets_Region>;
  size?: Droplet_Droplets_Size | Computed<Droplet_Droplets_Size>;
  sizeSlug?: string | Computed<string>;
  snapshotIds?: number[] | Computed<number[]>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  vcpus?: number | Computed<number>;
  volumeIds?: string[] | Computed<string[]>;
  vpcUuid?: string | Computed<string>;
}

export interface Droplet_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Droplet_Meta {
  total?: number | Computed<number>;
}

export interface DropletConfig {
  name?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  tagName?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface DropletAttrs {
  droplets: Droplet_Droplets[];
  links: Droplet_Links;
  meta: Droplet_Meta;
  name: string;
  page: number;
  perPage: number;
  tagName: string;
  type: string;
}

export const Droplet: DataSourceBinding<DropletConfig, DropletAttrs> = {
  wireType: "digitalocean_droplet",
  fields: {
    name: "name",
    page: "page",
    perPage: "per_page",
    tagName: "tag_name",
    type: "type",
  },
};
