// Code generated by `ubx sdk gen` from digitalocean_neighbor. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Neighbor_Droplets_DiskInfo_Size {
  amount?: number | Computed<number>;
  unit?: string | Computed<string>;
}

export interface Neighbor_Droplets_DiskInfo {
  size?: Neighbor_Droplets_DiskInfo_Size | Computed<Neighbor_Droplets_DiskInfo_Size>;
  type?: string | Computed<string>;
}

export interface Neighbor_Droplets_GpuInfo {
  count?: number | Computed<number>;
  model?: string | Computed<string>;
  vram?: Neighbor_Droplets_DiskInfo_Size | Computed<Neighbor_Droplets_DiskInfo_Size>;
}

export interface Neighbor_Droplets_Image {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  distribution?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
  id?: number | Computed<number>;
  minDiskSize?: number | Computed<number>;
  name?: string | Computed<string>;
  public?: boolean | Computed<boolean>;
  regions?: string[] | Computed<string[]>;
  sizeGigabytes?: number | Computed<number>;
  slug?: string | Computed<string>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  type?: string | Computed<string>;
}

export interface Neighbor_Droplets_Kernel {
  id?: number | Computed<number>;
  name?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface Neighbor_Droplets_Networks_V4 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Neighbor_Droplets_Networks_V6 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface Neighbor_Droplets_Networks {
  v4?: Neighbor_Droplets_Networks_V4[] | Computed<Neighbor_Droplets_Networks_V4[]>;
  v6?: Neighbor_Droplets_Networks_V6[] | Computed<Neighbor_Droplets_Networks_V6[]>;
}

export interface Neighbor_Droplets_NextBackupWindow {
  end?: string | Computed<string>;
  start?: string | Computed<string>;
}

export interface Neighbor_Droplets_Region {
  available?: boolean | Computed<boolean>;
  features?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  sizes?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
}

export interface Neighbor_Droplets_Size {
  available?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: Neighbor_Droplets_DiskInfo[] | Computed<Neighbor_Droplets_DiskInfo[]>;
  gpuInfo?: Neighbor_Droplets_GpuInfo | Computed<Neighbor_Droplets_GpuInfo>;
  memory?: number | Computed<number>;
  priceHourly?: number | Computed<number>;
  priceMonthly?: number | Computed<number>;
  regions?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
  transfer?: number | Computed<number>;
  vcpus?: number | Computed<number>;
}

export interface Neighbor_Droplets {
  backupIds?: number[] | Computed<number[]>;
  createdAt?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: Neighbor_Droplets_DiskInfo[] | Computed<Neighbor_Droplets_DiskInfo[]>;
  features?: string[] | Computed<string[]>;
  gpuInfo?: Neighbor_Droplets_GpuInfo | Computed<Neighbor_Droplets_GpuInfo>;
  id?: number | Computed<number>;
  image?: Neighbor_Droplets_Image | Computed<Neighbor_Droplets_Image>;
  kernel?: Neighbor_Droplets_Kernel | Computed<Neighbor_Droplets_Kernel>;
  locked?: boolean | Computed<boolean>;
  memory?: number | Computed<number>;
  name?: string | Computed<string>;
  networks?: Neighbor_Droplets_Networks | Computed<Neighbor_Droplets_Networks>;
  nextBackupWindow?: Neighbor_Droplets_NextBackupWindow | Computed<Neighbor_Droplets_NextBackupWindow>;
  region?: Neighbor_Droplets_Region | Computed<Neighbor_Droplets_Region>;
  size?: Neighbor_Droplets_Size | Computed<Neighbor_Droplets_Size>;
  sizeSlug?: string | Computed<string>;
  snapshotIds?: number[] | Computed<number[]>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  vcpus?: number | Computed<number>;
  volumeIds?: string[] | Computed<string[]>;
  vpcUuid?: string | Computed<string>;
}

export interface NeighborConfig {
  dropletId: number | Computed<number>;
}

export interface NeighborAttrs {
  dropletId: number;
  droplets: Neighbor_Droplets[];
}

export const Neighbor: DataSourceBinding<NeighborConfig, NeighborAttrs> = {
  wireType: "digitalocean_neighbor",
  fields: {
    dropletId: "droplet_id",
  },
};
