// Code generated by `ubx sdk gen` from digitalocean_snapshot. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Snapshot_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Snapshot_Meta {
  total?: number | Computed<number>;
}

export interface Snapshot_Snapshots {
  createdAt?: string | Computed<string>;
  id?: number | Computed<number>;
  minDiskSize?: number | Computed<number>;
  name?: string | Computed<string>;
  regions?: string[] | Computed<string[]>;
  sizeGigabytes?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface SnapshotConfig {
  dropletId: number | Computed<number>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface SnapshotAttrs {
  dropletId: number;
  links: Snapshot_Links;
  meta: Snapshot_Meta;
  page: number;
  perPage: number;
  snapshots: Snapshot_Snapshots[];
}

export const Snapshot: DataSourceBinding<SnapshotConfig, SnapshotAttrs> = {
  wireType: "digitalocean_snapshot",
  fields: {
    dropletId: "droplet_id",
    page: "page",
    perPage: "per_page",
  },
};
