// Code generated by `ubx sdk gen` from digitalocean_supported_droplet_backup_policy. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SupportedDropletBackupPolicy_SupportedPolicies {
  name?: string | Computed<string>;
  possibleDays?: string[] | Computed<string[]>;
  possibleWindowStarts?: number[] | Computed<number[]>;
  retentionPeriodDays?: number | Computed<number>;
  windowLengthHours?: number | Computed<number>;
}

export interface SupportedDropletBackupPolicyConfig {
}

export interface SupportedDropletBackupPolicyAttrs {
  supportedPolicies: SupportedDropletBackupPolicy_SupportedPolicies[];
}

export const SupportedDropletBackupPolicy: DataSourceBinding<SupportedDropletBackupPolicyConfig, SupportedDropletBackupPolicyAttrs> = {
  wireType: "digitalocean_supported_droplet_backup_policy",
  fields: {
  },
};
