// Code generated by `ubx sdk gen` from digitalocean_vpc_nat_gateway. DO NOT EDIT.
package vpcnatgateways

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VpcNatGateway_VpcNatGateway_Egresses_PublicGateways struct {
	Ipv4 any
}

type VpcNatGateway_VpcNatGateway_Egresses struct {
	// An array of public gateway IP addresses for the VPC NAT gateway.
	PublicGateways any
}

type VpcNatGateway_VpcNatGateway_Vpcs struct {
	GatewayIp any
	VpcUuid   any
}

type VpcNatGateway_VpcNatGateway struct {
	// A time value given in ISO8601 combined date and time format that represents when the VPC NAT gateway was created.
	CreatedAt any
	// An object containing egress information for the VPC NAT gateway.
	Egresses any
	// The ICMP timeout in seconds for the VPC NAT gateway.
	IcmpTimeoutSeconds any
	// The unique identifier for the VPC NAT gateway. This is automatically generated upon creation.
	Id any
	// The human-readable name of the VPC NAT gateway.
	Name any
	// The region in which the VPC NAT gateway is created.
	Region any
	// The size of the VPC NAT gateway.
	Size any
	// The current state of the VPC NAT gateway.
	State any
	// The TCP timeout in seconds for the VPC NAT gateway.
	TcpTimeoutSeconds any
	// The type of the VPC NAT gateway.
	Type any
	// The UDP timeout in seconds for the VPC NAT gateway.
	UdpTimeoutSeconds any
	// A time value given in ISO8601 combined date and time format that represents when the VPC NAT gateway was last updated.
	UpdatedAt any
	// An array of VPCs associated with the VPC NAT gateway.
	Vpcs any
}

type VpcNatGateway_Vpcs struct {
	DefaultGateway any
	VpcUuid        any
}

var VpcNatGateway_VpcsFields = ubx.FieldMap{
	"DefaultGateway": ubx.FieldSpec{WireName: "default_gateway"},
	"VpcUuid":        ubx.FieldSpec{WireName: "vpc_uuid"},
}

type VpcNatGatewayConfig struct {
	// The ICMP timeout in seconds for the VPC NAT gateway.
	IcmpTimeoutSeconds any
	// The human-readable name of the VPC NAT gateway.
	Name any
	// The region in which the VPC NAT gateway is created.
	Region any
	// The size of the VPC NAT gateway.
	Size any
	// The TCP timeout in seconds for the VPC NAT gateway.
	TcpTimeoutSeconds any
	// The type of the VPC NAT gateway.
	Type any
	// The UDP timeout in seconds for the VPC NAT gateway.
	UdpTimeoutSeconds any
	// An array of VPCs associated with the VPC NAT gateway.
	Vpcs any
	// path parameter, not part of the API's own resource representation
	Id any
}

type VpcNatGatewayAttrs struct {
	// The ICMP timeout in seconds for the VPC NAT gateway.
	IcmpTimeoutSeconds any
	// The human-readable name of the VPC NAT gateway.
	Name any
	// The region in which the VPC NAT gateway is created.
	Region any
	// The size of the VPC NAT gateway.
	Size any
	// The TCP timeout in seconds for the VPC NAT gateway.
	TcpTimeoutSeconds any
	// The type of the VPC NAT gateway.
	Type any
	// The UDP timeout in seconds for the VPC NAT gateway.
	UdpTimeoutSeconds any
	VpcNatGateway     any
	// An array of VPCs associated with the VPC NAT gateway.
	Vpcs any
	// path parameter, not part of the API's own resource representation
	Id any
}

var VpcNatGateway = ubx.ResourceBinding{
	WireType: "digitalocean_vpc_nat_gateway",
	Fields: ubx.FieldMap{
		"IcmpTimeoutSeconds": ubx.FieldSpec{WireName: "icmp_timeout_seconds"},
		"Name":               ubx.FieldSpec{WireName: "name"},
		"Region":             ubx.FieldSpec{WireName: "region"},
		"Size":               ubx.FieldSpec{WireName: "size"},
		"TcpTimeoutSeconds":  ubx.FieldSpec{WireName: "tcp_timeout_seconds"},
		"Type":               ubx.FieldSpec{WireName: "type"},
		"UdpTimeoutSeconds":  ubx.FieldSpec{WireName: "udp_timeout_seconds"},
		"Vpcs": ubx.FieldSpec{
			WireName: "vpcs",
			Kind:     "list",
			Fields:   VpcNatGateway_VpcsFields,
		},
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
