# Code generated by `ubx sdk gen` from digitalocean_check. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Check_Check:
    enabled: Any = None
    id: Any = None
    name: Any = None
    regions: Any = None
    target: Any = None
    type: Any = None

@dataclasses.dataclass
class CheckConfig:
    # A boolean value indicating whether the check is enabled/disabled.
    enabled: Any = None
    # A human-friendly display name.
    name: Any = None
    # An array containing the selected regions to perform healthchecks from.
    regions: Any = None
    # The endpoint to perform healthchecks on.
    target: Any = None
    # The type of health check to perform.
    type: Any = None
    # path parameter, not part of the API's own resource representation
    check_id: Any = None

@dataclasses.dataclass
class CheckAttrs:
    # The Uptime check's own real, current representation. (AI-inferred)
    check: Any = None
    # A boolean value indicating whether the check is enabled/disabled.
    enabled: Any = None
    # A human-friendly display name.
    name: Any = None
    # An array containing the selected regions to perform healthchecks from.
    regions: Any = None
    # The endpoint to perform healthchecks on.
    target: Any = None
    # The type of health check to perform.
    type: Any = None
    # path parameter, not part of the API's own resource representation
    check_id: Any = None

Check = ubx.ResourceBinding(
    wire_type="digitalocean_check",
    fields={
        "enabled": ubx.FieldSpec(wire_name="enabled"),
        "name": ubx.FieldSpec(wire_name="name"),
        "regions": ubx.FieldSpec(wire_name="regions"),
        "target": ubx.FieldSpec(wire_name="target"),
        "type": ubx.FieldSpec(wire_name="type"),
        "check_id": ubx.FieldSpec(wire_name="check_id"),
    },
)
