// Code generated by `ubx sdk gen` from digitalocean_byoip_prefixe. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Prefixe_ByoipPrefix_Validations {
  name?: string | Computed<string>;
  note?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface Prefixe_ByoipPrefix {
  /** Whether the BYOIP prefix is being advertised */
  advertised?: boolean | Computed<boolean>;
  /** Reason for failure, if applicable */
  failureReason?: string | Computed<string>;
  /** Whether the BYOIP prefix is locked */
  locked?: boolean | Computed<boolean>;
  /** Name of the BYOIP prefix */
  name?: string | Computed<string>;
  /** The IP prefix in CIDR notation */
  prefix?: string | Computed<string>;
  /** The ID of the project associated with the BYOIP prefix */
  projectId?: string | Computed<string>;
  /** Region where the BYOIP prefix is located */
  region?: string | Computed<string>;
  /** Status of the BYOIP prefix */
  status?: string | Computed<string>;
  /** Unique identifier for the BYOIP prefix */
  uuid?: string | Computed<string>;
  /** List of validation statuses for the BYOIP prefix */
  validations?: Prefixe_ByoipPrefix_Validations[] | Computed<Prefixe_ByoipPrefix_Validations[]>;
}

export interface PrefixeConfig {
  /** The IP prefix in CIDR notation to bring */
  prefix: string | Computed<string>;
  /** The region where the prefix will be created */
  region: string | Computed<string>;
  /** The signature hash for the prefix creation request */
  signature: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  byoipPrefixUuid: string | Computed<string>;
}

export interface PrefixeAttrs {
  byoipPrefix: Prefixe_ByoipPrefix;
  /** The IP prefix in CIDR notation to bring */
  prefix: string;
  /** The region where the prefix will be created */
  region: string;
  /** The signature hash for the prefix creation request */
  signature: string;
  /** path parameter, not part of the API's own resource representation */
  byoipPrefixUuid: string;
}

export const Prefixe: ResourceBinding<PrefixeConfig, PrefixeAttrs> = {
  wireType: "digitalocean_byoip_prefixe",
  fields: {
    prefix: "prefix",
    region: "region",
    signature: "signature",
    byoipPrefixUuid: "byoip_prefix_uuid",
  },
};
