# Code generated by `ubx sdk gen` from digitalocean_siz. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Siz_Links:
    pages: Any = None

@dataclasses.dataclass
class Siz_Meta:
    total: Any = None

@dataclasses.dataclass
class Siz_Sizes_DiskInfo_Size:
    amount: Any = None
    unit: Any = None

@dataclasses.dataclass
class Siz_Sizes_DiskInfo:
    size: Any = None
    type: Any = None

@dataclasses.dataclass
class Siz_Sizes_GpuInfo:
    count: Any = None
    model: Any = None
    vram: Any = None

@dataclasses.dataclass
class Siz_Sizes:
    available: Any = None
    description: Any = None
    disk: Any = None
    disk_info: Any = None
    gpu_info: Any = None
    memory: Any = None
    price_hourly: Any = None
    price_monthly: Any = None
    regions: Any = None
    slug: Any = None
    transfer: Any = None
    vcpus: Any = None

@dataclasses.dataclass
class SizConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class SizAttrs:
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None
    sizes: Any = None

Siz = ubx.DataSourceBinding(
    wire_type="digitalocean_siz",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
