// Code generated by `ubx sdk gen` from digitalocean_affected_resource. DO NOT EDIT.
package security

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AffectedResource_AffectedResources struct {
	Name any
	Type any
	Urn  any
}

type AffectedResourceConfig struct {
	FindingUuid any
	Page        any
	PerPage     any
	ScanId      any
}

type AffectedResourceAttrs struct {
	AffectedResources any
	FindingUuid       any
	Page              any
	PerPage           any
	ScanId            any
}

var AffectedResource = ubx.DataSourceBinding{
	WireType: "digitalocean_affected_resource",
	Fields: ubx.FieldMap{
		"FindingUuid": ubx.FieldSpec{WireName: "finding_uuid"},
		"Page":        ubx.FieldSpec{WireName: "page"},
		"PerPage":     ubx.FieldSpec{WireName: "per_page"},
		"ScanId":      ubx.FieldSpec{WireName: "scan_id"},
	},
}
