// Code generated by `ubx sdk gen` from digitalocean_events_logs. DO NOT EDIT.
package events

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Logs_Events struct {
	ClusterName any
	CreateTime any
	EventType any
	Id any
}

type LogsConfig struct {
	DatabaseClusterUuid any
}

type LogsAttrs struct {
	DatabaseClusterUuid any
	Events any
}

var Logs = ubx.DataSourceBinding{
	WireType: "digitalocean_events_logs",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
	},
}
