// Code generated by `ubx sdk gen` from digitalocean_api_anthropic_apikey_info. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AnthropicApikeyInfo_ApiKeyInfos {
  createdAt?: string | Computed<string>;
  createdBy?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface AnthropicApikeyInfo_Links_Pages {
  /** First page */
  first?: string | Computed<string>;
  /** Last page */
  last?: string | Computed<string>;
  /** Next page */
  next?: string | Computed<string>;
  /** Previous page */
  previous?: string | Computed<string>;
}

export interface AnthropicApikeyInfo_Links {
  /** Information about how to reach other pages */
  pages?: AnthropicApikeyInfo_Links_Pages | Computed<AnthropicApikeyInfo_Links_Pages>;
}

export interface AnthropicApikeyInfo_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface AnthropicApikeyInfoConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface AnthropicApikeyInfoAttrs {
  /** Api key infos */
  apiKeyInfos: AnthropicApikeyInfo_ApiKeyInfos[];
  /** Links to other pages */
  links: AnthropicApikeyInfo_Links;
  /** Meta information about the data set */
  meta: AnthropicApikeyInfo_Meta;
  page: number;
  perPage: number;
}

export const AnthropicApikeyInfo: DataSourceBinding<AnthropicApikeyInfoConfig, AnthropicApikeyInfoAttrs> = {
  wireType: "digitalocean_api_anthropic_apikey_info",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
