// Code generated by `ubx sdk gen` from digitalocean_api_custom_model. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CustomModel_Links_Pages {
  /** First page */
  first?: string | Computed<string>;
  /** Last page */
  last?: string | Computed<string>;
  /** Next page */
  next?: string | Computed<string>;
  /** Previous page */
  previous?: string | Computed<string>;
}

export interface CustomModel_Links {
  /** Information about how to reach other pages */
  pages?: CustomModel_Links_Pages | Computed<CustomModel_Links_Pages>;
}

export interface CustomModel_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface CustomModel_Models_ActiveDeployments_Endpoints {
  privateEndpointFqdn?: string | Computed<string>;
  publicEndpointFqdn?: string | Computed<string>;
}

export interface CustomModel_Models_ActiveDeployments {
  createdAt?: string | Computed<string>;
  endpoints?: CustomModel_Models_ActiveDeployments_Endpoints | Computed<CustomModel_Models_ActiveDeployments_Endpoints>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  regionSlug?: string | Computed<string>;
  state?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface CustomModel_Models_SourceRef {
  accessType?: string | Computed<string>;
  bucket?: string | Computed<string>;
  commitSha?: string | Computed<string>;
  hfToken?: string | Computed<string>;
  prefix?: string | Computed<string>;
  region?: string | Computed<string>;
  repoId?: string | Computed<string>;
}

export interface CustomModel_Models_Tags {
  tags?: string[] | Computed<string[]>;
}

export interface CustomModel_Models {
  activeDeployments?: CustomModel_Models_ActiveDeployments[] | Computed<CustomModel_Models_ActiveDeployments[]>;
  architecture?: string | Computed<string>;
  configJson?: unknown | Computed<unknown>;
  contextLength?: number | Computed<number>;
  costEstimatePerMonth?: number | Computed<number>;
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
  fileCount?: number | Computed<number>;
  inputModalities?: string[] | Computed<string[]>;
  license?: string | Computed<string>;
  name?: string | Computed<string>;
  outputModalities?: string[] | Computed<string[]>;
  parameters?: string | Computed<string>;
  sourceRef?: CustomModel_Models_SourceRef | Computed<CustomModel_Models_SourceRef>;
  sourceType?: string | Computed<string>;
  status?: string | Computed<string>;
  storageRegion?: string | Computed<string>;
  tags?: CustomModel_Models_Tags | Computed<CustomModel_Models_Tags>;
  teamId?: string | Computed<string>;
  totalSizeBytes?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface CustomModelConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  status?: string | Computed<string>;
}

export interface CustomModelAttrs {
  /** Links to other pages */
  links: CustomModel_Links;
  /** Maximum number of custom models allowed for this team's tier */
  maxThreshold: number;
  /** Meta information about the data set */
  meta: CustomModel_Meta;
  /** List of custom models */
  models: CustomModel_Models[];
  page: number;
  perPage: number;
  status: string;
}

export const CustomModel: DataSourceBinding<CustomModelConfig, CustomModelAttrs> = {
  wireType: "digitalocean_api_custom_model",
  fields: {
    page: "page",
    perPage: "per_page",
    status: "status",
  },
};
