// Code generated by `ubx sdk gen` from digitalocean_api_generate_oauth2_urloutput. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface GenerateOauth2UrloutputConfig {
  redirectUrl?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface GenerateOauth2UrloutputAttrs {
  redirectUrl: string;
  type: string;
  /** The oauth2 url */
  url: string;
}

export const GenerateOauth2Urloutput: DataSourceBinding<GenerateOauth2UrloutputConfig, GenerateOauth2UrloutputAttrs> = {
  wireType: "digitalocean_api_generate_oauth2_urloutput",
  fields: {
    redirectUrl: "redirect_url",
    type: "type",
  },
};
