// Code generated by `ubx sdk gen` from digitalocean_api_indexed_data_source. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IndexedDataSource_IndexedDataSources {
  completedAt?: string | Computed<string>;
  dataSourceUuid?: string | Computed<string>;
  errorDetails?: string | Computed<string>;
  errorMsg?: string | Computed<string>;
  failedItemCount?: string | Computed<string>;
  indexedFileCount?: string | Computed<string>;
  indexedItemCount?: string | Computed<string>;
  removedItemCount?: string | Computed<string>;
  skippedItemCount?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  totalBytes?: string | Computed<string>;
  totalBytesIndexed?: string | Computed<string>;
  totalFileCount?: string | Computed<string>;
}

export interface IndexedDataSourceConfig {
  indexingJobUuid: string | Computed<string>;
}

export interface IndexedDataSourceAttrs {
  indexedDataSources: IndexedDataSource_IndexedDataSources[];
  indexingJobUuid: string;
}

export const IndexedDataSource: DataSourceBinding<IndexedDataSourceConfig, IndexedDataSourceAttrs> = {
  wireType: "digitalocean_api_indexed_data_source",
  fields: {
    indexingJobUuid: "indexing_job_uuid",
  },
};
