// Code generated by `ubx sdk gen` from digitalocean_api_knowledge_base_data_source. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_AwsDataSource {
  bucketName?: string | Computed<string>;
  itemPath?: string | Computed<string>;
  region?: string | Computed<string>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_ChunkingOptions {
  childChunkSize?: number | Computed<number>;
  maxChunkSize?: number | Computed<number>;
  parentChunkSize?: number | Computed<number>;
  semanticThreshold?: number | Computed<number>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_DropboxDataSource {
  folder?: string | Computed<string>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_FileUploadDataSource {
  originalFileName?: string | Computed<string>;
  sizeInBytes?: string | Computed<string>;
  storedObjectKey?: string | Computed<string>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_GoogleDriveDataSource {
  folderId?: string | Computed<string>;
  folderName?: string | Computed<string>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_LastDatasourceIndexingJob {
  completedAt?: string | Computed<string>;
  dataSourceUuid?: string | Computed<string>;
  errorDetails?: string | Computed<string>;
  errorMsg?: string | Computed<string>;
  failedItemCount?: string | Computed<string>;
  indexedFileCount?: string | Computed<string>;
  indexedItemCount?: string | Computed<string>;
  removedItemCount?: string | Computed<string>;
  skippedItemCount?: string | Computed<string>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  totalBytes?: string | Computed<string>;
  totalBytesIndexed?: string | Computed<string>;
  totalFileCount?: string | Computed<string>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources_WebCrawlerDataSource {
  baseUrl?: string | Computed<string>;
  crawlingOption?: string | Computed<string>;
  embedMedia?: boolean | Computed<boolean>;
  excludeTags?: string[] | Computed<string[]>;
}

export interface KnowledgeBaseDataSource_KnowledgeBaseDataSources {
  awsDataSource?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_AwsDataSource | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_AwsDataSource>;
  bucketName?: string | Computed<string>;
  chunkingAlgorithm?: string | Computed<string>;
  chunkingOptions?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_ChunkingOptions | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_ChunkingOptions>;
  createdAt?: string | Computed<string>;
  dropboxDataSource?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_DropboxDataSource | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_DropboxDataSource>;
  fileUploadDataSource?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_FileUploadDataSource | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_FileUploadDataSource>;
  googleDriveDataSource?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_GoogleDriveDataSource | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_GoogleDriveDataSource>;
  itemPath?: string | Computed<string>;
  lastDatasourceIndexingJob?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_LastDatasourceIndexingJob | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_LastDatasourceIndexingJob>;
  region?: string | Computed<string>;
  spacesDataSource?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_AwsDataSource | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_AwsDataSource>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
  webCrawlerDataSource?: KnowledgeBaseDataSource_KnowledgeBaseDataSources_WebCrawlerDataSource | Computed<KnowledgeBaseDataSource_KnowledgeBaseDataSources_WebCrawlerDataSource>;
}

export interface KnowledgeBaseDataSource_Links_Pages {
  /** First page */
  first?: string | Computed<string>;
  /** Last page */
  last?: string | Computed<string>;
  /** Next page */
  next?: string | Computed<string>;
  /** Previous page */
  previous?: string | Computed<string>;
}

export interface KnowledgeBaseDataSource_Links {
  /** Information about how to reach other pages */
  pages?: KnowledgeBaseDataSource_Links_Pages | Computed<KnowledgeBaseDataSource_Links_Pages>;
}

export interface KnowledgeBaseDataSource_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface KnowledgeBaseDataSourceConfig {
  knowledgeBaseUuid: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface KnowledgeBaseDataSourceAttrs {
  /** The data sources */
  knowledgeBaseDataSources: KnowledgeBaseDataSource_KnowledgeBaseDataSources[];
  knowledgeBaseUuid: string;
  /** Links to other pages */
  links: KnowledgeBaseDataSource_Links;
  /** Meta information about the data set */
  meta: KnowledgeBaseDataSource_Meta;
  page: number;
  perPage: number;
}

export const KnowledgeBaseDataSource: DataSourceBinding<KnowledgeBaseDataSourceConfig, KnowledgeBaseDataSourceAttrs> = {
  wireType: "digitalocean_api_knowledge_base_data_source",
  fields: {
    knowledgeBaseUuid: "knowledge_base_uuid",
    page: "page",
    perPage: "per_page",
  },
};
