// Code generated by `ubx sdk gen` from digitalocean_api_model_router. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ModelRouter_Links_Pages {
  /** First page */
  first?: string | Computed<string>;
  /** Last page */
  last?: string | Computed<string>;
  /** Next page */
  next?: string | Computed<string>;
  /** Previous page */
  previous?: string | Computed<string>;
}

export interface ModelRouter_Links {
  /** Information about how to reach other pages */
  pages?: ModelRouter_Links_Pages | Computed<ModelRouter_Links_Pages>;
}

export interface ModelRouter_Meta {
  /** The current page */
  page?: number | Computed<number>;
  /** Total number of pages */
  pages?: number | Computed<number>;
  /** Total amount of items over all pages */
  total?: number | Computed<number>;
}

export interface ModelRouter_ModelRouters_Config_Policies_CustomTask {
  description?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface ModelRouter_ModelRouters_Config_Policies_SelectionPolicy {
  prefer?: string | Computed<string>;
}

export interface ModelRouter_ModelRouters_Config_Policies {
  customTask?: ModelRouter_ModelRouters_Config_Policies_CustomTask | Computed<ModelRouter_ModelRouters_Config_Policies_CustomTask>;
  models?: string[] | Computed<string[]>;
  selectionPolicy?: ModelRouter_ModelRouters_Config_Policies_SelectionPolicy | Computed<ModelRouter_ModelRouters_Config_Policies_SelectionPolicy>;
  taskSlug?: string | Computed<string>;
}

export interface ModelRouter_ModelRouters_Config {
  fallbackModels?: string[] | Computed<string[]>;
  policies?: ModelRouter_ModelRouters_Config_Policies[] | Computed<ModelRouter_ModelRouters_Config_Policies[]>;
}

export interface ModelRouter_ModelRouters {
  config?: ModelRouter_ModelRouters_Config | Computed<ModelRouter_ModelRouters_Config>;
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  name?: string | Computed<string>;
  regions?: string[] | Computed<string[]>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface ModelRouterConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface ModelRouterAttrs {
  /** Links to other pages */
  links: ModelRouter_Links;
  /** Meta information about the data set */
  meta: ModelRouter_Meta;
  /** The model routers */
  modelRouters: ModelRouter_ModelRouters[];
  page: number;
  perPage: number;
}

export const ModelRouter: DataSourceBinding<ModelRouterConfig, ModelRouterAttrs> = {
  wireType: "digitalocean_api_model_router",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
