// Code generated by `ubx sdk gen` from digitalocean_alert. DO NOT EDIT.
package monitoring

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Alert_Alerts_Slack struct {
	Channel any
	Url     any
}

type Alert_Alerts struct {
	// An email to notify on an alert trigger.
	Email any
	// Slack integration details.
	Slack any
}

type Alert_Policy struct {
	Alerts      any
	Compare     any
	Description any
	Enabled     any
	Entities    any
	Tags        any
	Type        any
	Uuid        any
	Value       any
	Window      any
}

var Alert_Alerts_SlackFields = ubx.FieldMap{
	"Channel": ubx.FieldSpec{WireName: "channel"},
	"Url":     ubx.FieldSpec{WireName: "url"},
}

var Alert_AlertsFields = ubx.FieldMap{
	"Email": ubx.FieldSpec{WireName: "email"},
	"Slack": ubx.FieldSpec{
		WireName: "slack",
		Kind:     "list",
		Fields:   Alert_Alerts_SlackFields,
	},
}

type AlertConfig struct {
	Alerts      any
	Compare     any
	Description any
	Enabled     any
	Entities    any
	Tags        any
	Type        any
	Value       any
	Window      any
	// path parameter, not part of the API's own resource representation
	AlertUuid any
}

type AlertAttrs struct {
	Alerts      any
	Compare     any
	Description any
	Enabled     any
	Entities    any
	Policy      any
	Tags        any
	Type        any
	Value       any
	Window      any
	// path parameter, not part of the API's own resource representation
	AlertUuid any
}

var Alert = ubx.ResourceBinding{
	WireType: "digitalocean_alert",
	Fields: ubx.FieldMap{
		"Alerts": ubx.FieldSpec{
			WireName: "alerts",
			Kind:     "object",
			Fields:   Alert_AlertsFields,
		},
		"Compare":     ubx.FieldSpec{WireName: "compare"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"Enabled":     ubx.FieldSpec{WireName: "enabled"},
		"Entities":    ubx.FieldSpec{WireName: "entities"},
		"Tags":        ubx.FieldSpec{WireName: "tags"},
		"Type":        ubx.FieldSpec{WireName: "type"},
		"Value":       ubx.FieldSpec{WireName: "value"},
		"Window":      ubx.FieldSpec{WireName: "window"},
		"AlertUuid":   ubx.FieldSpec{WireName: "alert_uuid"},
	},
}
