// Code generated by `ubx sdk gen` from digitalocean_sink. DO NOT EDIT.
package monitoring

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Sink_Resources struct {
	Name any
	Urn  any
}

type Sink_Sink_Destination_Config_Credentials struct {
	Password any
	Username any
}

type Sink_Sink_Destination_Config struct {
	// Name of a managed OpenSearch cluster.
	ClusterName any
	// A unique identifier for a managed OpenSearch cluster.
	ClusterUuid any
	// Credentials for an OpenSearch cluster user. Optional if `cluster_uuid` is passed.
	Credentials any
	// host of the OpenSearch cluster
	Endpoint any
	// A unique identifier for a configuration.
	Id any
	// OpenSearch index to send logs to.
	IndexName any
	// Number of days to retain logs in OpenSearch (default: 14)
	RetentionDays any
}

type Sink_Sink_Destination struct {
	Config any
	// A unique identifier for a destination.
	Id any
	// destination name
	Name any
	// The destination type. `opensearch_dbaas` for a DigitalOcean managed OpenSearch cluster or `opensearch_ext` for an externally managed one.
	Type any
}

type Sink_Sink struct {
	Destination any
	// List of resources identified by their URNs.
	Resources any
}

var Sink_ResourcesFields = ubx.FieldMap{
	"Name": ubx.FieldSpec{WireName: "name"},
	"Urn":  ubx.FieldSpec{WireName: "urn"},
}

type SinkConfig struct {
	// A unique identifier for an already-existing destination.
	DestinationUuid any
	// List of resources identified by their URNs.
	Resources any
	// path parameter, not part of the API's own resource representation
	SinkUuid any
}

type SinkAttrs struct {
	// A unique identifier for an already-existing destination.
	DestinationUuid any
	// List of resources identified by their URNs.
	Resources any
	// The sink's own real, current representation. (AI-inferred)
	Sink any
	// path parameter, not part of the API's own resource representation
	SinkUuid any
}

var Sink = ubx.ResourceBinding{
	WireType: "digitalocean_sink",
	Fields: ubx.FieldMap{
		"DestinationUuid": ubx.FieldSpec{WireName: "destination_uuid"},
		"Resources": ubx.FieldSpec{
			WireName: "resources",
			Kind:     "list",
			Fields:   Sink_ResourcesFields,
		},
		"SinkUuid": ubx.FieldSpec{WireName: "sink_uuid"},
	},
}
