# Code generated by `ubx sdk gen` from digitalocean_api_get_knowledge_base_indexing_job_output. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApiGetKnowledgeBaseIndexingJobOutput_Job_DataSourceJobs:
    completed_at: Any = None
    data_source_uuid: Any = None
    error_details: Any = None
    error_msg: Any = None
    failed_item_count: Any = None
    indexed_file_count: Any = None
    indexed_item_count: Any = None
    removed_item_count: Any = None
    skipped_item_count: Any = None
    started_at: Any = None
    status: Any = None
    total_bytes: Any = None
    total_bytes_indexed: Any = None
    total_file_count: Any = None

@dataclasses.dataclass
class ApiGetKnowledgeBaseIndexingJobOutput_Job:
    # Number of datasources indexed completed
    completed_datasources: Any = None
    # Creation date / time
    created_at: Any = None
    # Details on Data Sources included in the Indexing Job
    data_source_jobs: Any = None
    data_source_uuids: Any = None
    finished_at: Any = None
    # Boolean value to determine if the indexing job details are available
    is_report_available: Any = None
    # Knowledge base id
    knowledge_base_uuid: Any = None
    phase: Any = None
    started_at: Any = None
    status: Any = None
    # Number of tokens [This field is deprecated]
    tokens: Any = None
    # Number of datasources being indexed
    total_datasources: Any = None
    # Total Tokens Consumed By the Indexing Job
    total_tokens: Any = None
    # Last modified
    updated_at: Any = None
    # Unique id
    uuid: Any = None

@dataclasses.dataclass
class ApiGetKnowledgeBaseIndexingJobOutputConfig:
    # List of data source ids to index, if none are provided, all data sources will be indexed
    data_source_uuids: Any = None
    # Knowledge base id
    knowledge_base_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    uuid: Any = None

@dataclasses.dataclass
class ApiGetKnowledgeBaseIndexingJobOutputAttrs:
    # List of data source ids to index, if none are provided, all data sources will be indexed
    data_source_uuids: Any = None
    # IndexingJob description
    job: Any = None
    # Knowledge base id
    knowledge_base_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    uuid: Any = None

ApiGetKnowledgeBaseIndexingJobOutput = ubx.ResourceBinding(
    wire_type="digitalocean_api_get_knowledge_base_indexing_job_output",
    fields={
        "data_source_uuids": ubx.FieldSpec(wire_name="data_source_uuids"),
        "knowledge_base_uuid": ubx.FieldSpec(wire_name="knowledge_base_uuid"),
        "uuid": ubx.FieldSpec(wire_name="uuid"),
    },
)
