# Code generated by `ubx sdk gen` from digitalocean_api_get_anthropic_apikey_output. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApiGetAnthropicApikeyOutput_ApiKeyInfo:
    # Key creation date
    created_at: Any = None
    # Created by user id from DO
    created_by: Any = None
    # Key deleted date
    deleted_at: Any = None
    # Name
    name: Any = None
    # Key last updated date
    updated_at: Any = None
    # Uuid
    uuid: Any = None

@dataclasses.dataclass
class ApiGetAnthropicApikeyOutputConfig:
    # Anthropic API key
    api_key: Any = None
    # Name of the key
    name: Any = None
    # path parameter, not part of the API's own resource representation
    api_key_uuid: Any = None

@dataclasses.dataclass
class ApiGetAnthropicApikeyOutputAttrs:
    # Anthropic API key
    api_key: Any = None
    # Anthropic API Key Info
    api_key_info: Any = None
    # Name of the key
    name: Any = None
    # path parameter, not part of the API's own resource representation
    api_key_uuid: Any = None

ApiGetAnthropicApikeyOutput = ubx.ResourceBinding(
    wire_type="digitalocean_api_get_anthropic_apikey_output",
    fields={
        "api_key": ubx.FieldSpec(wire_name="api_key"),
        "name": ubx.FieldSpec(wire_name="name"),
        "api_key_uuid": ubx.FieldSpec(wire_name="api_key_uuid"),
    },
)
