# Code generated by `ubx sdk gen` from digitalocean_api_get_model_router_output. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApiGetModelRouterOutput_ModelRouter_Config_Policies_CustomTask:
    description: Any = None
    name: Any = None

@dataclasses.dataclass
class ApiGetModelRouterOutput_ModelRouter_Config_Policies_SelectionPolicy:
    prefer: Any = None

@dataclasses.dataclass
class ApiGetModelRouterOutput_ModelRouter_Config_Policies:
    custom_task: Any = None
    models: Any = None
    selection_policy: Any = None
    task_slug: Any = None

@dataclasses.dataclass
class ApiGetModelRouterOutput_ModelRouter_Config:
    # Router-level fallback models
    fallback_models: Any = None
    # Task routing policies
    policies: Any = None

@dataclasses.dataclass
class ApiGetModelRouterOutput_ModelRouter:
    config: Any = None
    # Creation date / time
    created_at: Any = None
    # Description
    description: Any = None
    # Name of the model router
    name: Any = None
    # Target regions for the router
    regions: Any = None
    # Last modified
    updated_at: Any = None
    # Unique id
    uuid: Any = None

_ApiGetModelRouterOutput_ModelRouter_Config_Policies_CustomTaskFields = {
    "description": ubx.FieldSpec(wire_name="description"),
    "name": ubx.FieldSpec(wire_name="name"),
}

_ApiGetModelRouterOutput_ModelRouter_Config_Policies_SelectionPolicyFields = {
    "prefer": ubx.FieldSpec(wire_name="prefer"),
}

_ApiGetModelRouterOutput_ModelRouter_Config_PoliciesFields = {
    "custom_task": ubx.FieldSpec(
        wire_name="custom_task",
        kind="object",
        fields=_ApiGetModelRouterOutput_ModelRouter_Config_Policies_CustomTaskFields,
    ),
    "models": ubx.FieldSpec(wire_name="models"),
    "selection_policy": ubx.FieldSpec(
        wire_name="selection_policy",
        kind="object",
        fields=_ApiGetModelRouterOutput_ModelRouter_Config_Policies_SelectionPolicyFields,
    ),
    "task_slug": ubx.FieldSpec(wire_name="task_slug"),
}

@dataclasses.dataclass
class ApiGetModelRouterOutputConfig:
    # Model router description
    description: Any = None
    # At least one fallback model is required; order defines failover priority
    fallback_models: Any = None
    # Model router name: lowercase, at most 255 characters, only a-z, 0-9, and hyphens
    name: Any = None
    # Router policies
    policies: Any = None
    # DEPRECATED: this field does not affect deployment and model routers are always deployed to all regions. Must be omitted or set to ["all"].
    regions: Any = None
    # path parameter, not part of the API's own resource representation
    uuid: Any = None

@dataclasses.dataclass
class ApiGetModelRouterOutputAttrs:
    # Model router description
    description: Any = None
    # At least one fallback model is required; order defines failover priority
    fallback_models: Any = None
    # Model router
    model_router: Any = None
    # Model router name: lowercase, at most 255 characters, only a-z, 0-9, and hyphens
    name: Any = None
    # Router policies
    policies: Any = None
    # DEPRECATED: this field does not affect deployment and model routers are always deployed to all regions. Must be omitted or set to ["all"].
    regions: Any = None
    # path parameter, not part of the API's own resource representation
    uuid: Any = None

ApiGetModelRouterOutput = ubx.ResourceBinding(
    wire_type="digitalocean_api_get_model_router_output",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "fallback_models": ubx.FieldSpec(wire_name="fallback_models"),
        "name": ubx.FieldSpec(wire_name="name"),
        "policies": ubx.FieldSpec(
            wire_name="policies",
            kind="list",
            fields=_ApiGetModelRouterOutput_ModelRouter_Config_PoliciesFields,
        ),
        "regions": ubx.FieldSpec(wire_name="regions"),
        "uuid": ubx.FieldSpec(wire_name="uuid"),
    },
)
