# Code generated by `ubx sdk gen` from digitalocean_token. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Token_Links:
    pages: Any = None

@dataclasses.dataclass
class Token_Meta:
    total: Any = None

@dataclasses.dataclass
class Token_Tokens:
    created_at: Any = None
    id: Any = None
    is_managed: Any = None
    name: Any = None
    value: Any = None

@dataclasses.dataclass
class TokenConfig:
    dedicated_inference_id: Any = None
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class TokenAttrs:
    dedicated_inference_id: Any = None
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None
    tokens: Any = None

Token = ubx.DataSourceBinding(
    wire_type="digitalocean_token",
    fields={
        "dedicated_inference_id": ubx.FieldSpec(wire_name="dedicated_inference_id"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
