// Code generated by `ubx sdk gen` from digitalocean_key. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface KeyConfig {
  accessKey: string | Computed<string>;
}

export interface KeyAttrs {
  accessKey: string;
}

export const Key: DataSourceBinding<KeyConfig, KeyAttrs> = {
  wireType: "digitalocean_key",
  fields: {
    accessKey: "access_key",
  },
};
