// Code generated by `ubx sdk gen` from digitalocean_backup. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Backup_Backups {
  createdAt?: string | Computed<string>;
  incremental?: boolean | Computed<boolean>;
  sizeGigabytes?: number | Computed<number>;
}

export interface Backup_ScheduledBackupTime {
  /** The hour of the day when the backup is scheduled (in UTC). */
  backupHour?: number | Computed<number>;
  /** The frequency, in hours, at which backups are taken. */
  backupIntervalHours?: number | Computed<number>;
  /** The minute of the hour when the backup is scheduled. */
  backupMinute?: number | Computed<number>;
}

export interface BackupConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface BackupAttrs {
  /** If a backup is currently in progress, this attribute shows the percentage of completion. If no backup is in progress, this attribute will be hidden. */
  backupProgress: string;
  backups: Backup_Backups[];
  databaseClusterUuid: string;
  scheduledBackupTime: Backup_ScheduledBackupTime;
}

export const Backup: DataSourceBinding<BackupConfig, BackupAttrs> = {
  wireType: "digitalocean_backup",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
