// Code generated by `ubx sdk gen` from digitalocean_do_setting. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DoSetting_DoSettings {
  /** An array of custom CNAMEs for the database cluster. Each CNAME must be a valid RFC 1123 hostname (e.g., "db.example.com"). Maximum of 16 CNAMEs allowed, each up to 253 characters. */
  serviceCnames?: string[] | Computed<string[]>;
}

export interface DoSettingConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface DoSettingAttrs {
  databaseClusterUuid: string;
  /** DigitalOcean-specific settings for the database cluster. */
  doSettings: DoSetting_DoSettings;
}

export const DoSetting: DataSourceBinding<DoSettingConfig, DoSettingAttrs> = {
  wireType: "digitalocean_do_setting",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
