// Code generated by `ubx sdk gen` from digitalocean_eviction_policy. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface EvictionPolicyConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface EvictionPolicyAttrs {
  databaseClusterUuid: string;
  /** A string specifying the desired eviction policy for a Caching or Valkey cluster. - `noeviction`: Don't evict any data, returns error when memory limit is reached. - `allkeys_lru:` Evict any key, least recently used (LRU) first. - `allkeys_random`: Evict keys in a random order. - `volatile_lru`: Evict keys with expiration only, least recently used (LRU) first. - `volatile_random`: Evict keys with expiration only in a random order. - `volatile_ttl`: Evict keys with expiration only, shortest time-to-live (TTL) first. */
  evictionPolicy: string;
}

export const EvictionPolicy: DataSourceBinding<EvictionPolicyConfig, EvictionPolicyAttrs> = {
  wireType: "digitalocean_eviction_policy",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
