// Code generated by `ubx sdk gen` from digitalocean_kafka_topic. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface KafkaTopic_Topics {
  name?: string | Computed<string>;
  partitionCount?: number | Computed<number>;
  replicationFactor?: number | Computed<number>;
  state?: string | Computed<string>;
}

export interface KafkaTopicConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface KafkaTopicAttrs {
  databaseClusterUuid: string;
  topics: KafkaTopic_Topics[];
}

export const KafkaTopic: DataSourceBinding<KafkaTopicConfig, KafkaTopicAttrs> = {
  wireType: "digitalocean_kafka_topic",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
