# Code generated by `ubx sdk gen` from digitalocean_batch. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Batch_Errors:
    code: Any = None
    line: Any = None
    message: Any = None

@dataclasses.dataclass
class Batch_RequestCounts:
    completed: Any = None
    failed: Any = None
    total: Any = None

@dataclasses.dataclass
class BatchConfig:
    # Time window in which the job must complete. Jobs that do not finish in time transition to `expired`.
    completion_window: Any = None
    # Inference endpoint each request is dispatched to. **Required when `provider` is `openai` and must match the `url` on every JSONL line. Must be omitted when `provider` is `anthropic`.**
    endpoint: Any = None
    # The `file_id` returned by `POST /v1/batches/files`.
    file_id: Any = None
    # Optional string-valued metadata to attach to the job.
    metadata: Any = None
    # The inference provider whose JSONL schema the input file conforms to. `openai` follows the OpenAI Batch API input schema (`custom_id`, `method`, `url`, `body`); `anthropic` follows the Anthropic Message Batches JSONL conventions.
    provider: Any = None
    # Client-supplied idempotency key. Retries with the same value return the existing job instead of creating a duplicate.
    request_id: Any = None

@dataclasses.dataclass
class BatchAttrs:
    # Unique identifier for the batch job.
    batch_id: Any = None
    cancelled_at: Any = None
    completed_at: Any = None
    # Time window in which the job must complete. Jobs that do not finish in time transition to `expired`.
    completion_window: Any = None
    created_at: Any = None
    # Inference endpoint each request is dispatched to. **Required when `provider` is `openai` and must match the `url` on every JSONL line. Must be omitted when `provider` is `anthropic`.**
    endpoint: Any = None
    # Error sidecar file. Null when no errors were produced.
    error_file_id: Any = None
    # Top-level errors that prevented the batch from completing.
    errors: Any = None
    # Derived from `created_at` plus `completion_window`.
    expires_at: Any = None
    failed_at: Any = None
    # The `file_id` returned by `POST /v1/batches/files`.
    file_id: Any = None
    finalizing_at: Any = None
    in_progress_at: Any = None
    # The uploaded JSONL input file.
    input_file_id: Any = None
    # Optional string-valued metadata to attach to the job.
    metadata: Any = None
    # Output JSONL file. Populated once the job completes.
    output_file_id: Any = None
    # The inference provider whose JSONL schema the input file conforms to. `openai` follows the OpenAI Batch API input schema (`custom_id`, `method`, `url`, `body`); `anthropic` follows the Anthropic Message Batches JSONL conventions.
    provider: Any = None
    # Aggregate request counts.
    request_counts: Any = None
    # Client-supplied idempotency key. Retries with the same value return the existing job instead of creating a duplicate.
    request_id: Any = None
    # Lifecycle status. Terminal states: `completed`, `failed`, `expired`, `cancelled`.
    status: Any = None

Batch = ubx.ResourceBinding(
    wire_type="digitalocean_batch",
    fields={
        "completion_window": ubx.FieldSpec(wire_name="completion_window"),
        "endpoint": ubx.FieldSpec(wire_name="endpoint"),
        "file_id": ubx.FieldSpec(wire_name="file_id"),
        "metadata": ubx.FieldSpec(wire_name="metadata"),
        "provider": ubx.FieldSpec(wire_name="provider"),
        "request_id": ubx.FieldSpec(wire_name="request_id"),
    },
)
