// Code generated by `ubx sdk gen` from digitalocean_saa. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Saa_Resource_Metadata {
  name?: string | Computed<string>;
  value?: unknown | Computed<unknown>;
}

export interface Saa_Resource {
  /** The name of the application associated with the resource. */
  appName?: string | Computed<string>;
  /** The slug identifier for the application associated with the resource. */
  appSlug: string | Computed<string>;
  /** Indicates if the resource has configuration values set by the vendor. */
  hasConfig: boolean | Computed<boolean>;
  /** A message related to the resource, if applicable. */
  message?: string | Computed<string>;
  /** Metadata associated with the resource, set by the user. */
  metadata?: Saa_Resource_Metadata[] | Computed<Saa_Resource_Metadata[]>;
  /** The name of the addon resource. */
  name: string | Computed<string>;
  /** The name of the plan associated with the resource. */
  planName?: string | Computed<string>;
  /** The price of the plan per month in US dollars. */
  planPricePerMonth?: number | Computed<number>;
  /** The slug identifier for the plan associated with the resource. */
  planSlug: string | Computed<string>;
  /** The Single Sign-On URL for the resource, if applicable. */
  ssoUrl?: string | Computed<string>;
  /** The state the resource is currently in. */
  state: string | Computed<string>;
  /** The unique identifier for the addon resource. */
  uuid: string | Computed<string>;
}

export interface SaaConfig {
  /** path parameter, not part of the API's own resource representation */
  resourceUuid: string | Computed<string>;
}

export interface SaaAttrs {
  resource: Saa_Resource;
  /** path parameter, not part of the API's own resource representation */
  resourceUuid: string;
}

export const Saa: ResourceBinding<SaaConfig, SaaAttrs> = {
  wireType: "digitalocean_saa",
  fields: {
    resourceUuid: "resource_uuid",
  },
};
