// Code generated by `ubx sdk gen` from digitalocean_model. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Model_Data {
  created?: number | Computed<number>;
  id?: string | Computed<string>;
  object?: string | Computed<string>;
  ownedBy?: string | Computed<string>;
}

export interface ModelConfig {
}

export interface ModelAttrs {
  /** The list of available models. */
  data: Model_Data[];
  /** The object type, which is always "list". */
  object: string;
}

export const Model: DataSourceBinding<ModelConfig, ModelAttrs> = {
  wireType: "digitalocean_model",
  fields: {
  },
};
