# Code generated by `ubx sdk gen` from digitalocean_default. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Default_Project:
    created_at: Any = None
    description: Any = None
    environment: Any = None
    id: Any = None
    is_default: Any = None
    name: Any = None
    owner_id: Any = None
    owner_uuid: Any = None
    purpose: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class DefaultConfig:
    pass

@dataclasses.dataclass
class DefaultAttrs:
    project: Any = None

Default = ubx.DataSourceBinding(
    wire_type="digitalocean_default",
    fields={
    },
)
