# Code generated by `ubx sdk gen` from digitalocean_vpc. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Vpc_Vpc:
    created_at: Any = None
    default: Any = None
    description: Any = None
    id: Any = None
    ip_range: Any = None
    name: Any = None
    region: Any = None
    urn: Any = None

@dataclasses.dataclass
class VpcConfig:
    # path parameter, not part of the API's own resource representation
    vpc_id: Any = None

@dataclasses.dataclass
class VpcAttrs:
    vpc: Any = None
    # path parameter, not part of the API's own resource representation
    vpc_id: Any = None

Vpc = ubx.ResourceBinding(
    wire_type="digitalocean_vpc",
    fields={
        "vpc_id": ubx.FieldSpec(wire_name="vpc_id"),
    },
)
