// Code generated by `ubx sdk gen` from digitalocean_associated_resource_status. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ResourceStatus_Droplet {
  /** A time value given in ISO8601 combined date and time format indicating when the resource was destroyed if the request was successful. */
  destroyedAt?: string | Computed<string>;
  /** A string indicating that the resource was not successfully destroyed and providing additional information. */
  errorMessage?: string | Computed<string>;
  /** The unique identifier for the resource scheduled for deletion. */
  id?: string | Computed<string>;
  /** The name of the resource scheduled for deletion. */
  name?: string | Computed<string>;
}

export interface ResourceStatus_Resources {
  floatingIps?: ResourceStatus_Droplet[] | Computed<ResourceStatus_Droplet[]>;
  reservedIps?: ResourceStatus_Droplet[] | Computed<ResourceStatus_Droplet[]>;
  snapshots?: ResourceStatus_Droplet[] | Computed<ResourceStatus_Droplet[]>;
  volumeSnapshots?: ResourceStatus_Droplet[] | Computed<ResourceStatus_Droplet[]>;
  volumes?: ResourceStatus_Droplet[] | Computed<ResourceStatus_Droplet[]>;
}

export interface ResourceStatusConfig {
  dropletId: number | Computed<number>;
}

export interface ResourceStatusAttrs {
  /** A time value given in ISO8601 combined date and time format indicating when the requested action was completed. */
  completedAt: string;
  /** An object containing information about a resource scheduled for deletion. */
  droplet: ResourceStatus_Droplet;
  dropletId: number;
  /** A count of the associated resources that failed to be destroyed, if any. */
  failures: number;
  /** An object containing additional information about resource related to a Droplet requested to be destroyed. */
  resources: ResourceStatus_Resources;
}

export const ResourceStatus: DataSourceBinding<ResourceStatusConfig, ResourceStatusAttrs> = {
  wireType: "digitalocean_associated_resource_status",
  fields: {
    dropletId: "droplet_id",
  },
};
