// Code generated by `ubx sdk gen` from digitalocean_vectordb_backup. DO NOT EDIT.
package vectordatabases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VectordbBackup_Backups struct {
	BackupId    any
	CompletedAt any
	StartedAt   any
	Status      any
}

type VectordbBackupConfig struct {
	Id any
}

type VectordbBackupAttrs struct {
	// List of available backups.
	Backups any
	Id      any
}

var VectordbBackup = ubx.DataSourceBinding{
	WireType: "digitalocean_vectordb_backup",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
