// Code generated by `ubx sdk gen` from digitalocean_endpoint. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EndpointConfig {
  /** The ID of a DigitalOcean managed TLS certificate used for SSL when a custom subdomain is provided. */
  certificateId?: string | Computed<string>;
  /** The fully qualified domain name (FQDN) of the custom subdomain used with the CDN endpoint. */
  customDomain?: string | Computed<string>;
  /** The fully qualified domain name (FQDN) from which the CDN-backed content is served. */
  endpoint?: string | Computed<string>;
  /** The fully qualified domain name (FQDN) for the origin server which provides the content for the CDN. This is currently restricted to a Space. */
  origin: string | Computed<string>;
  /** The amount of time the content is cached by the CDN's edge servers in seconds. TTL must be one of 60, 600, 3600, 86400, or 604800. Defaults to 3600 (one hour) when excluded. */
  ttl?: number | Computed<number>;
  /** path parameter, not part of the API's own resource representation */
  cdnId: string | Computed<string>;
}

export interface EndpointAttrs {
  /** The ID of a DigitalOcean managed TLS certificate used for SSL when a custom subdomain is provided. */
  certificateId: string;
  /** A time value given in ISO8601 combined date and time format that represents when the CDN endpoint was created. */
  createdAt: string;
  /** The fully qualified domain name (FQDN) of the custom subdomain used with the CDN endpoint. */
  customDomain: string;
  /** The fully qualified domain name (FQDN) from which the CDN-backed content is served. */
  endpoint: string;
  /** A unique ID that can be used to identify and reference a CDN endpoint. */
  id: string;
  /** The fully qualified domain name (FQDN) for the origin server which provides the content for the CDN. This is currently restricted to a Space. */
  origin: string;
  /** The amount of time the content is cached by the CDN's edge servers in seconds. TTL must be one of 60, 600, 3600, 86400, or 604800. Defaults to 3600 (one hour) when excluded. */
  ttl: number;
  /** path parameter, not part of the API's own resource representation */
  cdnId: string;
}

export const Endpoint: ResourceBinding<EndpointConfig, EndpointAttrs> = {
  wireType: "digitalocean_endpoint",
  fields: {
    certificateId: "certificate_id",
    customDomain: "custom_domain",
    endpoint: "endpoint",
    origin: "origin",
    ttl: "ttl",
    cdnId: "cdn_id",
  },
};
