// Code generated by `ubx sdk gen` from digitalocean_user. DO NOT EDIT.
package user

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type User_User_MysqlSettings struct {
	// A string specifying the authentication method to be used for connections to the MySQL user account. The valid values are `mysql_native_password` or `caching_sha2_password`. If excluded when creating a new user, the default for the version of MySQL in use will be used. As of MySQL 8.0, the default is `caching_sha2_password`.
	AuthPlugin any
}

type User_User_Settings_Acl struct {
	Id any
	Permission any
	Topic any
}

type User_User_Settings_MongoUserSettings struct {
	// A list of databases to which the user should have access. When the database is set to `admin`, the user will have access to all databases based on the user's role i.e. a user with the role `readOnly` assigned to the `admin` database will have read access to all databases.
	Databases any
	// The role to assign to the user with each role mapping to a MongoDB built-in role. `readOnly` maps to a [read](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-read) role. `readWrite` maps to a [readWrite](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-readWrite) role. `dbAdmin` maps to a [dbAdmin](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-dbAdmin) role.
	Role any
}

type User_User_Settings_OpensearchAcl struct {
	Index any
	Permission any
}

type User_User_Settings struct {
	// ACLs (Access Control Lists) specifying permissions on topics within a Kafka cluster.
	Acl any
	// MongoDB-specific settings for the user. This option is not currently supported for other database engines.
	MongoUserSettings any
	// ACLs (Access Control Lists) specifying permissions on index within a OpenSearch cluster.
	OpensearchAcl any
	// For PostgreSQL clusters, set to `true` to grant the user replication privileges. When omitted on create or update, the value defaults to `false` and replication privileges are not granted. This option is not currently supported for other database engines.
	PgAllowReplication any
}

type User_User struct {
	// Access certificate for TLS client authentication. (Kafka only)
	AccessCert any
	// Access key for TLS client authentication. (Kafka only)
	AccessKey any
	MysqlSettings any
	// The name of a database user.
	Name any
	// A randomly generated password for the database user.<br>Requires `database:view_credentials` scope.
	Password any
	// A string representing the database user's role. The value will be either "primary" or "normal".
	Role any
	Settings any
}

type UserConfig struct {
	// path parameter, not part of the API's own resource representation
	DatabaseClusterUuid any
	// path parameter, not part of the API's own resource representation
	Username any
}

type UserAttrs struct {
	User any
	// path parameter, not part of the API's own resource representation
	DatabaseClusterUuid any
	// path parameter, not part of the API's own resource representation
	Username any
}

var User = ubx.ResourceBinding{
	WireType: "digitalocean_user",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
		"Username": ubx.FieldSpec{WireName: "username"},
	},
}
