# Code generated by `ubx sdk gen` from digitalocean_docker_credentials. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DockerCredentials_Auths_RegistryDigitaloceanCom:
    # A base64 encoded string containing credentials for the container registry.
    auth: Any = None

@dataclasses.dataclass
class DockerCredentials_Auths:
    registry_digitalocean_com: Any = None

@dataclasses.dataclass
class DockerCredentialsConfig:
    registry_name: Any = None

@dataclasses.dataclass
class DockerCredentialsAttrs:
    auths: Any = None
    registry_name: Any = None

DockerCredentials = ubx.DataSourceBinding(
    wire_type="digitalocean_docker_credentials",
    fields={
        "registry_name": ubx.FieldSpec(wire_name="registry_name"),
    },
)
