// Code generated by `ubx sdk gen` from digitalocean_cdn. DO NOT EDIT.
package cdn

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CdnConfig struct {
	Page any
	PerPage any
}

type CdnAttrs struct {
	Page any
	PerPage any
}

var Cdn = ubx.DataSourceBinding{
	WireType: "digitalocean_cdn",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
