# Code generated by `ubx sdk gen` from digitalocean_api_get_agent_output. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GetAgentOutput_Agent_AnthropicApiKey:
    # Key creation date
    created_at: Any = None
    # Created by user id from DO
    created_by: Any = None
    # Key deleted date
    deleted_at: Any = None
    # Name
    name: Any = None
    # Key last updated date
    updated_at: Any = None
    # Uuid
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ApiKeyInfos:
    created_at: Any = None
    created_by: Any = None
    deleted_at: Any = None
    name: Any = None
    secret_key: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ApiKeys:
    api_key: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Chatbot:
    allowed_domains: Any = None
    button_background_color: Any = None
    logo: Any = None
    # Name of chatbot
    name: Any = None
    primary_color: Any = None
    secondary_color: Any = None
    starting_message: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ChatbotIdentifiers:
    agent_chatbot_identifier: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ChildAgents:
    pass

@dataclasses.dataclass
class GetAgentOutput_Agent_Deployment:
    # Creation date / time
    created_at: Any = None
    # Name
    name: Any = None
    status: Any = None
    # Last modified
    updated_at: Any = None
    # Access your deployed agent here
    url: Any = None
    # Unique id
    uuid: Any = None
    # - VISIBILITY_UNKNOWN: The status of the deployment is unknown - VISIBILITY_DISABLED: The deployment is disabled and will no longer service requests - VISIBILITY_PLAYGROUND: Deprecated: No longer a valid state - VISIBILITY_PUBLIC: The deployment is public and will service requests from the public internet - VISIBILITY_PRIVATE: The deployment is private and will only service requests from other agents, or through API keys
    visibility: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Functions:
    api_key: Any = None
    created_at: Any = None
    created_by: Any = None
    description: Any = None
    faas_name: Any = None
    faas_namespace: Any = None
    input_schema: Any = None
    name: Any = None
    output_schema: Any = None
    updated_at: Any = None
    url: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Guardrails:
    agent_uuid: Any = None
    created_at: Any = None
    default_response: Any = None
    description: Any = None
    guardrail_uuid: Any = None
    is_attached: Any = None
    is_default: Any = None
    metadata: Any = None
    name: Any = None
    priority: Any = None
    type: Any = None
    updated_at: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_KnowledgeBases_LastIndexingJob_DataSourceJobs:
    completed_at: Any = None
    data_source_uuid: Any = None
    error_details: Any = None
    error_msg: Any = None
    failed_item_count: Any = None
    indexed_file_count: Any = None
    indexed_item_count: Any = None
    removed_item_count: Any = None
    skipped_item_count: Any = None
    started_at: Any = None
    status: Any = None
    total_bytes: Any = None
    total_bytes_indexed: Any = None
    total_file_count: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_KnowledgeBases_LastIndexingJob:
    completed_datasources: Any = None
    created_at: Any = None
    data_source_jobs: Any = None
    data_source_uuids: Any = None
    finished_at: Any = None
    is_report_available: Any = None
    knowledge_base_uuid: Any = None
    phase: Any = None
    started_at: Any = None
    status: Any = None
    tokens: Any = None
    total_datasources: Any = None
    total_tokens: Any = None
    updated_at: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_KnowledgeBases_RerankingConfig:
    enabled: Any = None
    model: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_KnowledgeBases:
    added_to_agent_at: Any = None
    created_at: Any = None
    database_id: Any = None
    embedding_model_uuid: Any = None
    is_public: Any = None
    last_indexing_job: Any = None
    name: Any = None
    project_id: Any = None
    region: Any = None
    reranking_config: Any = None
    tags: Any = None
    updated_at: Any = None
    user_id: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_LoggingConfig:
    # Galileo project identifier
    galileo_project_id: Any = None
    # Name of the Galileo project
    galileo_project_name: Any = None
    # Whether insights are enabled
    insights_enabled: Any = None
    # Timestamp when insights were enabled
    insights_enabled_at: Any = None
    # Identifier for the log stream
    log_stream_id: Any = None
    # Name of the log stream
    log_stream_name: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_McpServers:
    allowed_tools: Any = None
    authorization: Any = None
    headers: Any = None
    server_label: Any = None
    server_url: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Model_Agreement:
    description: Any = None
    name: Any = None
    url: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Model_Endpoints:
    capabilities: Any = None
    endpoint: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Model_Modalities:
    input: Any = None
    output: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Model_Settings:
    default_string: Any = None
    default_value: Any = None
    max: Any = None
    min: Any = None
    name: Any = None
    options: Any = None
    step: Any = None
    type: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Model_Version:
    # Major version number
    major: Any = None
    # Minor version number
    minor: Any = None
    # Patch version number
    patch: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Model:
    # Agreement Description
    agreement: Any = None
    # Benchmark scores for this model, stored as arbitrary JSON
    benchmark_score: Any = None
    # High-level capabilities (e.g. tool_calling, vision, streaming)
    capabilities: Any = None
    # Context window size in tokens
    context_window: Any = None
    # Creation date / time
    created_at: Any = None
    # Available endpoints and their capabilities
    endpoints: Any = None
    # Internally used name
    inference_name: Any = None
    # Internally used version
    inference_version: Any = None
    # True if it is a foundational model provided by do
    is_foundational: Any = None
    # Default chunking size limit to show in UI
    kb_default_chunk_size: Any = None
    # Maximum chunk size limit of model
    kb_max_chunk_size: Any = None
    # Minimum chunking size token limits if model supports KNOWLEDGEBASE usecase
    kb_min_chunk_size: Any = None
    # Lifecycle status of the model (internal, public-preview, active, deprecated, end_of_life)
    lifecycle_status: Any = None
    # Additional meta data
    metadata: Any = None
    # Input/output modalities
    modalities: Any = None
    # Name of the model
    name: Any = None
    # Parameter count in billions
    parameter_count: Any = None
    # Unique id of the model, this model is based on
    parent_uuid: Any = None
    provider: Any = None
    # Available reasoning efforts for this model
    reasoning_efforts: Any = None
    # Playground settings derived from model metadata
    settings: Any = None
    # Whether this model supports extended thinking (Anthropic models)
    thinking: Any = None
    # Model type (chat, embedding, image, reasoning, coding)
    type: Any = None
    # Last modified
    updated_at: Any = None
    # Model has been fully uploaded
    upload_complete: Any = None
    # Download url
    url: Any = None
    # Usecases of the model
    usecases: Any = None
    # Unique id
    uuid: Any = None
    # Version Information about a Model
    version: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ModelProviderKey:
    # API key ID
    api_key_uuid: Any = None
    # Key creation date
    created_at: Any = None
    # Created by user id from DO
    created_by: Any = None
    # Key deleted date
    deleted_at: Any = None
    # Models supported by the openAI api key
    models: Any = None
    # Name of the key
    name: Any = None
    provider: Any = None
    # Key last updated date
    updated_at: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ModelRouter_Config_Policies_CustomTask:
    description: Any = None
    name: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ModelRouter_Config_Policies_SelectionPolicy:
    prefer: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ModelRouter_Config_Policies:
    custom_task: Any = None
    models: Any = None
    selection_policy: Any = None
    task_slug: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ModelRouter_Config:
    # Router-level fallback models
    fallback_models: Any = None
    # Task routing policies
    policies: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_ModelRouter:
    config: Any = None
    # Creation date / time
    created_at: Any = None
    # Description
    description: Any = None
    # Name of the model router
    name: Any = None
    # Target regions for the router
    regions: Any = None
    # Last modified
    updated_at: Any = None
    # Unique id
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_OpenaiApiKey:
    # Key creation date
    created_at: Any = None
    # Created by user id from DO
    created_by: Any = None
    # Key deleted date
    deleted_at: Any = None
    # Models supported by the openAI api key
    models: Any = None
    # Name
    name: Any = None
    # Key last updated date
    updated_at: Any = None
    # Uuid
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Template_Guardrails:
    priority: Any = None
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Template:
    # The agent template's creation date
    created_at: Any = None
    # Deprecated - Use summary instead
    description: Any = None
    # List of guardrails associated with the agent template
    guardrails: Any = None
    # Instructions for the agent template
    instruction: Any = None
    # The 'k' value for the agent template
    k: Any = None
    # List of knowledge bases associated with the agent template
    knowledge_bases: Any = None
    # The long description of the agent template
    long_description: Any = None
    # The max_tokens setting for the agent template
    max_tokens: Any = None
    # Description of a Model
    model: Any = None
    # Name of the agent template
    name: Any = None
    # The short description of the agent template
    short_description: Any = None
    # The summary of the agent template
    summary: Any = None
    # List of tags associated with the agent template
    tags: Any = None
    # The temperature setting for the agent template
    temperature: Any = None
    # - AGENT_TEMPLATE_TYPE_STANDARD: The standard agent template - AGENT_TEMPLATE_TYPE_ONE_CLICK: The one click agent template
    template_type: Any = None
    # The top_p setting for the agent template
    top_p: Any = None
    # The agent template's last updated date
    updated_at: Any = None
    # Unique id
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace_EvaluationTestCases_Dataset:
    created_at: Any = None
    dataset_name: Any = None
    dataset_type: Any = None
    dataset_uuid: Any = None
    file_size: Any = None
    has_ground_truth: Any = None
    row_count: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace_EvaluationTestCases_Metrics_AssociatedPresets:
    eval_preset_uuid: Any = None
    name: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace_EvaluationTestCases_Metrics_CustomEvalConfig:
    created_at: Any = None
    deleted_at: Any = None
    requires_ground_truth: Any = None
    scoring_prompt: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace_EvaluationTestCases_Metrics:
    associated_presets: Any = None
    category: Any = None
    custom_eval_config: Any = None
    description: Any = None
    evaluation_scope: Any = None
    inverted: Any = None
    is_metric_goal: Any = None
    metric_name: Any = None
    metric_rank: Any = None
    metric_type: Any = None
    metric_uuid: Any = None
    metric_value_type: Any = None
    range_max: Any = None
    range_min: Any = None
    source: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace_EvaluationTestCases_StarMetric:
    metric_uuid: Any = None
    name: Any = None
    success_threshold: Any = None
    success_threshold_pct: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace_EvaluationTestCases:
    archived_at: Any = None
    created_at: Any = None
    created_by_user_email: Any = None
    created_by_user_id: Any = None
    dataset: Any = None
    dataset_name: Any = None
    dataset_uuid: Any = None
    description: Any = None
    latest_version_number_of_runs: Any = None
    metrics: Any = None
    name: Any = None
    star_metric: Any = None
    test_case_uuid: Any = None
    total_runs: Any = None
    updated_at: Any = None
    updated_by_user_email: Any = None
    updated_by_user_id: Any = None
    version: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent_Workspace:
    # Agents
    agents: Any = None
    # Creation date
    created_at: Any = None
    # The id of user who created this workspace
    created_by: Any = None
    # The email of the user who created this workspace
    created_by_email: Any = None
    # Deleted date
    deleted_at: Any = None
    # Description of the workspace
    description: Any = None
    # Evaluations
    evaluation_test_cases: Any = None
    # Name of the workspace
    name: Any = None
    # Update date
    updated_at: Any = None
    # Unique id
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutput_Agent:
    # Anthropic API Key Info
    anthropic_api_key: Any = None
    # Api key infos
    api_key_infos: Any = None
    # Api keys
    api_keys: Any = None
    # A Chatbot
    chatbot: Any = None
    # Chatbot identifiers
    chatbot_identifiers: Any = None
    # Child agents
    child_agents: Any = None
    # Whether conversation logs are enabled for the agent
    conversation_logs_enabled: Any = None
    # Creation date / time
    created_at: Any = None
    # Description of deployment
    deployment: Any = None
    # Description of agent
    description: Any = None
    functions: Any = None
    # The guardrails the agent is attached to
    guardrails: Any = None
    if_case: Any = None
    # Agent instruction. Instructions help your agent to perform its job effectively. See [Write Effective Agent Instructions](https://docs.digitalocean.com/products/genai-platform/concepts/best-practices/#agent-instructions) for best practices.
    instruction: Any = None
    k: Any = None
    # Knowledge bases
    knowledge_bases: Any = None
    logging_config: Any = None
    max_tokens: Any = None
    # MCP (Model Context Protocol) servers attached to this agent
    mcp_servers: Any = None
    # Description of a Model
    model: Any = None
    model_provider_key: Any = None
    # Model router
    model_router: Any = None
    # Agent name
    name: Any = None
    # OpenAI API Key Info
    openai_api_key: Any = None
    # Parent agents
    parent_agents: Any = None
    project_id: Any = None
    # Whether the agent should provide in-response citations
    provide_citations: Any = None
    # The reasoning effort for the agent
    reasoning_effort: Any = None
    # Region code
    region: Any = None
    # - RETRIEVAL_METHOD_UNKNOWN: The retrieval method is unknown - RETRIEVAL_METHOD_REWRITE: The retrieval method is rewrite - RETRIEVAL_METHOD_STEP_BACK: The retrieval method is step back - RETRIEVAL_METHOD_SUB_QUERIES: The retrieval method is sub queries - RETRIEVAL_METHOD_NONE: The retrieval method is none
    retrieval_method: Any = None
    # Creation of route date / time
    route_created_at: Any = None
    route_created_by: Any = None
    # Route name
    route_name: Any = None
    route_uuid: Any = None
    # Agent tag to organize related resources
    tags: Any = None
    temperature: Any = None
    # Represents an AgentTemplate entity
    template: Any = None
    # The thinking token budget for Anthropic extended thinking (0 = disabled)
    thinking_token_budget: Any = None
    top_p: Any = None
    # Last modified
    updated_at: Any = None
    # Access your agent under this url
    url: Any = None
    # Id of user that created the agent
    user_id: Any = None
    # Unique agent id
    uuid: Any = None
    # The latest version of the agent
    version_hash: Any = None
    # VPC Egress IPs
    vpc_egress_ips: Any = None
    vpc_uuid: Any = None
    # Whether this agent can use the built-in web_fetch tool.
    web_fetch_enabled: Any = None
    # Whether this agent can use the built-in web_search tool.
    web_search_enabled: Any = None
    workspace: Any = None

_GetAgentOutput_Agent_McpServersFields = {
    "allowed_tools": ubx.FieldSpec(wire_name="allowed_tools"),
    "authorization": ubx.FieldSpec(wire_name="authorization"),
    "headers": ubx.FieldSpec(wire_name="headers"),
    "server_label": ubx.FieldSpec(wire_name="server_label"),
    "server_url": ubx.FieldSpec(wire_name="server_url"),
}

@dataclasses.dataclass
class GetAgentOutputConfig:
    # Optional Anthropic API key ID to use with Anthropic models
    anthropic_key_uuid: Any = None
    # A text description of the agent, not used in inference
    description: Any = None
    # Agent instruction. Instructions help your agent to perform its job effectively. See [Write Effective Agent Instructions](https://docs.digitalocean.com/products/genai-platform/concepts/best-practices/#agent-instructions) for best practices.
    instruction: Any = None
    # Ids of the knowledge base(s) to attach to the agent
    knowledge_base_uuid: Any = None
    # MCP (Model Context Protocol) servers to attach to the agent
    mcp_servers: Any = None
    model_provider_key_uuid: Any = None
    model_router_uuid: Any = None
    # Identifier for the foundation model.
    model_uuid: Any = None
    # Agent name
    name: Any = None
    # Optional OpenAI API key ID to use with OpenAI models
    open_ai_key_uuid: Any = None
    # The id of the DigitalOcean project this agent will belong to
    project_id: Any = None
    reasoning_effort: Any = None
    # The DigitalOcean region to deploy your agent in
    region: Any = None
    router_preset_slug: Any = None
    # Agent tag to organize related resources
    tags: Any = None
    thinking_token_budget: Any = None
    # Whether the agent can use the built-in web_fetch tool to retrieve content from public web pages.
    web_fetch_enabled: Any = None
    # Whether the agent can use the built-in web_search tool to search the public web for current information.
    web_search_enabled: Any = None
    # Identifier for the workspace
    workspace_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    uuid: Any = None

@dataclasses.dataclass
class GetAgentOutputAttrs:
    # An Agent
    agent: Any = None
    # Optional Anthropic API key ID to use with Anthropic models
    anthropic_key_uuid: Any = None
    # A text description of the agent, not used in inference
    description: Any = None
    # Agent instruction. Instructions help your agent to perform its job effectively. See [Write Effective Agent Instructions](https://docs.digitalocean.com/products/genai-platform/concepts/best-practices/#agent-instructions) for best practices.
    instruction: Any = None
    # Ids of the knowledge base(s) to attach to the agent
    knowledge_base_uuid: Any = None
    # MCP (Model Context Protocol) servers to attach to the agent
    mcp_servers: Any = None
    model_provider_key_uuid: Any = None
    model_router_uuid: Any = None
    # Identifier for the foundation model.
    model_uuid: Any = None
    # Agent name
    name: Any = None
    # Optional OpenAI API key ID to use with OpenAI models
    open_ai_key_uuid: Any = None
    # The id of the DigitalOcean project this agent will belong to
    project_id: Any = None
    reasoning_effort: Any = None
    # The DigitalOcean region to deploy your agent in
    region: Any = None
    router_preset_slug: Any = None
    # Agent tag to organize related resources
    tags: Any = None
    thinking_token_budget: Any = None
    # Whether the agent can use the built-in web_fetch tool to retrieve content from public web pages.
    web_fetch_enabled: Any = None
    # Whether the agent can use the built-in web_search tool to search the public web for current information.
    web_search_enabled: Any = None
    # Identifier for the workspace
    workspace_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    uuid: Any = None

GetAgentOutput = ubx.ResourceBinding(
    wire_type="digitalocean_api_get_agent_output",
    fields={
        "anthropic_key_uuid": ubx.FieldSpec(wire_name="anthropic_key_uuid"),
        "description": ubx.FieldSpec(wire_name="description"),
        "instruction": ubx.FieldSpec(wire_name="instruction"),
        "knowledge_base_uuid": ubx.FieldSpec(wire_name="knowledge_base_uuid"),
        "mcp_servers": ubx.FieldSpec(
            wire_name="mcp_servers",
            kind="list",
            fields=_GetAgentOutput_Agent_McpServersFields,
        ),
        "model_provider_key_uuid": ubx.FieldSpec(wire_name="model_provider_key_uuid"),
        "model_router_uuid": ubx.FieldSpec(wire_name="model_router_uuid"),
        "model_uuid": ubx.FieldSpec(wire_name="model_uuid"),
        "name": ubx.FieldSpec(wire_name="name"),
        "open_ai_key_uuid": ubx.FieldSpec(wire_name="open_ai_key_uuid"),
        "project_id": ubx.FieldSpec(wire_name="project_id"),
        "reasoning_effort": ubx.FieldSpec(wire_name="reasoning_effort"),
        "region": ubx.FieldSpec(wire_name="region"),
        "router_preset_slug": ubx.FieldSpec(wire_name="router_preset_slug"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "thinking_token_budget": ubx.FieldSpec(wire_name="thinking_token_budget"),
        "web_fetch_enabled": ubx.FieldSpec(wire_name="web_fetch_enabled"),
        "web_search_enabled": ubx.FieldSpec(wire_name="web_search_enabled"),
        "workspace_uuid": ubx.FieldSpec(wire_name="workspace_uuid"),
        "uuid": ubx.FieldSpec(wire_name="uuid"),
    },
)
