// Code generated by `ubx sdk gen` from digitalocean_attachment. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AttachmentConfig {
  paId: string | Computed<string>;
}

export interface AttachmentAttrs {
  paId: string;
}

export const Attachment: DataSourceBinding<AttachmentConfig, AttachmentAttrs> = {
  wireType: "digitalocean_attachment",
  fields: {
    paId: "pa_id",
  },
};
