// Code generated by `ubx sdk gen` from digitalocean_invoice_summary. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface InvoiceSummary_CreditsAndAdjustments {
  amount?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface InvoiceSummary_ProductCharges_Items {
  amount?: string | Computed<string>;
  count?: string | Computed<string>;
  name?: string | Computed<string>;
}

export interface InvoiceSummary_ProductCharges {
  amount?: string | Computed<string>;
  items?: InvoiceSummary_ProductCharges_Items[] | Computed<InvoiceSummary_ProductCharges_Items[]>;
  name?: string | Computed<string>;
}

export interface InvoiceSummary_UserBillingAddress {
  addressLine1?: string | Computed<string>;
  addressLine2?: string | Computed<string>;
  city?: string | Computed<string>;
  countryIso2Code?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  postalCode?: string | Computed<string>;
  region?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface InvoiceSummaryConfig {
  invoiceUuid: string | Computed<string>;
}

export interface InvoiceSummaryAttrs {
  /** Total amount of the invoice, in USD. This will reflect month-to-date usage in the invoice preview. */
  amount: string;
  /** Billing period of usage for which the invoice is issued, in `YYYY-MM` format. */
  billingPeriod: string;
  creditsAndAdjustments: InvoiceSummary_CreditsAndAdjustments;
  /** ID of the invoice */
  invoiceId: string;
  invoiceUuid: string;
  overages: InvoiceSummary_CreditsAndAdjustments;
  productCharges: InvoiceSummary_ProductCharges;
  taxes: InvoiceSummary_CreditsAndAdjustments;
  userBillingAddress: InvoiceSummary_UserBillingAddress;
  /** Company of the DigitalOcean customer being invoiced, if set. */
  userCompany: string;
  /** Email of the DigitalOcean customer being invoiced. */
  userEmail: string;
  /** Name of the DigitalOcean customer being invoiced. */
  userName: string;
}

export const InvoiceSummary: DataSourceBinding<InvoiceSummaryConfig, InvoiceSummaryAttrs> = {
  wireType: "digitalocean_invoice_summary",
  fields: {
    invoiceUuid: "invoice_uuid",
  },
};
