// Code generated by `ubx sdk gen` from digitalocean_invoice. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Invoice_InvoicePreview {
  /** Total amount of the invoice, in USD. This will reflect month-to-date usage in the invoice preview. */
  amount?: string | Computed<string>;
  /** ID of the invoice. Listed on the face of the invoice PDF as the "Invoice number". */
  invoiceId?: string | Computed<string>;
  /** Billing period of usage for which the invoice is issued, in `YYYY-MM` format. */
  invoicePeriod?: string | Computed<string>;
  /** The UUID of the invoice. The canonical reference for the invoice. */
  invoiceUuid?: string | Computed<string>;
  /** Time the invoice was last updated. This is only included with the invoice preview. */
  updatedAt?: string | Computed<string>;
}

export interface Invoice_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Invoice_Meta {
  total?: number | Computed<number>;
}

export interface InvoiceConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface InvoiceAttrs {
  /** The invoice preview. */
  invoicePreview: Invoice_InvoicePreview;
  invoices: Invoice_InvoicePreview[];
  links: Invoice_Links;
  meta: Invoice_Meta;
  page: number;
  perPage: number;
}

export const Invoice: DataSourceBinding<InvoiceConfig, InvoiceAttrs> = {
  wireType: "digitalocean_invoice",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
