// Code generated by `ubx sdk gen` from digitalocean_one_clicks. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface OneClicksConfig {
  type?: string | Computed<string>;
}

export interface OneClicksAttrs {
  type: string;
}

export const OneClicks: DataSourceBinding<OneClicksConfig, OneClicksAttrs> = {
  wireType: "digitalocean_one_clicks",
  fields: {
    type: "type",
  },
};
