# Code generated by `ubx sdk gen` from digitalocean_action. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Action_Actions_Region:
    available: Any = None
    features: Any = None
    name: Any = None
    sizes: Any = None
    slug: Any = None

@dataclasses.dataclass
class Action_Actions:
    completed_at: Any = None
    id: Any = None
    region: Any = None
    region_slug: Any = None
    resource_id: Any = None
    resource_type: Any = None
    started_at: Any = None
    status: Any = None
    type: Any = None

@dataclasses.dataclass
class Action_Links:
    pages: Any = None

@dataclasses.dataclass
class Action_Meta:
    total: Any = None

@dataclasses.dataclass
class ActionConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class ActionAttrs:
    actions: Any = None
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None

Action = ubx.DataSourceBinding(
    wire_type="digitalocean_action",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
