// Code generated by `ubx sdk gen` from digitalocean_opensearch_index. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Index_Indexes {
  createdTime?: string | Computed<string>;
  health?: string | Computed<string>;
  indexName?: string | Computed<string>;
  numberOfReplicas?: number | Computed<number>;
  numberOfShards?: number | Computed<number>;
  size?: number | Computed<number>;
  status?: string | Computed<string>;
}

export interface IndexConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface IndexAttrs {
  databaseClusterUuid: string;
  indexes: Index_Indexes[];
}

export const Index: DataSourceBinding<IndexConfig, IndexAttrs> = {
  wireType: "digitalocean_opensearch_index",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
