// Code generated by `ubx sdk gen` from digitalocean_replica. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Replica_Connection {
  database?: string | Computed<string>;
  host?: string | Computed<string>;
  password?: string | Computed<string>;
  port?: number | Computed<number>;
  ssl?: boolean | Computed<boolean>;
  uri?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface Replica_DoSettings {
  serviceCnames?: string[] | Computed<string[]>;
}

export interface Replica_Replica {
  connection?: Replica_Connection | Computed<Replica_Connection>;
  /** A time value given in ISO8601 combined date and time format that represents when the database cluster was created. */
  createdAt?: string | Computed<string>;
  doSettings?: Replica_DoSettings | Computed<Replica_DoSettings>;
  /** A unique ID that can be used to identify and reference a database replica. */
  id?: string | Computed<string>;
  /** The name to give the read-only replicating */
  name: string | Computed<string>;
  privateConnection?: Replica_Connection | Computed<Replica_Connection>;
  /** A string specifying the UUID of the VPC to which the read-only replica will be assigned. If excluded, the replica will be assigned to your account's default VPC for the region. <br><br>Requires `vpc:read` scope. */
  privateNetworkUuid?: string | Computed<string>;
  /** A slug identifier for the region where the read-only replica will be located. If excluded, the replica will be placed in the same region as the cluster. */
  region?: string | Computed<string>;
  /** A slug identifier representing the size of the node for the read-only replica. The size of the replica must be at least as large as the node size for the database cluster from which it is replicating. */
  size?: string | Computed<string>;
  /** A string representing the current status of the database cluster. */
  status?: string | Computed<string>;
  /** Additional storage added to the cluster, in MiB. If null, no additional storage is added to the cluster, beyond what is provided as a base amount from the 'size' and any previously added additional storage. */
  storageSizeMib?: number | Computed<number>;
  /** A flat array of tag names as strings applied to the read-only replica.<br><br>Requires `tag:read` scope. */
  tags?: string[] | Computed<string[]>;
}

const Replica_ConnectionFields: FieldMap = {
  database: "database",
  host: "host",
  password: "password",
  port: "port",
  ssl: "ssl",
  uri: "uri",
  user: "user",
};

const Replica_DoSettingsFields: FieldMap = {
  serviceCnames: "service_cnames",
};

export interface ReplicaConfig {
  /** The real, public connection details (host, port, user, password) for this database replica. (AI-inferred) */
  connection?: Replica_Connection | Computed<Replica_Connection>;
  /** This database replica's own, DigitalOcean-managed settings. (AI-inferred) */
  doSettings?: Replica_DoSettings | Computed<Replica_DoSettings>;
  /** The name to give the read-only replicating */
  name: string | Computed<string>;
  /** The real, private-network connection details (host, port, user, password) for this database replica. (AI-inferred) */
  privateConnection?: Replica_Connection | Computed<Replica_Connection>;
  /** A string specifying the UUID of the VPC to which the read-only replica will be assigned. If excluded, the replica will be assigned to your account's default VPC for the region. <br><br>Requires `vpc:read` scope. */
  privateNetworkUuid?: string | Computed<string>;
  /** A slug identifier for the region where the read-only replica will be located. If excluded, the replica will be placed in the same region as the cluster. */
  region?: string | Computed<string>;
  /** A slug identifier representing the size of the node for the read-only replica. The size of the replica must be at least as large as the node size for the database cluster from which it is replicating. */
  size: string | Computed<string>;
  /** Additional storage added to the cluster, in MiB. If null, no additional storage is added to the cluster, beyond what is provided as a base amount from the 'size' and any previously added additional storage. */
  storageSizeMib?: number | Computed<number>;
  /** A flat array of tag names as strings to apply to the read-only replica after it is created. Tag names can either be existing or new tags. <br><br>Requires `tag:create` scope. */
  tags?: string[] | Computed<string[]>;
  /** path parameter, not part of the API's own resource representation */
  databaseClusterUuid: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  replicaName: string | Computed<string>;
}

export interface ReplicaAttrs {
  /** The real, public connection details (host, port, user, password) for this database replica. (AI-inferred) */
  connection: Replica_Connection;
  /** A time value given in ISO8601 combined date and time format that represents when the database cluster was created. */
  createdAt: string;
  /** This database replica's own, DigitalOcean-managed settings. (AI-inferred) */
  doSettings: Replica_DoSettings;
  /** A unique ID that can be used to identify and reference a database replica. */
  id: string;
  /** The name to give the read-only replicating */
  name: string;
  /** The real, private-network connection details (host, port, user, password) for this database replica. (AI-inferred) */
  privateConnection: Replica_Connection;
  /** A string specifying the UUID of the VPC to which the read-only replica will be assigned. If excluded, the replica will be assigned to your account's default VPC for the region. <br><br>Requires `vpc:read` scope. */
  privateNetworkUuid: string;
  /** A slug identifier for the region where the read-only replica will be located. If excluded, the replica will be placed in the same region as the cluster. */
  region: string;
  /** The read-only replica's own real, current representation. (AI-inferred) */
  replica: Replica_Replica;
  /** A slug identifier representing the size of the node for the read-only replica. The size of the replica must be at least as large as the node size for the database cluster from which it is replicating. */
  size: string;
  /** A string representing the current status of the database cluster. */
  status: string;
  /** Additional storage added to the cluster, in MiB. If null, no additional storage is added to the cluster, beyond what is provided as a base amount from the 'size' and any previously added additional storage. */
  storageSizeMib: number;
  /** A flat array of tag names as strings to apply to the read-only replica after it is created. Tag names can either be existing or new tags. <br><br>Requires `tag:create` scope. */
  tags: string[];
  /** path parameter, not part of the API's own resource representation */
  databaseClusterUuid: string;
  /** path parameter, not part of the API's own resource representation */
  replicaName: string;
}

export const Replica: ResourceBinding<ReplicaConfig, ReplicaAttrs> = {
  wireType: "digitalocean_replica",
  fields: {
    connection: {
      wireName: "connection",
      kind: "object",
      fields: Replica_ConnectionFields,
    },
    doSettings: {
      wireName: "do_settings",
      kind: "object",
      fields: Replica_DoSettingsFields,
    },
    name: "name",
    privateConnection: {
      wireName: "private_connection",
      kind: "object",
      fields: Replica_ConnectionFields,
    },
    privateNetworkUuid: "private_network_uuid",
    region: "region",
    size: "size",
    storageSizeMib: "storage_size_mib",
    tags: "tags",
    databaseClusterUuid: "database_cluster_uuid",
    replicaName: "replica_name",
  },
};
