// Code generated by `ubx sdk gen` from digitalocean_project. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Project_Project {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  environment?: string | Computed<string>;
  id?: string | Computed<string>;
  isDefault?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
  ownerId?: number | Computed<number>;
  ownerUuid?: string | Computed<string>;
  purpose?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface ProjectConfig {
  /** The description of the project. The maximum length is 255 characters. */
  description?: string | Computed<string>;
  /** The environment of the project's resources. */
  environment?: string | Computed<string>;
  /** The human-readable name for the project. The maximum length is 175 characters and the name must be unique. */
  name: string | Computed<string>;
  /** The purpose of the project. The maximum length is 255 characters. It can have one of the following values: - Just trying out DigitalOcean - Class project / Educational purposes - Website or blog - Web Application - Service or API - Mobile Application - Machine learning / AI / Data processing - IoT - Operational / Developer tooling If another value for purpose is specified, for example, "your custom purpose", your purpose will be stored as `Other: your custom purpose`. */
  purpose: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  projectId: string | Computed<string>;
}

export interface ProjectAttrs {
  /** A time value given in ISO8601 combined date and time format that represents when the project was created. */
  createdAt: string;
  /** The description of the project. The maximum length is 255 characters. */
  description: string;
  /** The environment of the project's resources. */
  environment: string;
  /** The unique universal identifier of this project. */
  id: string;
  /** The human-readable name for the project. The maximum length is 175 characters and the name must be unique. */
  name: string;
  /** The integer id of the project owner. */
  ownerId: number;
  /** The unique universal identifier of the project owner. */
  ownerUuid: string;
  project: Project_Project;
  /** The purpose of the project. The maximum length is 255 characters. It can have one of the following values: - Just trying out DigitalOcean - Class project / Educational purposes - Website or blog - Web Application - Service or API - Mobile Application - Machine learning / AI / Data processing - IoT - Operational / Developer tooling If another value for purpose is specified, for example, "your custom purpose", your purpose will be stored as `Other: your custom purpose`. */
  purpose: string;
  /** A time value given in ISO8601 combined date and time format that represents when the project was updated. */
  updatedAt: string;
  /** path parameter, not part of the API's own resource representation */
  projectId: string;
}

export const Project: ResourceBinding<ProjectConfig, ProjectAttrs> = {
  wireType: "digitalocean_project",
  fields: {
    description: "description",
    environment: "environment",
    name: "name",
    purpose: "purpose",
    projectId: "project_id",
  },
};
