// Code generated by `ubx sdk gen` from digitalocean_account. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AccountConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface AccountAttrs {
  page: number;
  perPage: number;
}

export const Account: DataSourceBinding<AccountConfig, AccountAttrs> = {
  wireType: "digitalocean_account",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
