# Code generated by `ubx sdk gen` from digitalocean_db. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Db_Db:
    # The name of the database.
    name: Any = None

@dataclasses.dataclass
class DbConfig:
    # The name of the database.
    name: Any = None
    # path parameter, not part of the API's own resource representation
    database_cluster_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    database_name: Any = None

@dataclasses.dataclass
class DbAttrs:
    # The Kafka schema's own real, current representation. (AI-inferred)
    db: Any = None
    # The name of the database.
    name: Any = None
    # path parameter, not part of the API's own resource representation
    database_cluster_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    database_name: Any = None

Db = ubx.ResourceBinding(
    wire_type="digitalocean_db",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "database_cluster_uuid": ubx.FieldSpec(wire_name="database_cluster_uuid"),
        "database_name": ubx.FieldSpec(wire_name="database_name"),
    },
)
