// Code generated by `ubx sdk gen` from digitalocean_app_alert. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Alert_Alerts_Progress_Steps_Reason {
  code?: string | Computed<string>;
  message?: string | Computed<string>;
}

export interface Alert_Alerts_Progress_Steps {
  endedAt?: string | Computed<string>;
  name?: string | Computed<string>;
  reason?: Alert_Alerts_Progress_Steps_Reason | Computed<Alert_Alerts_Progress_Steps_Reason>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface Alert_Alerts_Progress {
  steps?: Alert_Alerts_Progress_Steps[] | Computed<Alert_Alerts_Progress_Steps[]>;
}

export interface Alert_Alerts_SlackWebhooks {
  channel?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface Alert_Alerts_Spec {
  disabled?: boolean | Computed<boolean>;
  operator?: string | Computed<string>;
  rule?: string | Computed<string>;
  value?: number | Computed<number>;
  window?: string | Computed<string>;
}

export interface Alert_Alerts {
  componentName?: string | Computed<string>;
  emails?: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  phase?: string | Computed<string>;
  progress?: Alert_Alerts_Progress | Computed<Alert_Alerts_Progress>;
  slackWebhooks?: Alert_Alerts_SlackWebhooks[] | Computed<Alert_Alerts_SlackWebhooks[]>;
  spec?: Alert_Alerts_Spec | Computed<Alert_Alerts_Spec>;
}

export interface AlertConfig {
  appId: string | Computed<string>;
}

export interface AlertAttrs {
  alerts: Alert_Alerts[];
  appId: string;
}

export const Alert: DataSourceBinding<AlertConfig, AlertAttrs> = {
  wireType: "digitalocean_app_alert",
  fields: {
    appId: "app_id",
  },
};
