# Code generated by `ubx sdk gen` from digitalocean_logsink_schema. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Schema_Sinks:
    pass

@dataclasses.dataclass
class SchemaConfig:
    database_cluster_uuid: Any = None

@dataclasses.dataclass
class SchemaAttrs:
    database_cluster_uuid: Any = None
    sinks: Any = None

Schema = ubx.DataSourceBinding(
    wire_type="digitalocean_logsink_schema",
    fields={
        "database_cluster_uuid": ubx.FieldSpec(wire_name="database_cluster_uuid"),
    },
)
