// Code generated by `ubx sdk gen` from digitalocean_kernel. DO NOT EDIT.
package droplets

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Kernel_Kernels struct {
	Id      any
	Name    any
	Version any
}

type Kernel_Links struct {
	Pages any
}

type Kernel_Meta struct {
	Total any
}

type KernelConfig struct {
	DropletId any
	Page      any
	PerPage   any
}

type KernelAttrs struct {
	DropletId any
	Kernels   any
	Links     any
	Meta      any
	Page      any
	PerPage   any
}

var Kernel = ubx.DataSourceBinding{
	WireType: "digitalocean_kernel",
	Fields: ubx.FieldMap{
		"DropletId": ubx.FieldSpec{WireName: "droplet_id"},
		"Page":      ubx.FieldSpec{WireName: "page"},
		"PerPage":   ubx.FieldSpec{WireName: "per_page"},
	},
}
