# Code generated by `ubx sdk gen` from digitalocean_droplet. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Droplet_Droplet_DiskInfo_Size:
    amount: Any = None
    unit: Any = None

@dataclasses.dataclass
class Droplet_Droplet_DiskInfo:
    size: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplet_GpuInfo:
    # The number of GPUs allocated to the Droplet.
    count: Any = None
    # The model of the GPU.
    model: Any = None
    vram: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Image:
    created_at: Any = None
    description: Any = None
    distribution: Any = None
    error_message: Any = None
    id: Any = None
    min_disk_size: Any = None
    name: Any = None
    public: Any = None
    regions: Any = None
    size_gigabytes: Any = None
    slug: Any = None
    status: Any = None
    tags: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Kernel:
    # A unique number used to identify and reference a specific kernel.
    id: Any = None
    # The display name of the kernel. This is shown in the web UI and is generally a descriptive title for the kernel in question.
    name: Any = None
    # A standard kernel version string representing the version, patch, and release information.
    version: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Networks_V4:
    gateway: Any = None
    ip_address: Any = None
    netmask: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Networks_V6:
    gateway: Any = None
    ip_address: Any = None
    netmask: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Networks:
    v4: Any = None
    v6: Any = None

@dataclasses.dataclass
class Droplet_Droplet_NextBackupWindow:
    end: Any = None
    start: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Region:
    # This is a boolean value that represents whether new Droplets can be created in this region.
    available: Any = None
    # This attribute is set to an array which contains features available in this region
    features: Any = None
    # The display name of the region. This will be a full name that is used in the control panel and other interfaces.
    name: Any = None
    # This attribute is set to an array which contains the identifying slugs for the sizes available in this region. sizes:read is required to view.
    sizes: Any = None
    # A human-readable string that is used as a unique identifier for each region.
    slug: Any = None

@dataclasses.dataclass
class Droplet_Droplet_Size:
    # This is a boolean value that represents whether new Droplets can be created with this size.
    available: Any = None
    # A string describing the class of Droplets created from this size. For example: Basic, General Purpose, CPU-Optimized, Memory-Optimized, or Storage-Optimized.
    description: Any = None
    # The amount of disk space set aside for Droplets of this size. The value is represented in gigabytes.
    disk: Any = None
    # An array of objects containing information about the disks available to Droplets created with this size.
    disk_info: Any = None
    # An object containing information about the GPU capabilities of Droplets created with this size.
    gpu_info: Any = None
    # The amount of RAM allocated to Droplets created of this size. The value is represented in megabytes.
    memory: Any = None
    # This describes the price of the Droplet size as measured hourly. The value is measured in US dollars.
    price_hourly: Any = None
    # This attribute describes the monthly cost of this Droplet size if the Droplet is kept for an entire month. The value is measured in US dollars.
    price_monthly: Any = None
    # An array containing the region slugs where this size is available for Droplet creates.
    regions: Any = None
    # A human-readable string that is used to uniquely identify each size.
    slug: Any = None
    # The amount of transfer bandwidth that is available for Droplets created in this size. This only counts traffic on the public interface. The value is given in terabytes.
    transfer: Any = None
    # The number of CPUs allocated to Droplets of this size.
    vcpus: Any = None

@dataclasses.dataclass
class Droplet_Droplet:
    # An array of backup IDs of any backups that have been taken of the Droplet instance. Droplet backups are enabled at the time of the instance creation.<br>Requires `image:read` scope.
    backup_ids: Any = None
    # A time value given in ISO8601 combined date and time format that represents when the Droplet was created.
    created_at: Any = None
    # The size of the Droplet's disk in gigabytes.
    disk: Any = None
    # An array of objects containing information about the disks available to the Droplet.
    disk_info: Any = None
    # An array of features enabled on this Droplet.
    features: Any = None
    # An object containing information about the GPU capabilities of Droplets created with this size.
    gpu_info: Any = None
    # A unique identifier for each Droplet instance. This is automatically generated upon Droplet creation.
    id: Any = None
    image: Any = None
    # **Note**: All Droplets created after March 2017 use internal kernels by default. These Droplets will have this attribute set to `null`. The current [kernel](https://docs.digitalocean.com/products/droplets/how-to/kernel/) for Droplets with externally managed kernels. This will initially be set to the kernel of the base image when the Droplet is created.
    kernel: Any = None
    # A boolean value indicating whether the Droplet has been locked, preventing actions by users.
    locked: Any = None
    # Memory of the Droplet in megabytes.
    memory: Any = None
    # The human-readable name set for the Droplet instance.
    name: Any = None
    # The details of the network that are configured for the Droplet instance. This is an object that contains keys for IPv4 and IPv6. The value of each of these is an array that contains objects describing an individual IP resource allocated to the Droplet. These will define attributes like the IP address, netmask, and gateway of the specific network depending on the type of network it is.
    networks: Any = None
    next_backup_window: Any = None
    region: Any = None
    size: Any = None
    # The unique slug identifier for the size of this Droplet.
    size_slug: Any = None
    # An array of snapshot IDs of any snapshots created from the Droplet instance.<br>Requires `image:read` scope.
    snapshot_ids: Any = None
    # A status string indicating the state of the Droplet instance. This may be "new", "active", "off", or "archive".
    status: Any = None
    # An array of Tags the Droplet has been tagged with.<br>Requires `tag:read` scope.
    tags: Any = None
    # The number of virtual CPUs.
    vcpus: Any = None
    # A flat array including the unique identifier for each Block Storage volume attached to the Droplet.<br>Requires `block_storage:read` scope.
    volume_ids: Any = None
    # A string specifying the UUID of the VPC to which the Droplet is assigned.<br>Requires `vpc:read` scope.
    vpc_uuid: Any = None

@dataclasses.dataclass
class DropletConfig:
    # path parameter, not part of the API's own resource representation
    droplet_id: Any = None

@dataclasses.dataclass
class DropletAttrs:
    droplet: Any = None
    # path parameter, not part of the API's own resource representation
    droplet_id: Any = None

Droplet = ubx.ResourceBinding(
    wire_type="digitalocean_droplet",
    fields={
        "droplet_id": ubx.FieldSpec(wire_name="droplet_id"),
    },
)
