// Code generated by `ubx sdk gen` from digitalocean_member. DO NOT EDIT.
package dropletautoscalepools

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Member_Droplets_CurrentUtilization struct {
	Cpu    any
	Memory any
}

type Member_Droplets struct {
	CreatedAt          any
	CurrentUtilization any
	DropletId          any
	HealthStatus       any
	Status             any
	UnhealthyReason    any
	UpdatedAt          any
}

type Member_Links struct {
	Pages any
}

type Member_Meta struct {
	Total any
}

type MemberConfig struct {
	AutoscalePoolId any
	Page            any
	PerPage         any
}

type MemberAttrs struct {
	AutoscalePoolId any
	Droplets        any
	Links           any
	Meta            any
	Page            any
	PerPage         any
}

var Member = ubx.DataSourceBinding{
	WireType: "digitalocean_member",
	Fields: ubx.FieldMap{
		"AutoscalePoolId": ubx.FieldSpec{WireName: "autoscale_pool_id"},
		"Page":            ubx.FieldSpec{WireName: "page"},
		"PerPage":         ubx.FieldSpec{WireName: "per_page"},
	},
}
