# Code generated by `ubx sdk gen` from digitalocean_check. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Check_Checks:
    enabled: Any = None
    id: Any = None
    name: Any = None
    regions: Any = None
    target: Any = None
    type: Any = None

@dataclasses.dataclass
class Check_Links:
    pages: Any = None

@dataclasses.dataclass
class Check_Meta:
    total: Any = None

@dataclasses.dataclass
class CheckConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class CheckAttrs:
    checks: Any = None
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None

Check = ubx.DataSourceBinding(
    wire_type="digitalocean_check",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
