# Code generated by `ubx sdk gen` from digitalocean_state. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class State_State_PreviousOutage:
    duration_seconds: Any = None
    ended_at: Any = None
    region: Any = None
    started_at: Any = None

@dataclasses.dataclass
class State_State_Regions_EuWest:
    status: Any = None
    status_changed_at: Any = None
    thirty_day_uptime_percentage: Any = None

@dataclasses.dataclass
class State_State_Regions:
    eu_west: Any = None
    us_east: Any = None

@dataclasses.dataclass
class State_State:
    previous_outage: Any = None
    # A map of region to regional state
    regions: Any = None

@dataclasses.dataclass
class StateConfig:
    check_id: Any = None

@dataclasses.dataclass
class StateAttrs:
    check_id: Any = None
    state: Any = None

State = ubx.DataSourceBinding(
    wire_type="digitalocean_state",
    fields={
        "check_id": ubx.FieldSpec(wire_name="check_id"),
    },
)
