# Code generated by `ubx sdk gen` from digitalocean_scan. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Scan_Scan_Findings_MitigationSteps:
    description: Any = None
    step: Any = None
    title: Any = None

@dataclasses.dataclass
class Scan_Scan_Findings:
    affected_resources_count: Any = None
    business_impact: Any = None
    details: Any = None
    found_at: Any = None
    mitigation_steps: Any = None
    name: Any = None
    rule_uuid: Any = None
    severity: Any = None
    technical_details: Any = None

@dataclasses.dataclass
class Scan_Scan:
    # When scan was created.
    created_at: Any = None
    findings: Any = None
    # The unique identifier for the scan.
    id: Any = None
    # The status of the scan.
    status: Any = None

@dataclasses.dataclass
class ScanConfig:
    # path parameter, not part of the API's own resource representation
    scan_id: Any = None

@dataclasses.dataclass
class ScanAttrs:
    scan: Any = None
    # path parameter, not part of the API's own resource representation
    scan_id: Any = None

Scan = ubx.ResourceBinding(
    wire_type="digitalocean_scan",
    fields={
        "scan_id": ubx.FieldSpec(wire_name="scan_id"),
    },
)
