# Code generated by `ubx sdk gen` from digitalocean_project. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Project_Project:
    created_at: Any = None
    description: Any = None
    environment: Any = None
    id: Any = None
    is_default: Any = None
    name: Any = None
    owner_id: Any = None
    owner_uuid: Any = None
    purpose: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class ProjectConfig:
    # The description of the project. The maximum length is 255 characters.
    description: Any = None
    # The environment of the project's resources.
    environment: Any = None
    # The human-readable name for the project. The maximum length is 175 characters and the name must be unique.
    name: Any = None
    # The purpose of the project. The maximum length is 255 characters. It can have one of the following values: - Just trying out DigitalOcean - Class project / Educational purposes - Website or blog - Web Application - Service or API - Mobile Application - Machine learning / AI / Data processing - IoT - Operational / Developer tooling If another value for purpose is specified, for example, "your custom purpose", your purpose will be stored as `Other: your custom purpose`.
    purpose: Any = None
    # path parameter, not part of the API's own resource representation
    project_id: Any = None

@dataclasses.dataclass
class ProjectAttrs:
    # A time value given in ISO8601 combined date and time format that represents when the project was created.
    created_at: Any = None
    # The description of the project. The maximum length is 255 characters.
    description: Any = None
    # The environment of the project's resources.
    environment: Any = None
    # The unique universal identifier of this project.
    id: Any = None
    # The human-readable name for the project. The maximum length is 175 characters and the name must be unique.
    name: Any = None
    # The integer id of the project owner.
    owner_id: Any = None
    # The unique universal identifier of the project owner.
    owner_uuid: Any = None
    project: Any = None
    # The purpose of the project. The maximum length is 255 characters. It can have one of the following values: - Just trying out DigitalOcean - Class project / Educational purposes - Website or blog - Web Application - Service or API - Mobile Application - Machine learning / AI / Data processing - IoT - Operational / Developer tooling If another value for purpose is specified, for example, "your custom purpose", your purpose will be stored as `Other: your custom purpose`.
    purpose: Any = None
    # A time value given in ISO8601 combined date and time format that represents when the project was updated.
    updated_at: Any = None
    # path parameter, not part of the API's own resource representation
    project_id: Any = None

Project = ubx.ResourceBinding(
    wire_type="digitalocean_project",
    fields={
        "description": ubx.FieldSpec(wire_name="description"),
        "environment": ubx.FieldSpec(wire_name="environment"),
        "name": ubx.FieldSpec(wire_name="name"),
        "purpose": ubx.FieldSpec(wire_name="purpose"),
        "project_id": ubx.FieldSpec(wire_name="project_id"),
    },
)
