# Code generated by `ubx sdk gen` from digitalocean_byoip_prefix. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ByoipPrefix_ByoipPrefixes_Validations:
    name: Any = None
    note: Any = None
    status: Any = None

@dataclasses.dataclass
class ByoipPrefix_ByoipPrefixes:
    advertised: Any = None
    failure_reason: Any = None
    locked: Any = None
    name: Any = None
    prefix: Any = None
    project_id: Any = None
    region: Any = None
    status: Any = None
    uuid: Any = None
    validations: Any = None

@dataclasses.dataclass
class ByoipPrefix_Links:
    pages: Any = None

@dataclasses.dataclass
class ByoipPrefix_Meta:
    total: Any = None

@dataclasses.dataclass
class ByoipPrefixConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class ByoipPrefixAttrs:
    byoip_prefixes: Any = None
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None

ByoipPrefix = ubx.DataSourceBinding(
    wire_type="digitalocean_byoip_prefix",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
