# Code generated by `ubx sdk gen` from digitalocean_replica. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Replica_Replica_Connection:
    database: Any = None
    host: Any = None
    password: Any = None
    port: Any = None
    ssl: Any = None
    uri: Any = None
    user: Any = None

@dataclasses.dataclass
class Replica_Replica_DoSettings:
    service_cnames: Any = None

@dataclasses.dataclass
class Replica_Replica:
    connection: Any = None
    # A time value given in ISO8601 combined date and time format that represents when the database cluster was created.
    created_at: Any = None
    do_settings: Any = None
    # A unique ID that can be used to identify and reference a database replica.
    id: Any = None
    # The name to give the read-only replicating
    name: Any = None
    private_connection: Any = None
    # A string specifying the UUID of the VPC to which the read-only replica will be assigned. If excluded, the replica will be assigned to your account's default VPC for the region. <br><br>Requires `vpc:read` scope.
    private_network_uuid: Any = None
    # A slug identifier for the region where the read-only replica will be located. If excluded, the replica will be placed in the same region as the cluster.
    region: Any = None
    # A slug identifier representing the size of the node for the read-only replica. The size of the replica must be at least as large as the node size for the database cluster from which it is replicating.
    size: Any = None
    # A string representing the current status of the database cluster.
    status: Any = None
    # Additional storage added to the cluster, in MiB. If null, no additional storage is added to the cluster, beyond what is provided as a base amount from the 'size' and any previously added additional storage.
    storage_size_mib: Any = None
    # A flat array of tag names as strings applied to the read-only replica.<br><br>Requires `tag:read` scope.
    tags: Any = None

@dataclasses.dataclass
class ReplicaConfig:
    # path parameter, not part of the API's own resource representation
    database_cluster_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    replica_name: Any = None

@dataclasses.dataclass
class ReplicaAttrs:
    replica: Any = None
    # path parameter, not part of the API's own resource representation
    database_cluster_uuid: Any = None
    # path parameter, not part of the API's own resource representation
    replica_name: Any = None

Replica = ubx.ResourceBinding(
    wire_type="digitalocean_replica",
    fields={
        "database_cluster_uuid": ubx.FieldSpec(wire_name="database_cluster_uuid"),
        "replica_name": ubx.FieldSpec(wire_name="replica_name"),
    },
)
