// Code generated by `ubx sdk gen` from digitalocean_ca. DO NOT EDIT.
package databases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Ca_Ca struct {
	// base64 encoding of the certificate used to secure database connections
	Certificate any
}

type CaConfig struct {
	DatabaseClusterUuid any
}

type CaAttrs struct {
	Ca                  any
	DatabaseClusterUuid any
}

var Ca = ubx.DataSourceBinding{
	WireType: "digitalocean_ca",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
	},
}
