// Code generated by `ubx sdk gen` from digitalocean_database_cluster_read. DO NOT EDIT.
package databases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DatabaseClusterRead_Databases_Connection struct {
	Database any
	Host     any
	Password any
	Port     any
	Ssl      any
	Uri      any
	User     any
}

type DatabaseClusterRead_Databases_DoSettings struct {
	ServiceCnames any
}

type DatabaseClusterRead_Databases_MaintenanceWindow struct {
	Day         any
	Description any
	Hour        any
	Pending     any
}

type DatabaseClusterRead_Databases_MetricsEndpoints struct {
	Host any
	Port any
}

type DatabaseClusterRead_Databases_Rules struct {
	ClusterUuid any
	CreatedAt   any
	Description any
	Type        any
	Uuid        any
	Value       any
}

type DatabaseClusterRead_Databases_SchemaRegistryConnection struct {
	Host     any
	Password any
	Port     any
	Ssl      any
	Uri      any
	User     any
}

type DatabaseClusterRead_Databases_Users_MysqlSettings struct {
	AuthPlugin any
}

type DatabaseClusterRead_Databases_Users_Settings_Acl struct {
	Id         any
	Permission any
	Topic      any
}

type DatabaseClusterRead_Databases_Users_Settings_MongoUserSettings struct {
	Databases any
	Role      any
}

type DatabaseClusterRead_Databases_Users_Settings_OpensearchAcl struct {
	Index      any
	Permission any
}

type DatabaseClusterRead_Databases_Users_Settings struct {
	Acl                any
	MongoUserSettings  any
	OpensearchAcl      any
	PgAllowReplication any
}

type DatabaseClusterRead_Databases_Users struct {
	AccessCert    any
	AccessKey     any
	MysqlSettings any
	Name          any
	Password      any
	Role          any
	Settings      any
}

type DatabaseClusterRead_Databases struct {
	Connection               any
	CreatedAt                any
	DbNames                  any
	DoSettings               any
	Engine                   any
	Id                       any
	MaintenanceWindow        any
	MetricsEndpoints         any
	Name                     any
	NumNodes                 any
	PrivateConnection        any
	PrivateNetworkUuid       any
	ProjectId                any
	Region                   any
	Rules                    any
	SchemaRegistryConnection any
	SemanticVersion          any
	Size                     any
	StandbyConnection        any
	StandbyPrivateConnection any
	Status                   any
	StorageSizeMib           any
	Tags                     any
	UiConnection             any
	Users                    any
	Version                  any
	VersionEndOfAvailability any
	VersionEndOfLife         any
}

type DatabaseClusterReadConfig struct {
	TagName any
}

type DatabaseClusterReadAttrs struct {
	Databases any
	TagName   any
}

var DatabaseClusterRead = ubx.DataSourceBinding{
	WireType: "digitalocean_database_cluster_read",
	Fields: ubx.FieldMap{
		"TagName": ubx.FieldSpec{WireName: "tag_name"},
	},
}
