// Code generated by `ubx sdk gen` from digitalocean_firewall_rule. DO NOT EDIT.
package databases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FirewallRule_Rules struct {
	ClusterUuid any
	CreatedAt   any
	Description any
	Type        any
	Uuid        any
	Value       any
}

type FirewallRuleConfig struct {
	DatabaseClusterUuid any
}

type FirewallRuleAttrs struct {
	DatabaseClusterUuid any
	Rules               any
}

var FirewallRule = ubx.DataSourceBinding{
	WireType: "digitalocean_firewall_rule",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
	},
}
