// Code generated by `ubx sdk gen` from digitalocean_opensearch_index. DO NOT EDIT.
package databases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OpensearchIndex_Indexes struct {
	CreatedTime      any
	Health           any
	IndexName        any
	NumberOfReplicas any
	NumberOfShards   any
	Size             any
	Status           any
}

type OpensearchIndexConfig struct {
	DatabaseClusterUuid any
}

type OpensearchIndexAttrs struct {
	DatabaseClusterUuid any
	Indexes             any
}

var OpensearchIndex = ubx.DataSourceBinding{
	WireType: "digitalocean_opensearch_index",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
	},
}
