// Code generated by `ubx sdk gen` from digitalocean_version. DO NOT EDIT.
package databases

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VersionConfig struct {
	DatabaseClusterUuid any
	SubjectName         any
	Version             any
}

type VersionAttrs struct {
	DatabaseClusterUuid any
	// The schema definition in the specified format.
	Schema any
	// The id for schema.
	SchemaId any
	// The type of the schema.
	SchemaType  any
	SubjectName any
	Version     any
}

var Version = ubx.DataSourceBinding{
	WireType: "digitalocean_version",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
		"SubjectName":         ubx.FieldSpec{WireName: "subject_name"},
		"Version":             ubx.FieldSpec{WireName: "version"},
	},
}
