// Code generated by `ubx sdk gen` from digitalocean_apps_deployments_response. DO NOT EDIT.
package apps

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DeploymentsResponseConfig struct {
	AppId any
	DeploymentTypes any
	Page any
	PerPage any
}

type DeploymentsResponseAttrs struct {
	AppId any
	DeploymentTypes any
	Page any
	PerPage any
}

var DeploymentsResponse = ubx.DataSourceBinding{
	WireType: "digitalocean_apps_deployments_response",
	Fields: ubx.FieldMap{
		"AppId": ubx.FieldSpec{WireName: "app_id"},
		"DeploymentTypes": ubx.FieldSpec{WireName: "deployment_types"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
