// Code generated by `ubx sdk gen` from digitalocean_floating_ip. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface FloatingIp_FloatingIps_Droplet_DiskInfo_Size {
  amount?: number | Computed<number>;
  unit?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_DiskInfo {
  size?: FloatingIp_FloatingIps_Droplet_DiskInfo_Size | Computed<FloatingIp_FloatingIps_Droplet_DiskInfo_Size>;
  type?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_GpuInfo {
  count?: number | Computed<number>;
  model?: string | Computed<string>;
  vram?: FloatingIp_FloatingIps_Droplet_DiskInfo_Size | Computed<FloatingIp_FloatingIps_Droplet_DiskInfo_Size>;
}

export interface FloatingIp_FloatingIps_Droplet_Image {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  distribution?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
  id?: number | Computed<number>;
  minDiskSize?: number | Computed<number>;
  name?: string | Computed<string>;
  public?: boolean | Computed<boolean>;
  regions?: string[] | Computed<string[]>;
  sizeGigabytes?: number | Computed<number>;
  slug?: string | Computed<string>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  type?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_Kernel {
  id?: number | Computed<number>;
  name?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_Networks_V4 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_Networks_V6 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_Networks {
  v4?: FloatingIp_FloatingIps_Droplet_Networks_V4[] | Computed<FloatingIp_FloatingIps_Droplet_Networks_V4[]>;
  v6?: FloatingIp_FloatingIps_Droplet_Networks_V6[] | Computed<FloatingIp_FloatingIps_Droplet_Networks_V6[]>;
}

export interface FloatingIp_FloatingIps_Droplet_NextBackupWindow {
  end?: string | Computed<string>;
  start?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_Region {
  available?: boolean | Computed<boolean>;
  features?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  sizes?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps_Droplet_Size {
  available?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: FloatingIp_FloatingIps_Droplet_DiskInfo[] | Computed<FloatingIp_FloatingIps_Droplet_DiskInfo[]>;
  gpuInfo?: FloatingIp_FloatingIps_Droplet_GpuInfo | Computed<FloatingIp_FloatingIps_Droplet_GpuInfo>;
  memory?: number | Computed<number>;
  priceHourly?: number | Computed<number>;
  priceMonthly?: number | Computed<number>;
  regions?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
  transfer?: number | Computed<number>;
  vcpus?: number | Computed<number>;
}

export interface FloatingIp_FloatingIps_Droplet {
  backupIds?: number[] | Computed<number[]>;
  createdAt?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: FloatingIp_FloatingIps_Droplet_DiskInfo[] | Computed<FloatingIp_FloatingIps_Droplet_DiskInfo[]>;
  features?: string[] | Computed<string[]>;
  gpuInfo?: FloatingIp_FloatingIps_Droplet_GpuInfo | Computed<FloatingIp_FloatingIps_Droplet_GpuInfo>;
  id?: number | Computed<number>;
  image?: FloatingIp_FloatingIps_Droplet_Image | Computed<FloatingIp_FloatingIps_Droplet_Image>;
  kernel?: FloatingIp_FloatingIps_Droplet_Kernel | Computed<FloatingIp_FloatingIps_Droplet_Kernel>;
  locked?: boolean | Computed<boolean>;
  memory?: number | Computed<number>;
  name?: string | Computed<string>;
  networks?: FloatingIp_FloatingIps_Droplet_Networks | Computed<FloatingIp_FloatingIps_Droplet_Networks>;
  nextBackupWindow?: FloatingIp_FloatingIps_Droplet_NextBackupWindow | Computed<FloatingIp_FloatingIps_Droplet_NextBackupWindow>;
  region?: FloatingIp_FloatingIps_Droplet_Region | Computed<FloatingIp_FloatingIps_Droplet_Region>;
  size?: FloatingIp_FloatingIps_Droplet_Size | Computed<FloatingIp_FloatingIps_Droplet_Size>;
  sizeSlug?: string | Computed<string>;
  snapshotIds?: number[] | Computed<number[]>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  vcpus?: number | Computed<number>;
  volumeIds?: string[] | Computed<string[]>;
  vpcUuid?: string | Computed<string>;
}

export interface FloatingIp_FloatingIps {
  droplet?: FloatingIp_FloatingIps_Droplet | Computed<FloatingIp_FloatingIps_Droplet>;
  ip?: string | Computed<string>;
  locked?: boolean | Computed<boolean>;
  projectId?: string | Computed<string>;
  region?: FloatingIp_FloatingIps_Droplet_Region | Computed<FloatingIp_FloatingIps_Droplet_Region>;
}

export interface FloatingIp_Links {
  pages?: unknown | Computed<unknown>;
}

export interface FloatingIp_Meta {
  total?: number | Computed<number>;
}

export interface FloatingIpConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface FloatingIpAttrs {
  floatingIps: FloatingIp_FloatingIps[];
  links: FloatingIp_Links;
  meta: FloatingIp_Meta;
  page: number;
  perPage: number;
}

export const FloatingIp: DataSourceBinding<FloatingIpConfig, FloatingIpAttrs> = {
  wireType: "digitalocean_floating_ip",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
