// Code generated by `ubx sdk gen` from digitalocean_api_get_agent_output. DO NOT EDIT.
package gradientaiplatform

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApiGetAgentOutput_Agent_AnthropicApiKey struct {
	// Key creation date
	CreatedAt any
	// Created by user id from DO
	CreatedBy any
	// Key deleted date
	DeletedAt any
	// Name
	Name any
	// Key last updated date
	UpdatedAt any
	// Uuid
	Uuid any
}

type ApiGetAgentOutput_Agent_ApiKeyInfos struct {
	CreatedAt any
	CreatedBy any
	DeletedAt any
	Name      any
	SecretKey any
	Uuid      any
}

type ApiGetAgentOutput_Agent_ApiKeys struct {
	ApiKey any
}

type ApiGetAgentOutput_Agent_Chatbot struct {
	AllowedDomains        any
	ButtonBackgroundColor any
	Logo                  any
	// Name of chatbot
	Name            any
	PrimaryColor    any
	SecondaryColor  any
	StartingMessage any
}

type ApiGetAgentOutput_Agent_ChatbotIdentifiers struct {
	AgentChatbotIdentifier any
}

type ApiGetAgentOutput_Agent_ChildAgents struct {
}

type ApiGetAgentOutput_Agent_Deployment struct {
	// Creation date / time
	CreatedAt any
	// Name
	Name   any
	Status any
	// Last modified
	UpdatedAt any
	// Access your deployed agent here
	Url any
	// Unique id
	Uuid any
	// - VISIBILITY_UNKNOWN: The status of the deployment is unknown - VISIBILITY_DISABLED: The deployment is disabled and will no longer service requests - VISIBILITY_PLAYGROUND: Deprecated: No longer a valid state - VISIBILITY_PUBLIC: The deployment is public and will service requests from the public internet - VISIBILITY_PRIVATE: The deployment is private and will only service requests from other agents, or through API keys
	Visibility any
}

type ApiGetAgentOutput_Agent_Functions struct {
	ApiKey        any
	CreatedAt     any
	CreatedBy     any
	Description   any
	FaasName      any
	FaasNamespace any
	InputSchema   any
	Name          any
	OutputSchema  any
	UpdatedAt     any
	Url           any
	Uuid          any
}

type ApiGetAgentOutput_Agent_Guardrails struct {
	AgentUuid       any
	CreatedAt       any
	DefaultResponse any
	Description     any
	GuardrailUuid   any
	IsAttached      any
	IsDefault       any
	Metadata        any
	Name            any
	Priority        any
	Type            any
	UpdatedAt       any
	Uuid            any
}

type ApiGetAgentOutput_Agent_KnowledgeBases_LastIndexingJob_DataSourceJobs struct {
	CompletedAt       any
	DataSourceUuid    any
	ErrorDetails      any
	ErrorMsg          any
	FailedItemCount   any
	IndexedFileCount  any
	IndexedItemCount  any
	RemovedItemCount  any
	SkippedItemCount  any
	StartedAt         any
	Status            any
	TotalBytes        any
	TotalBytesIndexed any
	TotalFileCount    any
}

type ApiGetAgentOutput_Agent_KnowledgeBases_LastIndexingJob struct {
	CompletedDatasources any
	CreatedAt            any
	DataSourceJobs       any
	DataSourceUuids      any
	FinishedAt           any
	IsReportAvailable    any
	KnowledgeBaseUuid    any
	Phase                any
	StartedAt            any
	Status               any
	Tokens               any
	TotalDatasources     any
	TotalTokens          any
	UpdatedAt            any
	Uuid                 any
}

type ApiGetAgentOutput_Agent_KnowledgeBases_RerankingConfig struct {
	Enabled any
	Model   any
}

type ApiGetAgentOutput_Agent_KnowledgeBases struct {
	AddedToAgentAt     any
	CreatedAt          any
	DatabaseId         any
	EmbeddingModelUuid any
	IsPublic           any
	LastIndexingJob    any
	Name               any
	ProjectId          any
	Region             any
	RerankingConfig    any
	Tags               any
	UpdatedAt          any
	UserId             any
	Uuid               any
}

type ApiGetAgentOutput_Agent_LoggingConfig struct {
	// Galileo project identifier
	GalileoProjectId any
	// Name of the Galileo project
	GalileoProjectName any
	// Whether insights are enabled
	InsightsEnabled any
	// Timestamp when insights were enabled
	InsightsEnabledAt any
	// Identifier for the log stream
	LogStreamId any
	// Name of the log stream
	LogStreamName any
}

type ApiGetAgentOutput_Agent_McpServers struct {
	AllowedTools  any
	Authorization any
	Headers       any
	ServerLabel   any
	ServerUrl     any
}

type ApiGetAgentOutput_Agent_Model_Agreement struct {
	Description any
	Name        any
	Url         any
	Uuid        any
}

type ApiGetAgentOutput_Agent_Model_Endpoints struct {
	Capabilities any
	Endpoint     any
}

type ApiGetAgentOutput_Agent_Model_Modalities struct {
	Input  any
	Output any
}

type ApiGetAgentOutput_Agent_Model_Settings struct {
	DefaultString any
	DefaultValue  any
	Max           any
	Min           any
	Name          any
	Options       any
	Step          any
	Type          any
}

type ApiGetAgentOutput_Agent_Model_Version struct {
	// Major version number
	Major any
	// Minor version number
	Minor any
	// Patch version number
	Patch any
}

type ApiGetAgentOutput_Agent_Model struct {
	// Agreement Description
	Agreement any
	// Benchmark scores for this model, stored as arbitrary JSON
	BenchmarkScore any
	// High-level capabilities (e.g. tool_calling, vision, streaming)
	Capabilities any
	// Context window size in tokens
	ContextWindow any
	// Creation date / time
	CreatedAt any
	// Available endpoints and their capabilities
	Endpoints any
	// Internally used name
	InferenceName any
	// Internally used version
	InferenceVersion any
	// True if it is a foundational model provided by do
	IsFoundational any
	// Default chunking size limit to show in UI
	KbDefaultChunkSize any
	// Maximum chunk size limit of model
	KbMaxChunkSize any
	// Minimum chunking size token limits if model supports KNOWLEDGEBASE usecase
	KbMinChunkSize any
	// Lifecycle status of the model (internal, public-preview, active, deprecated, end_of_life)
	LifecycleStatus any
	// Additional meta data
	Metadata any
	// Input/output modalities
	Modalities any
	// Name of the model
	Name any
	// Parameter count in billions
	ParameterCount any
	// Unique id of the model, this model is based on
	ParentUuid any
	Provider   any
	// Available reasoning efforts for this model
	ReasoningEfforts any
	// Playground settings derived from model metadata
	Settings any
	// Whether this model supports extended thinking (Anthropic models)
	Thinking any
	// Model type (chat, embedding, image, reasoning, coding)
	Type any
	// Last modified
	UpdatedAt any
	// Model has been fully uploaded
	UploadComplete any
	// Download url
	Url any
	// Usecases of the model
	Usecases any
	// Unique id
	Uuid any
	// Version Information about a Model
	Version any
}

type ApiGetAgentOutput_Agent_ModelProviderKey struct {
	// API key ID
	ApiKeyUuid any
	// Key creation date
	CreatedAt any
	// Created by user id from DO
	CreatedBy any
	// Key deleted date
	DeletedAt any
	// Models supported by the openAI api key
	Models any
	// Name of the key
	Name     any
	Provider any
	// Key last updated date
	UpdatedAt any
}

type ApiGetAgentOutput_Agent_ModelRouter_Config_Policies_CustomTask struct {
	Description any
	Name        any
}

type ApiGetAgentOutput_Agent_ModelRouter_Config_Policies_SelectionPolicy struct {
	Prefer any
}

type ApiGetAgentOutput_Agent_ModelRouter_Config_Policies struct {
	CustomTask      any
	Models          any
	SelectionPolicy any
	TaskSlug        any
}

type ApiGetAgentOutput_Agent_ModelRouter_Config struct {
	// Router-level fallback models
	FallbackModels any
	// Task routing policies
	Policies any
}

type ApiGetAgentOutput_Agent_ModelRouter struct {
	Config any
	// Creation date / time
	CreatedAt any
	// Description
	Description any
	// Name of the model router
	Name any
	// Target regions for the router
	Regions any
	// Last modified
	UpdatedAt any
	// Unique id
	Uuid any
}

type ApiGetAgentOutput_Agent_OpenaiApiKey struct {
	// Key creation date
	CreatedAt any
	// Created by user id from DO
	CreatedBy any
	// Key deleted date
	DeletedAt any
	// Models supported by the openAI api key
	Models any
	// Name
	Name any
	// Key last updated date
	UpdatedAt any
	// Uuid
	Uuid any
}

type ApiGetAgentOutput_Agent_Template_Guardrails struct {
	Priority any
	Uuid     any
}

type ApiGetAgentOutput_Agent_Template struct {
	// The agent template's creation date
	CreatedAt any
	// Deprecated - Use summary instead
	Description any
	// List of guardrails associated with the agent template
	Guardrails any
	// Instructions for the agent template
	Instruction any
	// The 'k' value for the agent template
	K any
	// List of knowledge bases associated with the agent template
	KnowledgeBases any
	// The long description of the agent template
	LongDescription any
	// The max_tokens setting for the agent template
	MaxTokens any
	// Description of a Model
	Model any
	// Name of the agent template
	Name any
	// The short description of the agent template
	ShortDescription any
	// The summary of the agent template
	Summary any
	// List of tags associated with the agent template
	Tags any
	// The temperature setting for the agent template
	Temperature any
	// - AGENT_TEMPLATE_TYPE_STANDARD: The standard agent template - AGENT_TEMPLATE_TYPE_ONE_CLICK: The one click agent template
	TemplateType any
	// The top_p setting for the agent template
	TopP any
	// The agent template's last updated date
	UpdatedAt any
	// Unique id
	Uuid any
}

type ApiGetAgentOutput_Agent_Workspace_EvaluationTestCases_Dataset struct {
	CreatedAt      any
	DatasetName    any
	DatasetType    any
	DatasetUuid    any
	FileSize       any
	HasGroundTruth any
	RowCount       any
}

type ApiGetAgentOutput_Agent_Workspace_EvaluationTestCases_Metrics_AssociatedPresets struct {
	EvalPresetUuid any
	Name           any
}

type ApiGetAgentOutput_Agent_Workspace_EvaluationTestCases_Metrics_CustomEvalConfig struct {
	CreatedAt           any
	DeletedAt           any
	RequiresGroundTruth any
	ScoringPrompt       any
	UpdatedAt           any
}

type ApiGetAgentOutput_Agent_Workspace_EvaluationTestCases_Metrics struct {
	AssociatedPresets any
	Category          any
	CustomEvalConfig  any
	Description       any
	EvaluationScope   any
	Inverted          any
	IsMetricGoal      any
	MetricName        any
	MetricRank        any
	MetricType        any
	MetricUuid        any
	MetricValueType   any
	RangeMax          any
	RangeMin          any
	Source            any
}

type ApiGetAgentOutput_Agent_Workspace_EvaluationTestCases_StarMetric struct {
	MetricUuid          any
	Name                any
	SuccessThreshold    any
	SuccessThresholdPct any
}

type ApiGetAgentOutput_Agent_Workspace_EvaluationTestCases struct {
	ArchivedAt                any
	CreatedAt                 any
	CreatedByUserEmail        any
	CreatedByUserId           any
	Dataset                   any
	DatasetName               any
	DatasetUuid               any
	Description               any
	LatestVersionNumberOfRuns any
	Metrics                   any
	Name                      any
	StarMetric                any
	TestCaseUuid              any
	TotalRuns                 any
	UpdatedAt                 any
	UpdatedByUserEmail        any
	UpdatedByUserId           any
	Version                   any
}

type ApiGetAgentOutput_Agent_Workspace struct {
	// Agents
	Agents any
	// Creation date
	CreatedAt any
	// The id of user who created this workspace
	CreatedBy any
	// The email of the user who created this workspace
	CreatedByEmail any
	// Deleted date
	DeletedAt any
	// Description of the workspace
	Description any
	// Evaluations
	EvaluationTestCases any
	// Name of the workspace
	Name any
	// Update date
	UpdatedAt any
	// Unique id
	Uuid any
}

type ApiGetAgentOutput_Agent struct {
	// Anthropic API Key Info
	AnthropicApiKey any
	// Api key infos
	ApiKeyInfos any
	// Api keys
	ApiKeys any
	// A Chatbot
	Chatbot any
	// Chatbot identifiers
	ChatbotIdentifiers any
	// Child agents
	ChildAgents any
	// Whether conversation logs are enabled for the agent
	ConversationLogsEnabled any
	// Creation date / time
	CreatedAt any
	// Description of deployment
	Deployment any
	// Description of agent
	Description any
	Functions   any
	// The guardrails the agent is attached to
	Guardrails any
	IfCase     any
	// Agent instruction. Instructions help your agent to perform its job effectively. See [Write Effective Agent Instructions](https://docs.digitalocean.com/products/genai-platform/concepts/best-practices/#agent-instructions) for best practices.
	Instruction any
	K           any
	// Knowledge bases
	KnowledgeBases any
	LoggingConfig  any
	MaxTokens      any
	// MCP (Model Context Protocol) servers attached to this agent
	McpServers any
	// Description of a Model
	Model            any
	ModelProviderKey any
	// Model router
	ModelRouter any
	// Agent name
	Name any
	// OpenAI API Key Info
	OpenaiApiKey any
	// Parent agents
	ParentAgents any
	ProjectId    any
	// Whether the agent should provide in-response citations
	ProvideCitations any
	// The reasoning effort for the agent
	ReasoningEffort any
	// Region code
	Region any
	// - RETRIEVAL_METHOD_UNKNOWN: The retrieval method is unknown - RETRIEVAL_METHOD_REWRITE: The retrieval method is rewrite - RETRIEVAL_METHOD_STEP_BACK: The retrieval method is step back - RETRIEVAL_METHOD_SUB_QUERIES: The retrieval method is sub queries - RETRIEVAL_METHOD_NONE: The retrieval method is none
	RetrievalMethod any
	// Creation of route date / time
	RouteCreatedAt any
	RouteCreatedBy any
	// Route name
	RouteName any
	RouteUuid any
	// Agent tag to organize related resources
	Tags        any
	Temperature any
	// Represents an AgentTemplate entity
	Template any
	// The thinking token budget for Anthropic extended thinking (0 = disabled)
	ThinkingTokenBudget any
	TopP                any
	// Last modified
	UpdatedAt any
	// Access your agent under this url
	Url any
	// Id of user that created the agent
	UserId any
	// Unique agent id
	Uuid any
	// The latest version of the agent
	VersionHash any
	// VPC Egress IPs
	VpcEgressIps any
	VpcUuid      any
	// Whether this agent can use the built-in web_fetch tool.
	WebFetchEnabled any
	// Whether this agent can use the built-in web_search tool.
	WebSearchEnabled any
	Workspace        any
}

var ApiGetAgentOutput_Agent_McpServersFields = ubx.FieldMap{
	"AllowedTools":  ubx.FieldSpec{WireName: "allowed_tools"},
	"Authorization": ubx.FieldSpec{WireName: "authorization"},
	"Headers":       ubx.FieldSpec{WireName: "headers"},
	"ServerLabel":   ubx.FieldSpec{WireName: "server_label"},
	"ServerUrl":     ubx.FieldSpec{WireName: "server_url"},
}

type ApiGetAgentOutputConfig struct {
	// Optional Anthropic API key ID to use with Anthropic models
	AnthropicKeyUuid any
	// A text description of the agent, not used in inference
	Description any
	// Agent instruction. Instructions help your agent to perform its job effectively. See [Write Effective Agent Instructions](https://docs.digitalocean.com/products/genai-platform/concepts/best-practices/#agent-instructions) for best practices.
	Instruction any
	// Ids of the knowledge base(s) to attach to the agent
	KnowledgeBaseUuid any
	// MCP (Model Context Protocol) servers to attach to the agent
	McpServers           any
	ModelProviderKeyUuid any
	ModelRouterUuid      any
	// Identifier for the foundation model.
	ModelUuid any
	// Agent name
	Name any
	// Optional OpenAI API key ID to use with OpenAI models
	OpenAiKeyUuid any
	// The id of the DigitalOcean project this agent will belong to
	ProjectId       any
	ReasoningEffort any
	// The DigitalOcean region to deploy your agent in
	Region           any
	RouterPresetSlug any
	// Agent tag to organize related resources
	Tags                any
	ThinkingTokenBudget any
	// Whether the agent can use the built-in web_fetch tool to retrieve content from public web pages.
	WebFetchEnabled any
	// Whether the agent can use the built-in web_search tool to search the public web for current information.
	WebSearchEnabled any
	// Identifier for the workspace
	WorkspaceUuid any
	// path parameter, not part of the API's own resource representation
	Uuid any
}

type ApiGetAgentOutputAttrs struct {
	// An Agent
	Agent any
	// Optional Anthropic API key ID to use with Anthropic models
	AnthropicKeyUuid any
	// A text description of the agent, not used in inference
	Description any
	// Agent instruction. Instructions help your agent to perform its job effectively. See [Write Effective Agent Instructions](https://docs.digitalocean.com/products/genai-platform/concepts/best-practices/#agent-instructions) for best practices.
	Instruction any
	// Ids of the knowledge base(s) to attach to the agent
	KnowledgeBaseUuid any
	// MCP (Model Context Protocol) servers to attach to the agent
	McpServers           any
	ModelProviderKeyUuid any
	ModelRouterUuid      any
	// Identifier for the foundation model.
	ModelUuid any
	// Agent name
	Name any
	// Optional OpenAI API key ID to use with OpenAI models
	OpenAiKeyUuid any
	// The id of the DigitalOcean project this agent will belong to
	ProjectId       any
	ReasoningEffort any
	// The DigitalOcean region to deploy your agent in
	Region           any
	RouterPresetSlug any
	// Agent tag to organize related resources
	Tags                any
	ThinkingTokenBudget any
	// Whether the agent can use the built-in web_fetch tool to retrieve content from public web pages.
	WebFetchEnabled any
	// Whether the agent can use the built-in web_search tool to search the public web for current information.
	WebSearchEnabled any
	// Identifier for the workspace
	WorkspaceUuid any
	// path parameter, not part of the API's own resource representation
	Uuid any
}

var ApiGetAgentOutput = ubx.ResourceBinding{
	WireType: "digitalocean_api_get_agent_output",
	Fields: ubx.FieldMap{
		"AnthropicKeyUuid":  ubx.FieldSpec{WireName: "anthropic_key_uuid"},
		"Description":       ubx.FieldSpec{WireName: "description"},
		"Instruction":       ubx.FieldSpec{WireName: "instruction"},
		"KnowledgeBaseUuid": ubx.FieldSpec{WireName: "knowledge_base_uuid"},
		"McpServers": ubx.FieldSpec{
			WireName: "mcp_servers",
			Kind:     "list",
			Fields:   ApiGetAgentOutput_Agent_McpServersFields,
		},
		"ModelProviderKeyUuid": ubx.FieldSpec{WireName: "model_provider_key_uuid"},
		"ModelRouterUuid":      ubx.FieldSpec{WireName: "model_router_uuid"},
		"ModelUuid":            ubx.FieldSpec{WireName: "model_uuid"},
		"Name":                 ubx.FieldSpec{WireName: "name"},
		"OpenAiKeyUuid":        ubx.FieldSpec{WireName: "open_ai_key_uuid"},
		"ProjectId":            ubx.FieldSpec{WireName: "project_id"},
		"ReasoningEffort":      ubx.FieldSpec{WireName: "reasoning_effort"},
		"Region":               ubx.FieldSpec{WireName: "region"},
		"RouterPresetSlug":     ubx.FieldSpec{WireName: "router_preset_slug"},
		"Tags":                 ubx.FieldSpec{WireName: "tags"},
		"ThinkingTokenBudget":  ubx.FieldSpec{WireName: "thinking_token_budget"},
		"WebFetchEnabled":      ubx.FieldSpec{WireName: "web_fetch_enabled"},
		"WebSearchEnabled":     ubx.FieldSpec{WireName: "web_search_enabled"},
		"WorkspaceUuid":        ubx.FieldSpec{WireName: "workspace_uuid"},
		"Uuid":                 ubx.FieldSpec{WireName: "uuid"},
	},
}
