// Code generated by `ubx sdk gen` from digitalocean_kafka_schema_verbose. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface SchemaVerbose_Subjects {
  schema?: string | Computed<string>;
  schemaId?: number | Computed<number>;
  schemaType?: string | Computed<string>;
  subjectName?: string | Computed<string>;
}

export interface SchemaVerboseConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface SchemaVerboseAttrs {
  databaseClusterUuid: string;
  subjects: SchemaVerbose_Subjects[];
}

export const SchemaVerbose: DataSourceBinding<SchemaVerboseConfig, SchemaVerboseAttrs> = {
  wireType: "digitalocean_kafka_schema_verbose",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
