# Code generated by `ubx sdk gen` from digitalocean_neighbor_ids. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class IdsConfig:
    pass

@dataclasses.dataclass
class IdsAttrs:
    # An array of arrays. Each array will contain a set of Droplet IDs for Droplets that share a physical server.
    neighbor_ids: Any = None

Ids = ubx.DataSourceBinding(
    wire_type="digitalocean_neighbor_ids",
    fields={
    },
)
