// Code generated by `ubx sdk gen` from digitalocean_app_response. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Response_App_ActiveDeployment_Functions {
  name?: string | Computed<string>;
  namespace?: string | Computed<string>;
  sourceCommitHash?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Jobs {
  name?: string | Computed<string>;
  sourceCommitHash?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Progress_Steps_Reason {
  code?: string | Computed<string>;
  message?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Progress_Steps {
  componentName?: string | Computed<string>;
  endedAt?: string | Computed<string>;
  messageBase?: string | Computed<string>;
  name?: string | Computed<string>;
  reason?: Response_App_ActiveDeployment_Progress_Steps_Reason | Computed<Response_App_ActiveDeployment_Progress_Steps_Reason>;
  startedAt?: string | Computed<string>;
  status?: string | Computed<string>;
  steps?: unknown[] | Computed<unknown[]>;
}

export interface Response_App_ActiveDeployment_Progress {
  errorSteps?: number | Computed<number>;
  pendingSteps?: number | Computed<number>;
  runningSteps?: number | Computed<number>;
  steps?: Response_App_ActiveDeployment_Progress_Steps[] | Computed<Response_App_ActiveDeployment_Progress_Steps[]>;
  successSteps?: number | Computed<number>;
  summarySteps?: Response_App_ActiveDeployment_Progress_Steps[] | Computed<Response_App_ActiveDeployment_Progress_Steps[]>;
  totalSteps?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Databases {
  clusterName?: string | Computed<string>;
  dbName?: string | Computed<string>;
  dbUser?: string | Computed<string>;
  engine?: string | Computed<string>;
  name?: string | Computed<string>;
  production?: boolean | Computed<boolean>;
  version?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Domains {
  domain?: string | Computed<string>;
  minimumTlsVersion?: string | Computed<string>;
  type?: string | Computed<string>;
  wildcard?: boolean | Computed<boolean>;
  zone?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Egress {
  type?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Alerts {
  disabled?: boolean | Computed<boolean>;
  operator?: string | Computed<string>;
  rule?: string | Computed<string>;
  value?: number | Computed<number>;
  window?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Bitbucket {
  branch?: string | Computed<string>;
  deployOnPush?: boolean | Computed<boolean>;
  repo?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Cors_AllowOrigins {
  exact?: string | Computed<string>;
  prefix?: string | Computed<string>;
  regex?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Cors {
  allowCredentials?: boolean | Computed<boolean>;
  allowHeaders?: string[] | Computed<string[]>;
  allowMethods?: string[] | Computed<string[]>;
  allowOrigins?: Response_App_ActiveDeployment_Spec_Functions_Cors_AllowOrigins[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Cors_AllowOrigins[]>;
  exposeHeaders?: string[] | Computed<string[]>;
  maxAge?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Envs {
  key?: string | Computed<string>;
  scope?: string | Computed<string>;
  type?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Git {
  branch?: string | Computed<string>;
  repoCloneUrl?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Datadog {
  apiKey?: string | Computed<string>;
  endpoint?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Logtail {
  token?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch_BasicAuth {
  password?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch {
  basicAuth?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch_BasicAuth | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch_BasicAuth>;
  clusterName?: string | Computed<string>;
  endpoint?: string | Computed<string>;
  indexName?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Papertrail {
  endpoint?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_LogDestinations {
  datadog?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Datadog | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Datadog>;
  logtail?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Logtail | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Logtail>;
  name?: string | Computed<string>;
  openSearch?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch>;
  papertrail?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Papertrail | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations_Papertrail>;
}

export interface Response_App_ActiveDeployment_Spec_Functions_Routes {
  path?: string | Computed<string>;
  preservePathPrefix?: boolean | Computed<boolean>;
}

export interface Response_App_ActiveDeployment_Spec_Functions {
  alerts?: Response_App_ActiveDeployment_Spec_Functions_Alerts[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Alerts[]>;
  bitbucket?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  cors?: Response_App_ActiveDeployment_Spec_Functions_Cors | Computed<Response_App_ActiveDeployment_Spec_Functions_Cors>;
  envs?: Response_App_ActiveDeployment_Spec_Functions_Envs[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Envs[]>;
  git?: Response_App_ActiveDeployment_Spec_Functions_Git | Computed<Response_App_ActiveDeployment_Spec_Functions_Git>;
  github?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  gitlab?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  logDestinations?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations[] | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations[]>;
  name?: string | Computed<string>;
  routes?: Response_App_ActiveDeployment_Spec_Functions_Routes[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Routes[]>;
  sourceDir?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress_Rules_Component {
  name?: string | Computed<string>;
  preservePathPrefix?: string | Computed<string>;
  rewrite?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_Authority {
  exact?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_Path {
  prefix?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress_Rules_Match {
  authority?: Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_Authority | Computed<Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_Authority>;
  path?: Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_Path | Computed<Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_Path>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress_Rules_Redirect {
  authority?: string | Computed<string>;
  port?: number | Computed<number>;
  redirectCode?: number | Computed<number>;
  scheme?: string | Computed<string>;
  uri?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress_Rules {
  component?: Response_App_ActiveDeployment_Spec_Ingress_Rules_Component | Computed<Response_App_ActiveDeployment_Spec_Ingress_Rules_Component>;
  cors?: Response_App_ActiveDeployment_Spec_Functions_Cors | Computed<Response_App_ActiveDeployment_Spec_Functions_Cors>;
  match?: Response_App_ActiveDeployment_Spec_Ingress_Rules_Match | Computed<Response_App_ActiveDeployment_Spec_Ingress_Rules_Match>;
  redirect?: Response_App_ActiveDeployment_Spec_Ingress_Rules_Redirect | Computed<Response_App_ActiveDeployment_Spec_Ingress_Rules_Redirect>;
}

export interface Response_App_ActiveDeployment_Spec_Ingress {
  /** Optional HTTPS URL of a custom error page to display when the app is unreachable. The page is shown in a full-viewport iframe. The target must allow framing: avoid `X-Frame-Options: DENY` and a restrictive `Content-Security-Policy` `frame-ancestors` that blocks the platform. If omitted, the default platform error page is used. */
  customErrorPageUrl?: string | Computed<string>;
  /** Rules for configuring HTTP ingress for component routes, CORS, rewrites, and redirects. */
  rules?: Response_App_ActiveDeployment_Spec_Ingress_Rules[] | Computed<Response_App_ActiveDeployment_Spec_Ingress_Rules[]>;
}

export interface Response_App_ActiveDeployment_Spec_Jobs_Image_DeployOnPush {
  enabled?: boolean | Computed<boolean>;
}

export interface Response_App_ActiveDeployment_Spec_Jobs_Image {
  deployOnPush?: Response_App_ActiveDeployment_Spec_Jobs_Image_DeployOnPush | Computed<Response_App_ActiveDeployment_Spec_Jobs_Image_DeployOnPush>;
  digest?: string | Computed<string>;
  registry?: string | Computed<string>;
  registryCredentials?: string | Computed<string>;
  registryType?: string | Computed<string>;
  repository?: string | Computed<string>;
  tag?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Jobs_Termination {
  gracePeriodSeconds?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Jobs {
  bitbucket?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  buildCommand?: string | Computed<string>;
  dockerfilePath?: string | Computed<string>;
  environmentSlug?: string | Computed<string>;
  envs?: Response_App_ActiveDeployment_Spec_Functions_Envs[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Envs[]>;
  git?: Response_App_ActiveDeployment_Spec_Functions_Git | Computed<Response_App_ActiveDeployment_Spec_Functions_Git>;
  github?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  gitlab?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  image?: Response_App_ActiveDeployment_Spec_Jobs_Image | Computed<Response_App_ActiveDeployment_Spec_Jobs_Image>;
  instanceCount?: number | Computed<number>;
  instanceSizeSlug?: string | Computed<string>;
  kind?: string | Computed<string>;
  logDestinations?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations[] | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations[]>;
  name?: string | Computed<string>;
  runCommand?: string | Computed<string>;
  sourceDir?: string | Computed<string>;
  termination?: Response_App_ActiveDeployment_Spec_Jobs_Termination | Computed<Response_App_ActiveDeployment_Spec_Jobs_Termination>;
}

export interface Response_App_ActiveDeployment_Spec_Maintenance {
  /** Indicates whether the app should be archived. Setting this to true implies that enabled is set to true. */
  archive?: boolean | Computed<boolean>;
  /** Indicates whether maintenance mode should be enabled for the app. */
  enabled?: boolean | Computed<boolean>;
  /** A custom offline page to display when maintenance mode is enabled or the app is archived. */
  offlinePageUrl?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestDuration {
  p95Milliseconds?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestsPerSecond {
  perInstance?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics {
  requestDuration?: Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestDuration | Computed<Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestDuration>;
  requestsPerSecond?: Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestsPerSecond | Computed<Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestsPerSecond>;
}

export interface Response_App_ActiveDeployment_Spec_Services_Autoscaling {
  maxInstanceCount?: number | Computed<number>;
  metrics?: Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics | Computed<Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics>;
  minInstanceCount?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Services_HealthCheck {
  failureThreshold?: number | Computed<number>;
  httpPath?: string | Computed<string>;
  initialDelaySeconds?: number | Computed<number>;
  periodSeconds?: number | Computed<number>;
  port?: number | Computed<number>;
  successThreshold?: number | Computed<number>;
  timeoutSeconds?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Services_Termination {
  drainSeconds?: number | Computed<number>;
  gracePeriodSeconds?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Services {
  autoscaling?: Response_App_ActiveDeployment_Spec_Services_Autoscaling | Computed<Response_App_ActiveDeployment_Spec_Services_Autoscaling>;
  bitbucket?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  buildCommand?: string | Computed<string>;
  cors?: Response_App_ActiveDeployment_Spec_Functions_Cors | Computed<Response_App_ActiveDeployment_Spec_Functions_Cors>;
  dockerfilePath?: string | Computed<string>;
  environmentSlug?: string | Computed<string>;
  envs?: Response_App_ActiveDeployment_Spec_Functions_Envs[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Envs[]>;
  git?: Response_App_ActiveDeployment_Spec_Functions_Git | Computed<Response_App_ActiveDeployment_Spec_Functions_Git>;
  github?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  gitlab?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  healthCheck?: Response_App_ActiveDeployment_Spec_Services_HealthCheck | Computed<Response_App_ActiveDeployment_Spec_Services_HealthCheck>;
  httpPort?: number | Computed<number>;
  image?: Response_App_ActiveDeployment_Spec_Jobs_Image | Computed<Response_App_ActiveDeployment_Spec_Jobs_Image>;
  instanceCount?: number | Computed<number>;
  instanceSizeSlug?: string | Computed<string>;
  internalPorts?: number[] | Computed<number[]>;
  livenessHealthCheck?: Response_App_ActiveDeployment_Spec_Services_HealthCheck | Computed<Response_App_ActiveDeployment_Spec_Services_HealthCheck>;
  logDestinations?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations[] | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations[]>;
  name?: string | Computed<string>;
  protocol?: string | Computed<string>;
  routes?: Response_App_ActiveDeployment_Spec_Functions_Routes[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Routes[]>;
  runCommand?: string | Computed<string>;
  sourceDir?: string | Computed<string>;
  termination?: Response_App_ActiveDeployment_Spec_Services_Termination | Computed<Response_App_ActiveDeployment_Spec_Services_Termination>;
}

export interface Response_App_ActiveDeployment_Spec_StaticSites {
  bitbucket?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  buildCommand?: string | Computed<string>;
  catchallDocument?: string | Computed<string>;
  cors?: Response_App_ActiveDeployment_Spec_Functions_Cors | Computed<Response_App_ActiveDeployment_Spec_Functions_Cors>;
  dockerfilePath?: string | Computed<string>;
  environmentSlug?: string | Computed<string>;
  envs?: Response_App_ActiveDeployment_Spec_Functions_Envs[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Envs[]>;
  errorDocument?: string | Computed<string>;
  git?: Response_App_ActiveDeployment_Spec_Functions_Git | Computed<Response_App_ActiveDeployment_Spec_Functions_Git>;
  github?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  gitlab?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  image?: Response_App_ActiveDeployment_Spec_Jobs_Image | Computed<Response_App_ActiveDeployment_Spec_Jobs_Image>;
  indexDocument?: string | Computed<string>;
  logDestinations?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations[] | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations[]>;
  name?: string | Computed<string>;
  outputDir?: string | Computed<string>;
  routes?: Response_App_ActiveDeployment_Spec_Functions_Routes[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Routes[]>;
  runCommand?: string | Computed<string>;
  sourceDir?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Vpc_EgressIps {
  ip?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Vpc {
  egressIps?: Response_App_ActiveDeployment_Spec_Vpc_EgressIps[] | Computed<Response_App_ActiveDeployment_Spec_Vpc_EgressIps[]>;
  id?: string | Computed<string>;
}

export interface Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics_Cpu {
  percent?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics {
  cpu?: Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics_Cpu | Computed<Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics_Cpu>;
}

export interface Response_App_ActiveDeployment_Spec_Workers_Autoscaling {
  maxInstanceCount?: number | Computed<number>;
  metrics?: Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics | Computed<Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics>;
  minInstanceCount?: number | Computed<number>;
}

export interface Response_App_ActiveDeployment_Spec_Workers {
  autoscaling?: Response_App_ActiveDeployment_Spec_Workers_Autoscaling | Computed<Response_App_ActiveDeployment_Spec_Workers_Autoscaling>;
  bitbucket?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  buildCommand?: string | Computed<string>;
  dockerfilePath?: string | Computed<string>;
  environmentSlug?: string | Computed<string>;
  envs?: Response_App_ActiveDeployment_Spec_Functions_Envs[] | Computed<Response_App_ActiveDeployment_Spec_Functions_Envs[]>;
  git?: Response_App_ActiveDeployment_Spec_Functions_Git | Computed<Response_App_ActiveDeployment_Spec_Functions_Git>;
  github?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  gitlab?: Response_App_ActiveDeployment_Spec_Functions_Bitbucket | Computed<Response_App_ActiveDeployment_Spec_Functions_Bitbucket>;
  image?: Response_App_ActiveDeployment_Spec_Jobs_Image | Computed<Response_App_ActiveDeployment_Spec_Jobs_Image>;
  instanceCount?: number | Computed<number>;
  instanceSizeSlug?: string | Computed<string>;
  livenessHealthCheck?: Response_App_ActiveDeployment_Spec_Services_HealthCheck | Computed<Response_App_ActiveDeployment_Spec_Services_HealthCheck>;
  logDestinations?: Response_App_ActiveDeployment_Spec_Functions_LogDestinations[] | Computed<Response_App_ActiveDeployment_Spec_Functions_LogDestinations[]>;
  name?: string | Computed<string>;
  runCommand?: string | Computed<string>;
  sourceDir?: string | Computed<string>;
  termination?: Response_App_ActiveDeployment_Spec_Jobs_Termination | Computed<Response_App_ActiveDeployment_Spec_Jobs_Termination>;
}

export interface Response_App_ActiveDeployment_Spec {
  /** Database instances which can provide persistence to workloads within the application. */
  databases?: Response_App_ActiveDeployment_Spec_Databases[] | Computed<Response_App_ActiveDeployment_Spec_Databases[]>;
  /** If set to `true`, the app will **not** be cached at the edge (CDN). Enable this option if you want to manage CDN configuration yourself—whether by using an external CDN provider or by handling static content and caching within your app. This setting is also recommended for apps that require real-time data or serve dynamic content, such as those using Server-Sent Events (SSE) over GET, or hosting an MCP (Model Context Protocol) Server that utilizes SSE. **Note:** This feature is not available for static site components. For more information, see [Disable CDN Cache](https://docs.digitalocean.com/products/app-platform/how-to/cache-content/#disable-cdn-cache). */
  disableEdgeCache?: boolean | Computed<boolean>;
  /** If set to `true`, email addresses in the app will not be obfuscated. This is useful for apps that require email addresses to be visible (in the HTML markup). */
  disableEmailObfuscation?: boolean | Computed<boolean>;
  /** A set of hostnames where the application will be available. */
  domains?: Response_App_ActiveDeployment_Spec_Domains[] | Computed<Response_App_ActiveDeployment_Spec_Domains[]>;
  /** Specification for app egress configurations. */
  egress?: Response_App_ActiveDeployment_Spec_Egress | Computed<Response_App_ActiveDeployment_Spec_Egress>;
  /** If set to `true`, suspicious requests will go through additional security checks to help mitigate layer 7 DDoS attacks. */
  enhancedThreatControlEnabled?: boolean | Computed<boolean>;
  /** Workloads which expose publicly-accessible HTTP services via Functions Components. */
  functions?: Response_App_ActiveDeployment_Spec_Functions[] | Computed<Response_App_ActiveDeployment_Spec_Functions[]>;
  /** Specification for app ingress configurations. */
  ingress?: Response_App_ActiveDeployment_Spec_Ingress | Computed<Response_App_ActiveDeployment_Spec_Ingress>;
  /** Pre and post deployment workloads which do not expose publicly-accessible HTTP routes. */
  jobs?: Response_App_ActiveDeployment_Spec_Jobs[] | Computed<Response_App_ActiveDeployment_Spec_Jobs[]>;
  /** Specification to configure maintenance settings for the app, such as maintenance mode and archiving the app. */
  maintenance?: Response_App_ActiveDeployment_Spec_Maintenance | Computed<Response_App_ActiveDeployment_Spec_Maintenance>;
  /** The name of the app. Must be unique across all apps in the same account. */
  name: string | Computed<string>;
  /** The slug form of the geographical origin of the app. Default: `nearest available` */
  region?: string | Computed<string>;
  /** Workloads which expose publicly-accessible HTTP services. */
  services?: Response_App_ActiveDeployment_Spec_Services[] | Computed<Response_App_ActiveDeployment_Spec_Services[]>;
  /** Content which can be rendered to static web assets. */
  staticSites?: Response_App_ActiveDeployment_Spec_StaticSites[] | Computed<Response_App_ActiveDeployment_Spec_StaticSites[]>;
  vpc?: Response_App_ActiveDeployment_Spec_Vpc | Computed<Response_App_ActiveDeployment_Spec_Vpc>;
  /** Workloads which do not expose publicly-accessible HTTP services. */
  workers?: Response_App_ActiveDeployment_Spec_Workers[] | Computed<Response_App_ActiveDeployment_Spec_Workers[]>;
}

export interface Response_App_ActiveDeployment {
  cause?: string | Computed<string>;
  clonedFrom?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  functions?: Response_App_ActiveDeployment_Functions[] | Computed<Response_App_ActiveDeployment_Functions[]>;
  id?: string | Computed<string>;
  jobs?: Response_App_ActiveDeployment_Jobs[] | Computed<Response_App_ActiveDeployment_Jobs[]>;
  phase?: string | Computed<string>;
  phaseLastUpdatedAt?: string | Computed<string>;
  progress?: Response_App_ActiveDeployment_Progress | Computed<Response_App_ActiveDeployment_Progress>;
  services?: Response_App_ActiveDeployment_Jobs[] | Computed<Response_App_ActiveDeployment_Jobs[]>;
  /** The desired configuration of an application. */
  spec?: Response_App_ActiveDeployment_Spec | Computed<Response_App_ActiveDeployment_Spec>;
  staticSites?: Response_App_ActiveDeployment_Jobs[] | Computed<Response_App_ActiveDeployment_Jobs[]>;
  tierSlug?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  workers?: Response_App_ActiveDeployment_Jobs[] | Computed<Response_App_ActiveDeployment_Jobs[]>;
}

export interface Response_App_DedicatedIps {
  id?: string | Computed<string>;
  ip?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface Response_App_Domains_Progress {
  steps?: unknown[] | Computed<unknown[]>;
}

export interface Response_App_Domains_Validations {
  txtName?: string | Computed<string>;
  txtValue?: string | Computed<string>;
}

export interface Response_App_Domains {
  certificateExpiresAt?: string | Computed<string>;
  id?: string | Computed<string>;
  phase?: string | Computed<string>;
  progress?: Response_App_Domains_Progress | Computed<Response_App_Domains_Progress>;
  rotateValidationRecords?: boolean | Computed<boolean>;
  spec?: Response_App_ActiveDeployment_Spec_Domains | Computed<Response_App_ActiveDeployment_Spec_Domains>;
  validations?: Response_App_Domains_Validations[] | Computed<Response_App_Domains_Validations[]>;
}

export interface Response_App_Region {
  continent?: string | Computed<string>;
  dataCenters?: string[] | Computed<string[]>;
  /** Whether or not the region is presented as the default. */
  default?: boolean | Computed<boolean>;
  disabled?: boolean | Computed<boolean>;
  flag?: string | Computed<string>;
  label?: string | Computed<string>;
  reason?: string | Computed<string>;
  slug?: string | Computed<string>;
}

export interface Response_App {
  activeDeployment?: Response_App_ActiveDeployment | Computed<Response_App_ActiveDeployment>;
  createdAt?: string | Computed<string>;
  dedicatedIps?: Response_App_DedicatedIps[] | Computed<Response_App_DedicatedIps[]>;
  defaultIngress?: string | Computed<string>;
  domains?: Response_App_Domains[] | Computed<Response_App_Domains[]>;
  id?: string | Computed<string>;
  inProgressDeployment?: Response_App_ActiveDeployment | Computed<Response_App_ActiveDeployment>;
  lastDeploymentCreatedAt?: string | Computed<string>;
  liveDomain?: string | Computed<string>;
  liveUrl?: string | Computed<string>;
  liveUrlBase?: string | Computed<string>;
  ownerUuid?: string | Computed<string>;
  pendingDeployment?: Response_App_ActiveDeployment | Computed<Response_App_ActiveDeployment>;
  pinnedDeployment?: Response_App_ActiveDeployment | Computed<Response_App_ActiveDeployment>;
  /** Requires `project:read` scope. */
  projectId?: string | Computed<string>;
  region?: Response_App_Region | Computed<Response_App_Region>;
  /** The desired configuration of an application. */
  spec: Response_App_ActiveDeployment_Spec | Computed<Response_App_ActiveDeployment_Spec>;
  tierSlug?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  vpc?: Response_App_ActiveDeployment_Spec_Vpc | Computed<Response_App_ActiveDeployment_Spec_Vpc>;
}

const Response_App_ActiveDeployment_Spec_DatabasesFields: FieldMap = {
  clusterName: "cluster_name",
  dbName: "db_name",
  dbUser: "db_user",
  engine: "engine",
  name: "name",
  production: "production",
  version: "version",
};

const Response_App_ActiveDeployment_Spec_DomainsFields: FieldMap = {
  domain: "domain",
  minimumTlsVersion: "minimum_tls_version",
  type: "type",
  wildcard: "wildcard",
  zone: "zone",
};

const Response_App_ActiveDeployment_Spec_EgressFields: FieldMap = {
  type: "type",
};

const Response_App_ActiveDeployment_Spec_Functions_AlertsFields: FieldMap = {
  disabled: "disabled",
  operator: "operator",
  rule: "rule",
  value: "value",
  window: "window",
};

const Response_App_ActiveDeployment_Spec_Functions_BitbucketFields: FieldMap = {
  branch: "branch",
  deployOnPush: "deploy_on_push",
  repo: "repo",
};

const Response_App_ActiveDeployment_Spec_Functions_Cors_AllowOriginsFields: FieldMap = {
  exact: "exact",
  prefix: "prefix",
  regex: "regex",
};

const Response_App_ActiveDeployment_Spec_Functions_CorsFields: FieldMap = {
  allowCredentials: "allow_credentials",
  allowHeaders: "allow_headers",
  allowMethods: "allow_methods",
  allowOrigins: {
    wireName: "allow_origins",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_Cors_AllowOriginsFields,
  },
  exposeHeaders: "expose_headers",
  maxAge: "max_age",
};

const Response_App_ActiveDeployment_Spec_Functions_EnvsFields: FieldMap = {
  key: "key",
  scope: "scope",
  type: "type",
  value: "value",
};

const Response_App_ActiveDeployment_Spec_Functions_GitFields: FieldMap = {
  branch: "branch",
  repoCloneUrl: "repo_clone_url",
};

const Response_App_ActiveDeployment_Spec_Functions_LogDestinations_DatadogFields: FieldMap = {
  apiKey: "api_key",
  endpoint: "endpoint",
};

const Response_App_ActiveDeployment_Spec_Functions_LogDestinations_LogtailFields: FieldMap = {
  token: "token",
};

const Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch_BasicAuthFields: FieldMap = {
  password: "password",
  user: "user",
};

const Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearchFields: FieldMap = {
  basicAuth: {
    wireName: "basic_auth",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearch_BasicAuthFields,
  },
  clusterName: "cluster_name",
  endpoint: "endpoint",
  indexName: "index_name",
};

const Response_App_ActiveDeployment_Spec_Functions_LogDestinations_PapertrailFields: FieldMap = {
  endpoint: "endpoint",
};

const Response_App_ActiveDeployment_Spec_Functions_LogDestinationsFields: FieldMap = {
  datadog: {
    wireName: "datadog",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_DatadogFields,
  },
  logtail: {
    wireName: "logtail",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_LogtailFields,
  },
  name: "name",
  openSearch: {
    wireName: "open_search",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_OpenSearchFields,
  },
  papertrail: {
    wireName: "papertrail",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinations_PapertrailFields,
  },
};

const Response_App_ActiveDeployment_Spec_Functions_RoutesFields: FieldMap = {
  path: "path",
  preservePathPrefix: "preserve_path_prefix",
};

const Response_App_ActiveDeployment_Spec_FunctionsFields: FieldMap = {
  alerts: {
    wireName: "alerts",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_AlertsFields,
  },
  bitbucket: {
    wireName: "bitbucket",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  cors: {
    wireName: "cors",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_CorsFields,
  },
  envs: {
    wireName: "envs",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_EnvsFields,
  },
  git: {
    wireName: "git",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_GitFields,
  },
  github: {
    wireName: "github",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  gitlab: {
    wireName: "gitlab",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  logDestinations: {
    wireName: "log_destinations",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinationsFields,
  },
  name: "name",
  routes: {
    wireName: "routes",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_RoutesFields,
  },
  sourceDir: "source_dir",
};

const Response_App_ActiveDeployment_Spec_Ingress_Rules_ComponentFields: FieldMap = {
  name: "name",
  preservePathPrefix: "preserve_path_prefix",
  rewrite: "rewrite",
};

const Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_AuthorityFields: FieldMap = {
  exact: "exact",
};

const Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_PathFields: FieldMap = {
  prefix: "prefix",
};

const Response_App_ActiveDeployment_Spec_Ingress_Rules_MatchFields: FieldMap = {
  authority: {
    wireName: "authority",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_AuthorityFields,
  },
  path: {
    wireName: "path",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Ingress_Rules_Match_PathFields,
  },
};

const Response_App_ActiveDeployment_Spec_Ingress_Rules_RedirectFields: FieldMap = {
  authority: "authority",
  port: "port",
  redirectCode: "redirect_code",
  scheme: "scheme",
  uri: "uri",
};

const Response_App_ActiveDeployment_Spec_Ingress_RulesFields: FieldMap = {
  component: {
    wireName: "component",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Ingress_Rules_ComponentFields,
  },
  cors: {
    wireName: "cors",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_CorsFields,
  },
  match: {
    wireName: "match",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Ingress_Rules_MatchFields,
  },
  redirect: {
    wireName: "redirect",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Ingress_Rules_RedirectFields,
  },
};

const Response_App_ActiveDeployment_Spec_IngressFields: FieldMap = {
  customErrorPageUrl: "custom_error_page_url",
  rules: {
    wireName: "rules",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Ingress_RulesFields,
  },
};

const Response_App_ActiveDeployment_Spec_Jobs_Image_DeployOnPushFields: FieldMap = {
  enabled: "enabled",
};

const Response_App_ActiveDeployment_Spec_Jobs_ImageFields: FieldMap = {
  deployOnPush: {
    wireName: "deploy_on_push",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_Image_DeployOnPushFields,
  },
  digest: "digest",
  registry: "registry",
  registryCredentials: "registry_credentials",
  registryType: "registry_type",
  repository: "repository",
  tag: "tag",
};

const Response_App_ActiveDeployment_Spec_Jobs_TerminationFields: FieldMap = {
  gracePeriodSeconds: "grace_period_seconds",
};

const Response_App_ActiveDeployment_Spec_JobsFields: FieldMap = {
  bitbucket: {
    wireName: "bitbucket",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  buildCommand: "build_command",
  dockerfilePath: "dockerfile_path",
  environmentSlug: "environment_slug",
  envs: {
    wireName: "envs",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_EnvsFields,
  },
  git: {
    wireName: "git",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_GitFields,
  },
  github: {
    wireName: "github",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  gitlab: {
    wireName: "gitlab",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  image: {
    wireName: "image",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_ImageFields,
  },
  instanceCount: "instance_count",
  instanceSizeSlug: "instance_size_slug",
  kind: "kind",
  logDestinations: {
    wireName: "log_destinations",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinationsFields,
  },
  name: "name",
  runCommand: "run_command",
  sourceDir: "source_dir",
  termination: {
    wireName: "termination",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_TerminationFields,
  },
};

const Response_App_ActiveDeployment_Spec_MaintenanceFields: FieldMap = {
  archive: "archive",
  enabled: "enabled",
  offlinePageUrl: "offline_page_url",
};

const Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestDurationFields: FieldMap = {
  p95Milliseconds: "p95_milliseconds",
};

const Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestsPerSecondFields: FieldMap = {
  perInstance: "per_instance",
};

const Response_App_ActiveDeployment_Spec_Services_Autoscaling_MetricsFields: FieldMap = {
  requestDuration: {
    wireName: "request_duration",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestDurationFields,
  },
  requestsPerSecond: {
    wireName: "requests_per_second",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_Autoscaling_Metrics_RequestsPerSecondFields,
  },
};

const Response_App_ActiveDeployment_Spec_Services_AutoscalingFields: FieldMap = {
  maxInstanceCount: "max_instance_count",
  metrics: {
    wireName: "metrics",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_Autoscaling_MetricsFields,
  },
  minInstanceCount: "min_instance_count",
};

const Response_App_ActiveDeployment_Spec_Services_HealthCheckFields: FieldMap = {
  failureThreshold: "failure_threshold",
  httpPath: "http_path",
  initialDelaySeconds: "initial_delay_seconds",
  periodSeconds: "period_seconds",
  port: "port",
  successThreshold: "success_threshold",
  timeoutSeconds: "timeout_seconds",
};

const Response_App_ActiveDeployment_Spec_Services_TerminationFields: FieldMap = {
  drainSeconds: "drain_seconds",
  gracePeriodSeconds: "grace_period_seconds",
};

const Response_App_ActiveDeployment_Spec_ServicesFields: FieldMap = {
  autoscaling: {
    wireName: "autoscaling",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_AutoscalingFields,
  },
  bitbucket: {
    wireName: "bitbucket",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  buildCommand: "build_command",
  cors: {
    wireName: "cors",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_CorsFields,
  },
  dockerfilePath: "dockerfile_path",
  environmentSlug: "environment_slug",
  envs: {
    wireName: "envs",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_EnvsFields,
  },
  git: {
    wireName: "git",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_GitFields,
  },
  github: {
    wireName: "github",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  gitlab: {
    wireName: "gitlab",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  healthCheck: {
    wireName: "health_check",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_HealthCheckFields,
  },
  httpPort: "http_port",
  image: {
    wireName: "image",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_ImageFields,
  },
  instanceCount: "instance_count",
  instanceSizeSlug: "instance_size_slug",
  internalPorts: "internal_ports",
  livenessHealthCheck: {
    wireName: "liveness_health_check",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_HealthCheckFields,
  },
  logDestinations: {
    wireName: "log_destinations",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinationsFields,
  },
  name: "name",
  protocol: "protocol",
  routes: {
    wireName: "routes",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_RoutesFields,
  },
  runCommand: "run_command",
  sourceDir: "source_dir",
  termination: {
    wireName: "termination",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_TerminationFields,
  },
};

const Response_App_ActiveDeployment_Spec_StaticSitesFields: FieldMap = {
  bitbucket: {
    wireName: "bitbucket",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  buildCommand: "build_command",
  catchallDocument: "catchall_document",
  cors: {
    wireName: "cors",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_CorsFields,
  },
  dockerfilePath: "dockerfile_path",
  environmentSlug: "environment_slug",
  envs: {
    wireName: "envs",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_EnvsFields,
  },
  errorDocument: "error_document",
  git: {
    wireName: "git",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_GitFields,
  },
  github: {
    wireName: "github",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  gitlab: {
    wireName: "gitlab",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  image: {
    wireName: "image",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_ImageFields,
  },
  indexDocument: "index_document",
  logDestinations: {
    wireName: "log_destinations",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinationsFields,
  },
  name: "name",
  outputDir: "output_dir",
  routes: {
    wireName: "routes",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_RoutesFields,
  },
  runCommand: "run_command",
  sourceDir: "source_dir",
};

const Response_App_ActiveDeployment_Spec_Vpc_EgressIpsFields: FieldMap = {
  ip: "ip",
};

const Response_App_ActiveDeployment_Spec_VpcFields: FieldMap = {
  egressIps: {
    wireName: "egress_ips",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Vpc_EgressIpsFields,
  },
  id: "id",
};

const Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics_CpuFields: FieldMap = {
  percent: "percent",
};

const Response_App_ActiveDeployment_Spec_Workers_Autoscaling_MetricsFields: FieldMap = {
  cpu: {
    wireName: "cpu",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Workers_Autoscaling_Metrics_CpuFields,
  },
};

const Response_App_ActiveDeployment_Spec_Workers_AutoscalingFields: FieldMap = {
  maxInstanceCount: "max_instance_count",
  metrics: {
    wireName: "metrics",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Workers_Autoscaling_MetricsFields,
  },
  minInstanceCount: "min_instance_count",
};

const Response_App_ActiveDeployment_Spec_WorkersFields: FieldMap = {
  autoscaling: {
    wireName: "autoscaling",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Workers_AutoscalingFields,
  },
  bitbucket: {
    wireName: "bitbucket",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  buildCommand: "build_command",
  dockerfilePath: "dockerfile_path",
  environmentSlug: "environment_slug",
  envs: {
    wireName: "envs",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_EnvsFields,
  },
  git: {
    wireName: "git",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_GitFields,
  },
  github: {
    wireName: "github",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  gitlab: {
    wireName: "gitlab",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Functions_BitbucketFields,
  },
  image: {
    wireName: "image",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_ImageFields,
  },
  instanceCount: "instance_count",
  instanceSizeSlug: "instance_size_slug",
  livenessHealthCheck: {
    wireName: "liveness_health_check",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Services_HealthCheckFields,
  },
  logDestinations: {
    wireName: "log_destinations",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_Functions_LogDestinationsFields,
  },
  name: "name",
  runCommand: "run_command",
  sourceDir: "source_dir",
  termination: {
    wireName: "termination",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_Jobs_TerminationFields,
  },
};

const Response_App_ActiveDeployment_SpecFields: FieldMap = {
  databases: {
    wireName: "databases",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_DatabasesFields,
  },
  disableEdgeCache: "disable_edge_cache",
  disableEmailObfuscation: "disable_email_obfuscation",
  domains: {
    wireName: "domains",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_DomainsFields,
  },
  egress: {
    wireName: "egress",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_EgressFields,
  },
  enhancedThreatControlEnabled: "enhanced_threat_control_enabled",
  functions: {
    wireName: "functions",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_FunctionsFields,
  },
  ingress: {
    wireName: "ingress",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_IngressFields,
  },
  jobs: {
    wireName: "jobs",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_JobsFields,
  },
  maintenance: {
    wireName: "maintenance",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_MaintenanceFields,
  },
  name: "name",
  region: "region",
  services: {
    wireName: "services",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_ServicesFields,
  },
  staticSites: {
    wireName: "static_sites",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_StaticSitesFields,
  },
  vpc: {
    wireName: "vpc",
    kind: "object",
    fields: Response_App_ActiveDeployment_Spec_VpcFields,
  },
  workers: {
    wireName: "workers",
    kind: "list",
    fields: Response_App_ActiveDeployment_Spec_WorkersFields,
  },
};

export interface ResponseConfig {
  /** The ID of the project the app should be assigned to. If omitted, it will be assigned to your default project. <br><br>Requires `project:assign_resource` scope. */
  projectId?: string | Computed<string>;
  /** The desired configuration of an application. */
  spec: Response_App_ActiveDeployment_Spec | Computed<Response_App_ActiveDeployment_Spec>;
  /** path parameter, not part of the API's own resource representation */
  id: string | Computed<string>;
}

export interface ResponseAttrs {
  /** An application's configuration and status. */
  app: Response_App;
  /** The ID of the project the app should be assigned to. If omitted, it will be assigned to your default project. <br><br>Requires `project:assign_resource` scope. */
  projectId: string;
  /** The desired configuration of an application. */
  spec: Response_App_ActiveDeployment_Spec;
  /** path parameter, not part of the API's own resource representation */
  id: string;
}

export const Response: ResourceBinding<ResponseConfig, ResponseAttrs> = {
  wireType: "digitalocean_app_response",
  fields: {
    projectId: "project_id",
    spec: {
      wireName: "spec",
      kind: "object",
      fields: Response_App_ActiveDeployment_SpecFields,
    },
    id: "id",
  },
};
