// Code generated by `ubx sdk gen` from digitalocean_resource. DO NOT EDIT.
package projectresources

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Resource_Links struct {
	Pages any
}

type Resource_Meta struct {
	Total any
}

type Resource_Resources_Links struct {
	Self any
}

type Resource_Resources struct {
	AssignedAt any
	Links      any
	Status     any
	Urn        any
}

type ResourceConfig struct {
}

type ResourceAttrs struct {
	Links any
	Meta  any
	// The resources that are assigned to this project. Only resources that you are authorized to see will be returned.
	Resources any
}

var Resource = ubx.DataSourceBinding{
	WireType: "digitalocean_resource",
	Fields:   ubx.FieldMap{},
}
