// Code generated by `ubx sdk gen` from digitalocean_endpoint. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Endpoint_Endpoints {
  certificateId?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  customDomain?: string | Computed<string>;
  endpoint?: string | Computed<string>;
  id?: string | Computed<string>;
  origin?: string | Computed<string>;
  ttl?: number | Computed<number>;
}

export interface Endpoint_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Endpoint_Meta {
  total?: number | Computed<number>;
}

export interface EndpointConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface EndpointAttrs {
  endpoints: Endpoint_Endpoints[];
  links: Endpoint_Links;
  meta: Endpoint_Meta;
  page: number;
  perPage: number;
}

export const Endpoint: DataSourceBinding<EndpointConfig, EndpointAttrs> = {
  wireType: "digitalocean_endpoint",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
