// Code generated by `ubx sdk gen` from digitalocean_attachment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Attachment_Bgp {
  /** BGP Auth Key */
  authKey: string | Computed<string>;
  /** IP of the DO router */
  localRouterIp: string | Computed<string>;
  /** ASN of the peer router */
  peerRouterAsn: number | Computed<number>;
  /** IP of the Naas Provider router */
  peerRouterIp: string | Computed<string>;
}

const Attachment_BgpFields: FieldMap = {
  authKey: "auth_key",
  localRouterIp: "local_router_ip",
  peerRouterAsn: "peer_router_asn",
  peerRouterIp: "peer_router_ip",
};

export interface AttachmentConfig {
  /** Optional BGP configurations */
  bgp?: Attachment_Bgp | Computed<Attachment_Bgp>;
  /** Bandwidth (in Mbps) of the connection. */
  connectionBandwidthInMbps: number | Computed<number>;
  naasProvider: string | Computed<string>;
  /** The name of the partner attachment. Must be unique and may only contain alphanumeric characters, dashes, and periods. */
  name: string | Computed<string>;
  /** Optional associated partner attachment UUID */
  parentUuid?: string | Computed<string>;
  /** Optional redundancy zone for the partner attachment. */
  redundancyZone?: string | Computed<string>;
  /** The region to create the partner attachment. */
  region: string | Computed<string>;
  /** An array of VPCs IDs. */
  vpcIds: string[] | Computed<string[]>;
  /** path parameter, not part of the API's own resource representation */
  paId: string | Computed<string>;
}

export interface AttachmentAttrs {
  /** Optional BGP configurations */
  bgp: Attachment_Bgp;
  /** Bandwidth (in Mbps) of the connection. */
  connectionBandwidthInMbps: number;
  naasProvider: string;
  /** The name of the partner attachment. Must be unique and may only contain alphanumeric characters, dashes, and periods. */
  name: string;
  /** Optional associated partner attachment UUID */
  parentUuid: string;
  /** Optional redundancy zone for the partner attachment. */
  redundancyZone: string;
  /** The region to create the partner attachment. */
  region: string;
  /** An array of VPCs IDs. */
  vpcIds: string[];
  /** path parameter, not part of the API's own resource representation */
  paId: string;
}

export const Attachment: ResourceBinding<AttachmentConfig, AttachmentAttrs> = {
  wireType: "digitalocean_attachment",
  fields: {
    bgp: {
      wireName: "bgp",
      kind: "object",
      fields: Attachment_BgpFields,
    },
    connectionBandwidthInMbps: "connection_bandwidth_in_mbps",
    naasProvider: "naas_provider",
    name: "name",
    parentUuid: "parent_uuid",
    redundancyZone: "redundancy_zone",
    region: "region",
    vpcIds: "vpc_ids",
    paId: "pa_id",
  },
};
