# Code generated by `ubx sdk gen` from digitalocean_project. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Project_Project:
    created_at: Any = None
    description: Any = None
    environment: Any = None
    id: Any = None
    is_default: Any = None
    name: Any = None
    owner_id: Any = None
    owner_uuid: Any = None
    purpose: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class ProjectConfig:
    pass

@dataclasses.dataclass
class ProjectAttrs:
    project: Any = None

Project = ubx.DataSourceBinding(
    wire_type="digitalocean_project",
    fields={
    },
)
