// Code generated by `ubx sdk gen` from digitalocean_api_get_anthropic_apikey_output. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GetAnthropicApikeyOutput_ApiKeyInfo struct {
	// Key creation date
	CreatedAt any
	// Created by user id from DO
	CreatedBy any
	// Key deleted date
	DeletedAt any
	// Name
	Name any
	// Key last updated date
	UpdatedAt any
	// Uuid
	Uuid any
}

type GetAnthropicApikeyOutputConfig struct {
	// Anthropic API key
	ApiKey any
	// Name of the key
	Name any
	// path parameter, not part of the API's own resource representation
	ApiKeyUuid any
}

type GetAnthropicApikeyOutputAttrs struct {
	// Anthropic API key
	ApiKey any
	// Anthropic API Key Info
	ApiKeyInfo any
	// Name of the key
	Name any
	// path parameter, not part of the API's own resource representation
	ApiKeyUuid any
}

var GetAnthropicApikeyOutput = ubx.ResourceBinding{
	WireType: "digitalocean_api_get_anthropic_apikey_output",
	Fields: ubx.FieldMap{
		"ApiKey": ubx.FieldSpec{WireName: "api_key"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ApiKeyUuid": ubx.FieldSpec{WireName: "api_key_uuid"},
	},
}
