// Code generated by `ubx sdk gen` from digitalocean_api_get_knowledge_base_output. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GetKnowledgeBaseOutput_Datasources_AwsDataSource struct {
	BucketName any
	ItemPath any
	KeyId any
	Region any
	SecretKey any
}

type GetKnowledgeBaseOutput_Datasources_ChunkingOptions struct {
	ChildChunkSize any
	MaxChunkSize any
	ParentChunkSize any
	SemanticThreshold any
}

type GetKnowledgeBaseOutput_Datasources_DropboxDataSource struct {
	Folder any
	RefreshToken any
}

type GetKnowledgeBaseOutput_Datasources_FileUploadDataSource struct {
	OriginalFileName any
	SizeInBytes any
	StoredObjectKey any
}

type GetKnowledgeBaseOutput_Datasources_GoogleDriveDataSource struct {
	FolderId any
	RefreshToken any
}

type GetKnowledgeBaseOutput_Datasources_SpacesDataSource struct {
	BucketName any
	ItemPath any
	Region any
}

type GetKnowledgeBaseOutput_Datasources_WebCrawlerDataSource struct {
	BaseUrl any
	CrawlingOption any
	EmbedMedia any
	ExcludeTags any
}

type GetKnowledgeBaseOutput_Datasources struct {
	AwsDataSource any
	BucketName any
	BucketRegion any
	ChunkingAlgorithm any
	ChunkingOptions any
	DropboxDataSource any
	FileUploadDataSource any
	GoogleDriveDataSource any
	ItemPath any
	SpacesDataSource any
	WebCrawlerDataSource any
}

type GetKnowledgeBaseOutput_KnowledgeBase_LastIndexingJob_DataSourceJobs struct {
	CompletedAt any
	DataSourceUuid any
	ErrorDetails any
	ErrorMsg any
	FailedItemCount any
	IndexedFileCount any
	IndexedItemCount any
	RemovedItemCount any
	SkippedItemCount any
	StartedAt any
	Status any
	TotalBytes any
	TotalBytesIndexed any
	TotalFileCount any
}

type GetKnowledgeBaseOutput_KnowledgeBase_LastIndexingJob struct {
	// Number of datasources indexed completed
	CompletedDatasources any
	// Creation date / time
	CreatedAt any
	// Details on Data Sources included in the Indexing Job
	DataSourceJobs any
	DataSourceUuids any
	FinishedAt any
	// Boolean value to determine if the indexing job details are available
	IsReportAvailable any
	// Knowledge base id
	KnowledgeBaseUuid any
	Phase any
	StartedAt any
	Status any
	// Number of tokens [This field is deprecated]
	Tokens any
	// Number of datasources being indexed
	TotalDatasources any
	// Total Tokens Consumed By the Indexing Job
	TotalTokens any
	// Last modified
	UpdatedAt any
	// Unique id
	Uuid any
}

type GetKnowledgeBaseOutput_KnowledgeBase_RerankingConfig struct {
	// Whether reranking is enabled for retrieval
	Enabled any
	// Reranker model internal name
	Model any
}

type GetKnowledgeBaseOutput_KnowledgeBase struct {
	// Time when the knowledge base was added to the agent
	AddedToAgentAt any
	// Creation date / time
	CreatedAt any
	DatabaseId any
	EmbeddingModelUuid any
	// Whether the knowledge base is public or not
	IsPublic any
	// IndexingJob description
	LastIndexingJob any
	// Name of knowledge base
	Name any
	ProjectId any
	// Region code
	Region any
	// Configuration for cross-encoder reranking during retrieval.
	RerankingConfig any
	// Tags to organize related resources
	Tags any
	// Last modified
	UpdatedAt any
	// Id of user that created the knowledge base
	UserId any
	// Unique id for knowledge base
	Uuid any
}

var GetKnowledgeBaseOutput_Datasources_AwsDataSourceFields = ubx.FieldMap{
		"BucketName": ubx.FieldSpec{WireName: "bucket_name"},
		"ItemPath": ubx.FieldSpec{WireName: "item_path"},
		"KeyId": ubx.FieldSpec{WireName: "key_id"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"SecretKey": ubx.FieldSpec{WireName: "secret_key"},
	}

var GetKnowledgeBaseOutput_Datasources_ChunkingOptionsFields = ubx.FieldMap{
		"ChildChunkSize": ubx.FieldSpec{WireName: "child_chunk_size"},
		"MaxChunkSize": ubx.FieldSpec{WireName: "max_chunk_size"},
		"ParentChunkSize": ubx.FieldSpec{WireName: "parent_chunk_size"},
		"SemanticThreshold": ubx.FieldSpec{WireName: "semantic_threshold"},
	}

var GetKnowledgeBaseOutput_Datasources_DropboxDataSourceFields = ubx.FieldMap{
		"Folder": ubx.FieldSpec{WireName: "folder"},
		"RefreshToken": ubx.FieldSpec{WireName: "refresh_token"},
	}

var GetKnowledgeBaseOutput_Datasources_FileUploadDataSourceFields = ubx.FieldMap{
		"OriginalFileName": ubx.FieldSpec{WireName: "original_file_name"},
		"SizeInBytes": ubx.FieldSpec{WireName: "size_in_bytes"},
		"StoredObjectKey": ubx.FieldSpec{WireName: "stored_object_key"},
	}

var GetKnowledgeBaseOutput_Datasources_GoogleDriveDataSourceFields = ubx.FieldMap{
		"FolderId": ubx.FieldSpec{WireName: "folder_id"},
		"RefreshToken": ubx.FieldSpec{WireName: "refresh_token"},
	}

var GetKnowledgeBaseOutput_Datasources_SpacesDataSourceFields = ubx.FieldMap{
		"BucketName": ubx.FieldSpec{WireName: "bucket_name"},
		"ItemPath": ubx.FieldSpec{WireName: "item_path"},
		"Region": ubx.FieldSpec{WireName: "region"},
	}

var GetKnowledgeBaseOutput_Datasources_WebCrawlerDataSourceFields = ubx.FieldMap{
		"BaseUrl": ubx.FieldSpec{WireName: "base_url"},
		"CrawlingOption": ubx.FieldSpec{WireName: "crawling_option"},
		"EmbedMedia": ubx.FieldSpec{WireName: "embed_media"},
		"ExcludeTags": ubx.FieldSpec{WireName: "exclude_tags"},
	}

var GetKnowledgeBaseOutput_DatasourcesFields = ubx.FieldMap{
		"AwsDataSource": ubx.FieldSpec{
			WireName: "aws_data_source",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_AwsDataSourceFields,
		},
		"BucketName": ubx.FieldSpec{WireName: "bucket_name"},
		"BucketRegion": ubx.FieldSpec{WireName: "bucket_region"},
		"ChunkingAlgorithm": ubx.FieldSpec{WireName: "chunking_algorithm"},
		"ChunkingOptions": ubx.FieldSpec{
			WireName: "chunking_options",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_ChunkingOptionsFields,
		},
		"DropboxDataSource": ubx.FieldSpec{
			WireName: "dropbox_data_source",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_DropboxDataSourceFields,
		},
		"FileUploadDataSource": ubx.FieldSpec{
			WireName: "file_upload_data_source",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_FileUploadDataSourceFields,
		},
		"GoogleDriveDataSource": ubx.FieldSpec{
			WireName: "google_drive_data_source",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_GoogleDriveDataSourceFields,
		},
		"ItemPath": ubx.FieldSpec{WireName: "item_path"},
		"SpacesDataSource": ubx.FieldSpec{
			WireName: "spaces_data_source",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_SpacesDataSourceFields,
		},
		"WebCrawlerDataSource": ubx.FieldSpec{
			WireName: "web_crawler_data_source",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_Datasources_WebCrawlerDataSourceFields,
		},
	}

var GetKnowledgeBaseOutput_KnowledgeBase_RerankingConfigFields = ubx.FieldMap{
		"Enabled": ubx.FieldSpec{WireName: "enabled"},
		"Model": ubx.FieldSpec{WireName: "model"},
	}

type GetKnowledgeBaseOutputConfig struct {
	// Identifier of the DigitalOcean OpenSearch database this knowledge base will use, optional. If not provided, we create a new database for the knowledge base in the same region as the knowledge base.
	DatabaseId any
	// Optional data sources to attach at creation. Omit or use an empty list to create the knowledge base without sources, then add sources (with chunking strategy and sizes) using [Add a Data Source to a Knowledge Base](#operation/create_knowledge_base_data_source). When provided, see [Organize Data Sources](https://docs.digitalocean.com/products/gradient-ai-platform/how-to/create-manage-agent-knowledge-bases/#add-data-sources) for best practices.
	Datasources any
	// Identifier for the [embedding model](https://docs.digitalocean.com/products/genai-platform/details/models/#embedding-models).
	EmbeddingModelUuid any
	// Name of the knowledge base.
	Name any
	// Identifier of the DigitalOcean project this knowledge base will belong to.
	ProjectId any
	// The datacenter region to deploy the knowledge base in.
	Region any
	// Configuration for cross-encoder reranking during retrieval.
	RerankingConfig any
	Size any
	// Tags to organize your knowledge base.
	Tags any
	// The VPC to deploy the knowledge base database in
	VpcUuid any
	// path parameter, not part of the API's own resource representation
	Uuid any
}

type GetKnowledgeBaseOutputAttrs struct {
	// Identifier of the DigitalOcean OpenSearch database this knowledge base will use, optional. If not provided, we create a new database for the knowledge base in the same region as the knowledge base.
	DatabaseId any
	DatabaseStatus any
	// Optional data sources to attach at creation. Omit or use an empty list to create the knowledge base without sources, then add sources (with chunking strategy and sizes) using [Add a Data Source to a Knowledge Base](#operation/create_knowledge_base_data_source). When provided, see [Organize Data Sources](https://docs.digitalocean.com/products/gradient-ai-platform/how-to/create-manage-agent-knowledge-bases/#add-data-sources) for best practices.
	Datasources any
	// Identifier for the [embedding model](https://docs.digitalocean.com/products/genai-platform/details/models/#embedding-models).
	EmbeddingModelUuid any
	// Knowledgebase Description
	KnowledgeBase any
	// Name of the knowledge base.
	Name any
	// Identifier of the DigitalOcean project this knowledge base will belong to.
	ProjectId any
	// The datacenter region to deploy the knowledge base in.
	Region any
	// Configuration for cross-encoder reranking during retrieval.
	RerankingConfig any
	Size any
	// Tags to organize your knowledge base.
	Tags any
	// The VPC to deploy the knowledge base database in
	VpcUuid any
	// path parameter, not part of the API's own resource representation
	Uuid any
}

var GetKnowledgeBaseOutput = ubx.ResourceBinding{
	WireType: "digitalocean_api_get_knowledge_base_output",
	Fields: ubx.FieldMap{
		"DatabaseId": ubx.FieldSpec{WireName: "database_id"},
		"Datasources": ubx.FieldSpec{
			WireName: "datasources",
			Kind: "list",
			Fields: GetKnowledgeBaseOutput_DatasourcesFields,
		},
		"EmbeddingModelUuid": ubx.FieldSpec{WireName: "embedding_model_uuid"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"ProjectId": ubx.FieldSpec{WireName: "project_id"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"RerankingConfig": ubx.FieldSpec{
			WireName: "reranking_config",
			Kind: "object",
			Fields: GetKnowledgeBaseOutput_KnowledgeBase_RerankingConfigFields,
		},
		"Size": ubx.FieldSpec{WireName: "size"},
		"Tags": ubx.FieldSpec{WireName: "tags"},
		"VpcUuid": ubx.FieldSpec{WireName: "vpc_uuid"},
		"Uuid": ubx.FieldSpec{WireName: "uuid"},
	},
}
