// Code generated by `ubx sdk gen` from digitalocean_sql_mode. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ModeConfig {
  databaseClusterUuid: string | Computed<string>;
}

export interface ModeAttrs {
  databaseClusterUuid: string;
  /** A string specifying the configured SQL modes for the MySQL cluster. */
  sqlMode: string;
}

export const Mode: DataSourceBinding<ModeConfig, ModeAttrs> = {
  wireType: "digitalocean_sql_mode",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
  },
};
