// Code generated by `ubx sdk gen` from digitalocean_api_get_model_catalog_card_output. DO NOT EDIT.
package gradientaiplatform

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ApiGetModelCatalogCardOutput_Data_CodeSnippets struct {
	Curl       any
	Javascript any
	Python     any
	Sdk        any
}

type ApiGetModelCatalogCardOutput_Data_Modalities struct {
	Input  any
	Output any
}

type ApiGetModelCatalogCardOutput_Data_Pricing struct {
	// Per-million cache read rate for standard chat models (token_type "cache read input"). Multimodal models use text_cache_read_input_price_per_million / image_cache_read_input_price_per_million instead.
	CacheReadInputPricePerMillion any
	// Price per million tokens written to the prompt cache with a 1-hour lifetime.
	CacheWrite1hInputPricePerMillion any
	// Price per million tokens written to the prompt cache with a 5-minute lifetime.
	CacheWrite5mInputPricePerMillion   any
	ImageCacheReadInputPricePerMillion any
	ImageInputPricePerMillion          any
	ImageOutputPricePerMillion         any
	// Cache read input price per single token. Equivalent to cache_read_input_price_per_million.
	InputCacheRead        any
	InputPricePerMillion  any
	OutputPricePerMillion any
	PricePerAudio         any
	// Unit-based pricing for non-token models (e.g., Fal AI image/video/audio generation, speech models). At most one of these is typically populated per model. Token-based models (chat, embeddings) leave all of these at 0 and populate input_price_per_million / output_price_per_million instead.
	PricePerImage              any
	PricePerMegapixel          any
	PricePerSecond             any
	PricePerThousandCharacters any
	PricePerVideo              any
	// Price per million reasoning tokens. 0 if the model does not charge separately for reasoning tokens.
	ReasoningPricePerMillion          any
	TextCacheReadInputPricePerMillion any
	// Per-million token rates for models that bill text vs image tokens separately (e.g. OpenAI gpt-image-2). Standard chat models leave these at 0 and use input_price_per_million / output_price_per_million instead. Values align with usage token_type / internal/usage.Type string values for each meter.
	TextInputPricePerMillion  any
	TextOutputPricePerMillion any
}

type ApiGetModelCatalogCardOutput_Data_PricingDetail_Variants_ScaledPricing_Intervals struct {
	EndTime   any
	Prices    any
	StartTime any
}

type ApiGetModelCatalogCardOutput_Data_PricingDetail_Variants_ScaledPricing struct {
	Intervals any
	MaxPrices any
	MinPrices any
}

type ApiGetModelCatalogCardOutput_Data_PricingDetail_Variants struct {
	Currency      any
	Label         any
	Mode          any
	Prices        any
	ScaledPricing any
	Tier          any
}

type ApiGetModelCatalogCardOutput_Data_PricingDetail struct {
	// Each available pricing variant for the model.
	Variants any
}

type ApiGetModelCatalogCardOutput_Data struct {
	Availability any
	// Badges for models
	Badges any
	// Benchmark scores for this model, stored as arbitrary JSON
	BenchmarkScore any
	Capabilities   any
	// Code examples for using the model
	CodeSnippets any
	// Specs (same as Entry)
	ContextWindow any
	// Model creator/developer (e.g., "Meta", "Anthropic", "OpenAI")
	Creator any
	// Card-specific
	Description any
	// The Hugging Face repository ID (e.g. "meta-llama/Llama-3.3-70B-Instruct") the model is based on, when applicable. Omitted for models not sourced from Hugging Face.
	HuggingFaceId any
	// Identity (same as Entry)
	Id any
	// The maximum number of output tokens the model can generate in a single response.
	MaxOutputTokens any
	// Input/output modalities
	Modalities any
	// Model identifier used for API calls (e.g., "llama3.1-70b-instruct")
	ModelId        any
	Name           any
	ParameterCount any
	// Pricing per million tokens (aligns with existing ModelPrice pattern)
	Pricing any
	// The complete set of prices for a model, covering every available variant.
	PricingDetail    any
	Provider         any
	ShortDescription any
	Type             any
}

type ApiGetModelCatalogCardOutputConfig struct {
	Id      any
	ModelId any
}

type ApiGetModelCatalogCardOutputAttrs struct {
	// Detail view for GetModelCatalogCard
	Data    any
	Id      any
	ModelId any
}

var ApiGetModelCatalogCardOutput = ubx.DataSourceBinding{
	WireType: "digitalocean_api_get_model_catalog_card_output",
	Fields: ubx.FieldMap{
		"Id":      ubx.FieldSpec{WireName: "id"},
		"ModelId": ubx.FieldSpec{WireName: "model_id"},
	},
}
