# Code generated by `ubx sdk gen` from digitalocean_trigger. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Trigger_ScheduledDetails_Body:
    name: Any = None

@dataclasses.dataclass
class Trigger_ScheduledDetails:
    # Optional data to be sent to function while triggering the function.
    body: Any = None
    # valid cron expression string which is required for SCHEDULED type triggers.
    cron: Any = None

@dataclasses.dataclass
class Trigger_Trigger_ScheduledRuns:
    # Indicates last run time. null value indicates trigger not run yet.
    last_run_at: Any = None
    # Indicates next run time. null value indicates trigger will not run.
    next_run_at: Any = None

@dataclasses.dataclass
class Trigger_Trigger:
    # UTC time string.
    created_at: Any = None
    # Name of function(action) that exists in the given namespace.
    function: Any = None
    # Indicates weather the trigger is paused or unpaused.
    is_enabled: Any = None
    # The trigger's unique name within the namespace.
    name: Any = None
    # A unique string format of UUID with a prefix fn-.
    namespace: Any = None
    # Trigger details for SCHEDULED type, where body is optional.
    scheduled_details: Any = None
    scheduled_runs: Any = None
    # String which indicates the type of trigger source like SCHEDULED.
    type: Any = None
    # UTC time string.
    updated_at: Any = None

_Trigger_ScheduledDetails_BodyFields = {
    "name": ubx.FieldSpec(wire_name="name"),
}

_Trigger_ScheduledDetailsFields = {
    "body": ubx.FieldSpec(
        wire_name="body",
        kind="object",
        fields=_Trigger_ScheduledDetails_BodyFields,
    ),
    "cron": ubx.FieldSpec(wire_name="cron"),
}

@dataclasses.dataclass
class TriggerConfig:
    # Name of function(action) that exists in the given namespace.
    function: Any = None
    # Indicates weather the trigger is paused or unpaused.
    is_enabled: Any = None
    # The trigger's unique name within the namespace.
    name: Any = None
    # Trigger details for SCHEDULED type, where body is optional.
    scheduled_details: Any = None
    # One of different type of triggers. Currently only SCHEDULED is supported.
    type: Any = None
    # path parameter, not part of the API's own resource representation
    namespace_id: Any = None
    # path parameter, not part of the API's own resource representation
    trigger_name: Any = None

@dataclasses.dataclass
class TriggerAttrs:
    # Name of function(action) that exists in the given namespace.
    function: Any = None
    # Indicates weather the trigger is paused or unpaused.
    is_enabled: Any = None
    # The trigger's unique name within the namespace.
    name: Any = None
    # Trigger details for SCHEDULED type, where body is optional.
    scheduled_details: Any = None
    trigger: Any = None
    # One of different type of triggers. Currently only SCHEDULED is supported.
    type: Any = None
    # path parameter, not part of the API's own resource representation
    namespace_id: Any = None
    # path parameter, not part of the API's own resource representation
    trigger_name: Any = None

Trigger = ubx.ResourceBinding(
    wire_type="digitalocean_trigger",
    fields={
        "function": ubx.FieldSpec(wire_name="function"),
        "is_enabled": ubx.FieldSpec(wire_name="is_enabled"),
        "name": ubx.FieldSpec(wire_name="name"),
        "scheduled_details": ubx.FieldSpec(
            wire_name="scheduled_details",
            kind="object",
            fields=_Trigger_ScheduledDetailsFields,
        ),
        "type": ubx.FieldSpec(wire_name="type"),
        "namespace_id": ubx.FieldSpec(wire_name="namespace_id"),
        "trigger_name": ubx.FieldSpec(wire_name="trigger_name"),
    },
)
