# Code generated by `ubx sdk gen` from digitalocean_kubernete. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class KuberneteConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class KuberneteAttrs:
    page: Any = None
    per_page: Any = None

Kubernete = ubx.DataSourceBinding(
    wire_type="digitalocean_kubernete",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
