// Code generated by `ubx sdk gen` from digitalocean_dedicated_inference_gpu_model_config. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface InferenceGpuModelConfig_GpuModelConfigs {
  gpuSlugs?: string[] | Computed<string[]>;
  isGatedModel?: boolean | Computed<boolean>;
  modelName?: string | Computed<string>;
  modelSlug?: string | Computed<string>;
}

export interface InferenceGpuModelConfigConfig {
}

export interface InferenceGpuModelConfigAttrs {
  gpuModelConfigs: InferenceGpuModelConfig_GpuModelConfigs[];
}

export const InferenceGpuModelConfig: DataSourceBinding<InferenceGpuModelConfigConfig, InferenceGpuModelConfigAttrs> = {
  wireType: "digitalocean_dedicated_inference_gpu_model_config",
  fields: {
  },
};
