// Code generated by `ubx sdk gen` from digitalocean_dedicated_inference. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Inference_DedicatedInferences_Endpoints {
  privateEndpointFqdn?: string | Computed<string>;
  publicEndpointFqdn?: string | Computed<string>;
}

export interface Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments_Accelerators {
  acceleratorSlug?: string | Computed<string>;
  scale?: number | Computed<number>;
  status?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments {
  accelerators?: Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments_Accelerators[] | Computed<Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments_Accelerators[]>;
  modelId?: string | Computed<string>;
  modelProvider?: string | Computed<string>;
  modelSlug?: string | Computed<string>;
  workloadConfig?: unknown | Computed<unknown>;
}

export interface Inference_DedicatedInferences_PendingDeploymentSpec_Vpc {
  uuid?: string | Computed<string>;
}

export interface Inference_DedicatedInferences_PendingDeploymentSpec {
  createdAt?: string | Computed<string>;
  enablePublicEndpoint?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  modelDeployments?: Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments[] | Computed<Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments[]>;
  name?: string | Computed<string>;
  status?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  version?: number | Computed<number>;
  vpc?: Inference_DedicatedInferences_PendingDeploymentSpec_Vpc | Computed<Inference_DedicatedInferences_PendingDeploymentSpec_Vpc>;
}

export interface Inference_DedicatedInferences_Spec {
  enablePublicEndpoint?: boolean | Computed<boolean>;
  modelDeployments?: Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments[] | Computed<Inference_DedicatedInferences_PendingDeploymentSpec_ModelDeployments[]>;
  name?: string | Computed<string>;
  region?: string | Computed<string>;
  version?: number | Computed<number>;
  vpc?: Inference_DedicatedInferences_PendingDeploymentSpec_Vpc | Computed<Inference_DedicatedInferences_PendingDeploymentSpec_Vpc>;
}

export interface Inference_DedicatedInferences {
  createdAt?: string | Computed<string>;
  endpoints?: Inference_DedicatedInferences_Endpoints | Computed<Inference_DedicatedInferences_Endpoints>;
  id?: string | Computed<string>;
  pendingDeploymentSpec?: Inference_DedicatedInferences_PendingDeploymentSpec | Computed<Inference_DedicatedInferences_PendingDeploymentSpec>;
  region?: string | Computed<string>;
  spec?: Inference_DedicatedInferences_Spec | Computed<Inference_DedicatedInferences_Spec>;
  status?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  vpcUuid?: string | Computed<string>;
}

export interface Inference_Links {
  /** Pagination links (first, prev, next, last). */
  pages?: Record<string, string> | Computed<Record<string, string>>;
}

export interface Inference_Meta {
  /** Total number of results. */
  total: number | Computed<number>;
}

export interface InferenceConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  region?: string | Computed<string>;
}

export interface InferenceAttrs {
  /** Array of Dedicated Inference instances. */
  dedicatedInferences: Inference_DedicatedInferences[];
  links: Inference_Links;
  meta: Inference_Meta;
  page: number;
  perPage: number;
  region: string;
}

export const Inference: DataSourceBinding<InferenceConfig, InferenceAttrs> = {
  wireType: "digitalocean_dedicated_inference",
  fields: {
    page: "page",
    perPage: "per_page",
    region: "region",
  },
};
