# Code generated by `ubx sdk gen` from digitalocean_account. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Account_Account_Team:
    # The name for the current team.
    name: Any = None
    # The unique universal identifier for the current team.
    uuid: Any = None

@dataclasses.dataclass
class Account_Account:
    # The total number of Droplets current user or team may have active at one time. <br><br>Requires `droplet:read` scope.
    droplet_limit: Any = None
    # The email address used by the current user to register for DigitalOcean.
    email: Any = None
    # If true, the user has verified their account via email. False otherwise.
    email_verified: Any = None
    # The total number of Floating IPs the current user or team may have. <br><br>Requires `reserved_ip:read` scope.
    floating_ip_limit: Any = None
    # The display name for the current user.
    name: Any = None
    # This value is one of "active", "warning" or "locked".
    status: Any = None
    # A human-readable message giving more details about the status of the account.
    status_message: Any = None
    # When authorized in a team context, includes information about the current team.
    team: Any = None
    # The unique universal identifier for the current user.
    uuid: Any = None

@dataclasses.dataclass
class AccountConfig:
    pass

@dataclasses.dataclass
class AccountAttrs:
    account: Any = None

Account = ubx.DataSourceBinding(
    wire_type="digitalocean_account",
    fields={
    },
)
