# Code generated by `ubx sdk gen` from digitalocean@dynamic. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "digitalocean", "version": "dynamic"}

from .alert import Alert, AlertConfig
from .destination_omit_credentials import DestinationOmitCredentials, DestinationOmitCredentialsConfig
from .metrics import Metrics, MetricsConfig
from .sinks_response import SinksResponse, SinksResponseConfig
