# Code generated by `ubx sdk gen` from digitalocean_alert. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Alert_Links:
    pages: Any = None

@dataclasses.dataclass
class Alert_Meta:
    total: Any = None

@dataclasses.dataclass
class Alert_Policies_Alerts_Slack:
    channel: Any = None
    url: Any = None

@dataclasses.dataclass
class Alert_Policies_Alerts:
    email: Any = None
    slack: Any = None

@dataclasses.dataclass
class Alert_Policies:
    alerts: Any = None
    compare: Any = None
    description: Any = None
    enabled: Any = None
    entities: Any = None
    tags: Any = None
    type: Any = None
    uuid: Any = None
    value: Any = None
    window: Any = None

@dataclasses.dataclass
class AlertConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class AlertAttrs:
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None
    policies: Any = None

Alert = ubx.DataSourceBinding(
    wire_type="digitalocean_alert",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
