# Code generated by `ubx sdk gen` from digitalocean_sinks_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SinksResponse_Sinks_Destination_Config_Credentials:
    password: Any = None
    username: Any = None

@dataclasses.dataclass
class SinksResponse_Sinks_Destination_Config:
    cluster_name: Any = None
    cluster_uuid: Any = None
    credentials: Any = None
    endpoint: Any = None
    id: Any = None
    index_name: Any = None
    retention_days: Any = None

@dataclasses.dataclass
class SinksResponse_Sinks_Destination:
    config: Any = None
    id: Any = None
    name: Any = None
    type: Any = None

@dataclasses.dataclass
class SinksResponse_Sinks_Resources:
    name: Any = None
    urn: Any = None

@dataclasses.dataclass
class SinksResponse_Sinks:
    destination: Any = None
    resources: Any = None

@dataclasses.dataclass
class SinksResponseConfig:
    # The uniform resource name (URN) for the resource in the format do:resource_type:resource_id.
    resource_id: Any = None

@dataclasses.dataclass
class SinksResponseAttrs:
    # The uniform resource name (URN) for the resource in the format do:resource_type:resource_id.
    resource_id: Any = None
    # List of sinks identified by their URNs.
    sinks: Any = None

SinksResponse = ubx.DataSourceBinding(
    wire_type="digitalocean_sinks_response",
    fields={
        "resource_id": ubx.FieldSpec(wire_name="resource_id"),
    },
)
