# Code generated by `ubx sdk gen` from digitalocean@dynamic. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "digitalocean", "version": "dynamic"}

from .inference import Inference, InferenceConfig
from .inference_accelerator import InferenceAccelerator, InferenceAcceleratorConfig
from .inference_gpu_model_config import InferenceGpuModelConfig, InferenceGpuModelConfigConfig
from .inference_size import InferenceSize, InferenceSizeConfig
