# Code generated by `ubx sdk gen` from digitalocean_dedicated_inference_size. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class InferenceSize_Sizes:
    currency: Any = None
    gpu_slug: Any = None
    price_per_hour: Any = None
    region: Any = None

@dataclasses.dataclass
class InferenceSizeConfig:
    pass

@dataclasses.dataclass
class InferenceSizeAttrs:
    # Regions where Dedicated Inference is available.
    enabled_regions: Any = None
    sizes: Any = None

InferenceSize = ubx.DataSourceBinding(
    wire_type="digitalocean_dedicated_inference_size",
    fields={
    },
)
