// Code generated by `ubx sdk gen` from digitalocean_destination_omit_credentials. DO NOT EDIT.
package monitoring

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DestinationOmitCredentials_Destinations_Config struct {
	ClusterName   any
	ClusterUuid   any
	Endpoint      any
	Id            any
	IndexName     any
	RetentionDays any
}

type DestinationOmitCredentials_Destinations struct {
	Config any
	Id     any
	Name   any
	Type   any
}

type DestinationOmitCredentialsConfig struct {
}

type DestinationOmitCredentialsAttrs struct {
	Destinations any
}

var DestinationOmitCredentials = ubx.DataSourceBinding{
	WireType: "digitalocean_destination_omit_credentials",
	Fields:   ubx.FieldMap{},
}
