// Code generated by `ubx sdk gen` from digitalocean_droplet. DO NOT EDIT.
package droplet

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DropletConfig struct {
	Name any
	Page any
	PerPage any
}

type DropletAttrs struct {
	Name any
	Page any
	PerPage any
}

var Droplet = ubx.DataSourceBinding{
	WireType: "digitalocean_droplet",
	Fields: ubx.FieldMap{
		"Name": ubx.FieldSpec{WireName: "name"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
