// Code generated by `ubx sdk gen` from digitalocean_registry. DO NOT EDIT.
package containerregistries

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Registry_Registry struct {
	CreatedAt                  any
	Name                       any
	Region                     any
	StorageUsageBytes          any
	StorageUsageBytesUpdatedAt any
}

type RegistryConfig struct {
	// A globally unique name for the container registry. Must be lowercase and be composed only of numbers, letters and `-`, up to a limit of 63 characters.
	Name any
	// Slug of the region where registry data is stored. When not provided, a region will be selected.
	Region any
	// The slug of the subscription tier to sign up for. Valid values can be retrieved using the options endpoint.
	SubscriptionTierSlug any
	// path parameter, not part of the API's own resource representation
	RegistryName any
}

type RegistryAttrs struct {
	// A globally unique name for the container registry. Must be lowercase and be composed only of numbers, letters and `-`, up to a limit of 63 characters.
	Name any
	// Slug of the region where registry data is stored. When not provided, a region will be selected.
	Region any
	// The container registry's own real, current representation. (AI-inferred)
	Registry any
	// The slug of the subscription tier to sign up for. Valid values can be retrieved using the options endpoint.
	SubscriptionTierSlug any
	// path parameter, not part of the API's own resource representation
	RegistryName any
}

var Registry = ubx.ResourceBinding{
	WireType: "digitalocean_registry",
	Fields: ubx.FieldMap{
		"Name":                 ubx.FieldSpec{WireName: "name"},
		"Region":               ubx.FieldSpec{WireName: "region"},
		"SubscriptionTierSlug": ubx.FieldSpec{WireName: "subscription_tier_slug"},
		"RegistryName":         ubx.FieldSpec{WireName: "registry_name"},
	},
}
