// Code generated by `ubx sdk gen` from digitalocean_scan. DO NOT EDIT.
package scan

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Scan_Scan_Findings_MitigationSteps struct {
	Description any
	Step any
	Title any
}

type Scan_Scan_Findings struct {
	AffectedResourcesCount any
	BusinessImpact any
	Details any
	FoundAt any
	MitigationSteps any
	Name any
	RuleUuid any
	Severity any
	TechnicalDetails any
}

type Scan_Scan struct {
	// When scan was created.
	CreatedAt any
	Findings any
	// The unique identifier for the scan.
	Id any
	// The status of the scan.
	Status any
}

type ScanConfig struct {
	// path parameter, not part of the API's own resource representation
	ScanId any
}

type ScanAttrs struct {
	Scan any
	// path parameter, not part of the API's own resource representation
	ScanId any
}

var Scan = ubx.ResourceBinding{
	WireType: "digitalocean_scan",
	Fields: ubx.FieldMap{
		"ScanId": ubx.FieldSpec{WireName: "scan_id"},
	},
}
