// Code generated by `ubx sdk gen` from digitalocean_credentials. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CredentialsConfig {
  clusterId: string | Computed<string>;
  expirySeconds?: number | Computed<number>;
}

export interface CredentialsAttrs {
  /** A base64 encoding of bytes representing the certificate authority data for accessing the cluster. */
  certificateAuthorityData: string;
  /** A base64 encoding of bytes representing the x509 client certificate data for access the cluster. This is only returned for clusters without support for token-based authentication. Newly created Kubernetes clusters do not return credentials using certificate-based authentication. For additional information, [see here](https://docs.digitalocean.com/products/kubernetes/how-to/connect-to-cluster/#authenticate). */
  clientCertificateData: string;
  /** A base64 encoding of bytes representing the x509 client key data for access the cluster. This is only returned for clusters without support for token-based authentication. Newly created Kubernetes clusters do not return credentials using certificate-based authentication. For additional information, [see here](https://docs.digitalocean.com/products/kubernetes/how-to/connect-to-cluster/#authenticate). */
  clientKeyData: string;
  clusterId: string;
  /** A time value given in ISO8601 combined date and time format that represents when the access token expires. */
  expiresAt: string;
  expirySeconds: number;
  /** The URL used to access the cluster API server. */
  server: string;
  /** An access token used to authenticate with the cluster. This is only returned for clusters with support for token-based authentication. */
  token: string;
}

export const Credentials: DataSourceBinding<CredentialsConfig, CredentialsAttrs> = {
  wireType: "digitalocean_credentials",
  fields: {
    clusterId: "cluster_id",
    expirySeconds: "expiry_seconds",
  },
};
