// Code generated by `ubx sdk gen` from digitalocean_kubernetes_options. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Options_Options_Regions {
  name?: string | Computed<string>;
  slug?: string | Computed<string>;
}

export interface Options_Options_Versions {
  kubernetesVersion?: string | Computed<string>;
  slug?: string | Computed<string>;
  supportedFeatures?: string[] | Computed<string[]>;
}

export interface Options_Options {
  regions?: Options_Options_Regions[] | Computed<Options_Options_Regions[]>;
  sizes?: Options_Options_Regions[] | Computed<Options_Options_Regions[]>;
  versions?: Options_Options_Versions[] | Computed<Options_Options_Versions[]>;
}

export interface OptionsConfig {
}

export interface OptionsAttrs {
  options: Options_Options;
}

export const Options: DataSourceBinding<OptionsConfig, OptionsAttrs> = {
  wireType: "digitalocean_kubernetes_options",
  fields: {
  },
};
