// Code generated by `ubx sdk gen` from digitalocean_status_messages. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface StatusMessages_Messages {
  message?: string | Computed<string>;
  timestamp?: string | Computed<string>;
}

export interface StatusMessagesConfig {
  clusterId: string | Computed<string>;
  since?: string | Computed<string>;
}

export interface StatusMessagesAttrs {
  clusterId: string;
  messages: StatusMessages_Messages[];
  since: string;
}

export const StatusMessages: DataSourceBinding<StatusMessagesConfig, StatusMessagesAttrs> = {
  wireType: "digitalocean_status_messages",
  fields: {
    clusterId: "cluster_id",
    since: "since",
  },
};
