// Code generated by `ubx sdk gen` from digitalocean_droplet. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface DropletConfig {
  name?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface DropletAttrs {
  name: string;
  page: number;
  perPage: number;
}

export const Droplet: DataSourceBinding<DropletConfig, DropletAttrs> = {
  wireType: "digitalocean_droplet",
  fields: {
    name: "name",
    page: "page",
    perPage: "per_page",
  },
};
