# Code generated by `ubx sdk gen` from digitalocean_byoip_prefix. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ByoipPrefix_ByoipPrefix_Validations:
    name: Any = None
    note: Any = None
    status: Any = None

@dataclasses.dataclass
class ByoipPrefix_ByoipPrefix:
    # Whether the BYOIP prefix is being advertised
    advertised: Any = None
    # Reason for failure, if applicable
    failure_reason: Any = None
    # Whether the BYOIP prefix is locked
    locked: Any = None
    # Name of the BYOIP prefix
    name: Any = None
    # The IP prefix in CIDR notation
    prefix: Any = None
    # The ID of the project associated with the BYOIP prefix
    project_id: Any = None
    # Region where the BYOIP prefix is located
    region: Any = None
    # Status of the BYOIP prefix
    status: Any = None
    # Unique identifier for the BYOIP prefix
    uuid: Any = None
    # List of validation statuses for the BYOIP prefix
    validations: Any = None

@dataclasses.dataclass
class ByoipPrefixConfig:
    # The IP prefix in CIDR notation to bring
    prefix: Any = None
    # The region where the prefix will be created
    region: Any = None
    # The signature hash for the prefix creation request
    signature: Any = None
    # path parameter, not part of the API's own resource representation
    byoip_prefix_uuid: Any = None

@dataclasses.dataclass
class ByoipPrefixAttrs:
    byoip_prefix: Any = None
    # The IP prefix in CIDR notation to bring
    prefix: Any = None
    # The region where the prefix will be created
    region: Any = None
    # The signature hash for the prefix creation request
    signature: Any = None
    # path parameter, not part of the API's own resource representation
    byoip_prefix_uuid: Any = None

ByoipPrefix = ubx.ResourceBinding(
    wire_type="digitalocean_byoip_prefix",
    fields={
        "prefix": ubx.FieldSpec(wire_name="prefix"),
        "region": ubx.FieldSpec(wire_name="region"),
        "signature": ubx.FieldSpec(wire_name="signature"),
        "byoip_prefix_uuid": ubx.FieldSpec(wire_name="byoip_prefix_uuid"),
    },
)
