// Code generated by `ubx sdk gen` from digitalocean_endpoint. DO NOT EDIT.
package cdnendpoints

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Endpoint_Endpoints struct {
	CertificateId any
	CreatedAt     any
	CustomDomain  any
	Endpoint      any
	Id            any
	Origin        any
	Ttl           any
}

type Endpoint_Links struct {
	Pages any
}

type Endpoint_Meta struct {
	Total any
}

type EndpointConfig struct {
	Page    any
	PerPage any
}

type EndpointAttrs struct {
	Endpoints any
	Links     any
	Meta      any
	Page      any
	PerPage   any
}

var Endpoint = ubx.DataSourceBinding{
	WireType: "digitalocean_endpoint",
	Fields: ubx.FieldMap{
		"Page":    ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
