// Code generated by `ubx sdk gen` from digitalocean_alert. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Alert_Alerts_Slack {
  channel?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface Alert_Alerts {
  /** An email to notify on an alert trigger. */
  email: string[] | Computed<string[]>;
  /** Slack integration details. */
  slack: Alert_Alerts_Slack[] | Computed<Alert_Alerts_Slack[]>;
}

export interface Alert_Policy {
  alerts: Alert_Alerts | Computed<Alert_Alerts>;
  compare: string | Computed<string>;
  description: string | Computed<string>;
  enabled: boolean | Computed<boolean>;
  entities: string[] | Computed<string[]>;
  tags: string[] | Computed<string[]>;
  type: string | Computed<string>;
  uuid: string | Computed<string>;
  value: number | Computed<number>;
  window: string | Computed<string>;
}

const Alert_Alerts_SlackFields: FieldMap = {
  channel: "channel",
  url: "url",
};

const Alert_AlertsFields: FieldMap = {
  email: "email",
  slack: {
    wireName: "slack",
    kind: "list",
    fields: Alert_Alerts_SlackFields,
  },
};

export interface AlertConfig {
  /** The real conditions that trigger this alert policy. (AI-inferred) */
  alerts: Alert_Alerts | Computed<Alert_Alerts>;
  /** The real comparison operator (greater than or less than) used against the threshold value. (AI-inferred) */
  compare: string | Computed<string>;
  /** A real, human-readable description of the alert policy. (AI-inferred) */
  description: string | Computed<string>;
  /** Whether the alert policy is currently active. (AI-inferred) */
  enabled: boolean | Computed<boolean>;
  /** The real IDs of the entities this alert policy monitors. (AI-inferred) */
  entities: string[] | Computed<string[]>;
  /** The real tags this alert policy applies to, in addition to any explicitly listed entities. (AI-inferred) */
  tags: string[] | Computed<string[]>;
  /** The real type of metric this alert policy monitors. (AI-inferred) */
  type: string | Computed<string>;
  /** The real threshold value that triggers this alert. (AI-inferred) */
  value: number | Computed<number>;
  /** The real time window the metric is evaluated over before triggering. (AI-inferred) */
  window: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  alertUuid: string | Computed<string>;
}

export interface AlertAttrs {
  /** The real conditions that trigger this alert policy. (AI-inferred) */
  alerts: Alert_Alerts;
  /** The real comparison operator (greater than or less than) used against the threshold value. (AI-inferred) */
  compare: string;
  /** A real, human-readable description of the alert policy. (AI-inferred) */
  description: string;
  /** Whether the alert policy is currently active. (AI-inferred) */
  enabled: boolean;
  /** The real IDs of the entities this alert policy monitors. (AI-inferred) */
  entities: string[];
  /** The real, full alert policy configuration. (AI-inferred) */
  policy: Alert_Policy;
  /** The real tags this alert policy applies to, in addition to any explicitly listed entities. (AI-inferred) */
  tags: string[];
  /** The real type of metric this alert policy monitors. (AI-inferred) */
  type: string;
  /** The real threshold value that triggers this alert. (AI-inferred) */
  value: number;
  /** The real time window the metric is evaluated over before triggering. (AI-inferred) */
  window: string;
  /** path parameter, not part of the API's own resource representation */
  alertUuid: string;
}

export const Alert: ResourceBinding<AlertConfig, AlertAttrs> = {
  wireType: "digitalocean_alert",
  fields: {
    alerts: {
      wireName: "alerts",
      kind: "object",
      fields: Alert_AlertsFields,
    },
    compare: "compare",
    description: "description",
    enabled: "enabled",
    entities: "entities",
    tags: "tags",
    type: "type",
    value: "value",
    window: "window",
    alertUuid: "alert_uuid",
  },
};
