// Code generated by `ubx sdk gen` from digitalocean_api_get_indexing_job_details_signed_urloutput. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GetIndexingJobDetailsSignedUrloutputConfig struct {
	IndexingJobUuid any
}

type GetIndexingJobDetailsSignedUrloutputAttrs struct {
	IndexingJobUuid any
	// The signed url for downloading the indexing job details
	SignedUrl any
}

var GetIndexingJobDetailsSignedUrloutput = ubx.DataSourceBinding{
	WireType: "digitalocean_api_get_indexing_job_details_signed_urloutput",
	Fields: ubx.FieldMap{
		"IndexingJobUuid": ubx.FieldSpec{WireName: "indexing_job_uuid"},
	},
}
