// Code generated by `ubx sdk gen` from digitalocean_api_get_custom_model_output_public. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GetCustomModelOutputPublic_Model_ActiveDeployments_Endpoints struct {
	PrivateEndpointFqdn any
	PublicEndpointFqdn any
}

type GetCustomModelOutputPublic_Model_ActiveDeployments struct {
	CreatedAt any
	Endpoints any
	Id any
	Name any
	RegionSlug any
	State any
	UpdatedAt any
}

type GetCustomModelOutputPublic_Model_SourceRef struct {
	// Access level required for the model repository
	AccessType any
	// Spaces bucket name
	Bucket any
	// Git commit SHA of the model version
	CommitSha any
	// User-provided HuggingFace token for gated/private models (not persisted in source_ref)
	HfToken any
	// Object prefix path in the bucket
	Prefix any
	// Spaces bucket region
	Region any
	// Huggingface repository identifier
	RepoId any
}

type GetCustomModelOutputPublic_Model_Tags struct {
	// List of tag strings
	Tags any
}

type GetCustomModelOutputPublic_Model struct {
	// List of active deployments using this model
	ActiveDeployments any
	// Model architecture type (free-form string from config.json)
	Architecture any
	// Raw config.json contents from the model repository
	ConfigJson any
	// Maximum context length supported by the model
	ContextLength any
	// Estimated monthly cost in dollars for hosting
	CostEstimatePerMonth any
	// Timestamp when the model was created
	CreatedAt any
	// Description of the custom model
	Description any
	// User-facing reason the most recent import failed; empty otherwise.
	ErrorMessage any
	// Number of files in the model
	FileCount any
	// Input modalities supported (e.g., text, image)
	InputModalities any
	// License under which the model is distributed
	License any
	// Name of the custom model
	Name any
	// Output modalities supported (e.g., text, image)
	OutputModalities any
	// Number of parameters in the model
	Parameters any
	// Reference to the original source of the model
	SourceRef any
	// Source from which the model was imported
	SourceType any
	// Import and deployment status of the custom model
	Status any
	// Region of the Spaces bucket where model files are stored
	StorageRegion any
	// User-defined tags for organizing models
	Tags any
	// Team that owns the model
	TeamId any
	// Total size of model files in bytes
	TotalSizeBytes any
	// Timestamp when the model was last updated
	UpdatedAt any
	// Unique identifier for the custom model
	Uuid any
}

type GetCustomModelOutputPublicConfig struct {
	Uuid any
}

type GetCustomModelOutputPublicAttrs struct {
	// Custom model - user-imported model from HuggingFace, Spaces, etc.
	Model any
	Uuid any
}

var GetCustomModelOutputPublic = ubx.DataSourceBinding{
	WireType: "digitalocean_api_get_custom_model_output_public",
	Fields: ubx.FieldMap{
		"Uuid": ubx.FieldSpec{WireName: "uuid"},
	},
}
