// Code generated by `ubx sdk gen` from digitalocean_api_indexed_data_source. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type IndexedDataSource_IndexedDataSources struct {
	CompletedAt any
	DataSourceUuid any
	ErrorDetails any
	ErrorMsg any
	FailedItemCount any
	IndexedFileCount any
	IndexedItemCount any
	RemovedItemCount any
	SkippedItemCount any
	StartedAt any
	Status any
	TotalBytes any
	TotalBytesIndexed any
	TotalFileCount any
}

type IndexedDataSourceConfig struct {
	IndexingJobUuid any
}

type IndexedDataSourceAttrs struct {
	IndexedDataSources any
	IndexingJobUuid any
}

var IndexedDataSource = ubx.DataSourceBinding{
	WireType: "digitalocean_api_indexed_data_source",
	Fields: ubx.FieldMap{
		"IndexingJobUuid": ubx.FieldSpec{WireName: "indexing_job_uuid"},
	},
}
