// Code generated by `ubx sdk gen` from digitalocean_api_model_router. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ModelRouter_Links_Pages struct {
	// First page
	First any
	// Last page
	Last any
	// Next page
	Next any
	// Previous page
	Previous any
}

type ModelRouter_Links struct {
	// Information about how to reach other pages
	Pages any
}

type ModelRouter_Meta struct {
	// The current page
	Page any
	// Total number of pages
	Pages any
	// Total amount of items over all pages
	Total any
}

type ModelRouter_ModelRouters_Config_Policies_CustomTask struct {
	Description any
	Name any
}

type ModelRouter_ModelRouters_Config_Policies_SelectionPolicy struct {
	Prefer any
}

type ModelRouter_ModelRouters_Config_Policies struct {
	CustomTask any
	Models any
	SelectionPolicy any
	TaskSlug any
}

type ModelRouter_ModelRouters_Config struct {
	FallbackModels any
	Policies any
}

type ModelRouter_ModelRouters struct {
	Config any
	CreatedAt any
	Description any
	Name any
	Regions any
	UpdatedAt any
	Uuid any
}

type ModelRouterConfig struct {
	Page any
	PerPage any
}

type ModelRouterAttrs struct {
	// Links to other pages
	Links any
	// Meta information about the data set
	Meta any
	// The model routers
	ModelRouters any
	Page any
	PerPage any
}

var ModelRouter = ubx.DataSourceBinding{
	WireType: "digitalocean_api_model_router",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
