// Code generated by `ubx sdk gen` from digitalocean_api_model_router_preset. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ModelRouterPreset_Links_Pages struct {
	// First page
	First any
	// Last page
	Last any
	// Next page
	Next any
	// Previous page
	Previous any
}

type ModelRouterPreset_Links struct {
	// Information about how to reach other pages
	Pages any
}

type ModelRouterPreset_Meta struct {
	// The current page
	Page any
	// Total number of pages
	Pages any
	// Total amount of items over all pages
	Total any
}

type ModelRouterPreset_Presets_Config_Policies_CustomTask struct {
	Description any
	Name any
}

type ModelRouterPreset_Presets_Config_Policies_SelectionPolicy struct {
	Prefer any
}

type ModelRouterPreset_Presets_Config_Policies struct {
	CustomTask any
	Models any
	SelectionPolicy any
	TaskSlug any
}

type ModelRouterPreset_Presets_Config struct {
	FallbackModels any
	Policies any
}

type ModelRouterPreset_Presets struct {
	Config any
	DisplayName any
	LongDescription any
	ShortDescription any
	Slug any
}

type ModelRouterPresetConfig struct {
	Page any
	PerPage any
}

type ModelRouterPresetAttrs struct {
	// Links to other pages
	Links any
	// Meta information about the data set
	Meta any
	Page any
	PerPage any
	// The model router presets
	Presets any
}

var ModelRouterPreset = ubx.DataSourceBinding{
	WireType: "digitalocean_api_model_router_preset",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
