// Code generated by `ubx sdk gen` from digitalocean_api_model_apikey_info. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ModelApikeyInfo_ApiKeyInfos struct {
	CreatedAt any
	CreatedBy any
	DeletedAt any
	Name any
	SecretKey any
	Uuid any
}

type ModelApikeyInfo_Links_Pages struct {
	// First page
	First any
	// Last page
	Last any
	// Next page
	Next any
	// Previous page
	Previous any
}

type ModelApikeyInfo_Links struct {
	// Information about how to reach other pages
	Pages any
}

type ModelApikeyInfo_Meta struct {
	// The current page
	Page any
	// Total number of pages
	Pages any
	// Total amount of items over all pages
	Total any
}

type ModelApikeyInfoConfig struct {
	Page any
	PerPage any
}

type ModelApikeyInfoAttrs struct {
	// Api key infos
	ApiKeyInfos any
	// Links to other pages
	Links any
	// Meta information about the data set
	Meta any
	Page any
	PerPage any
}

var ModelApikeyInfo = ubx.DataSourceBinding{
	WireType: "digitalocean_api_model_apikey_info",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
