// Code generated by `ubx sdk gen` from digitalocean_vpc. DO NOT EDIT.
package vpc

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VpcConfig struct {
	Page any
	PerPage any
	ResourceType any
	VpcId any
}

type VpcAttrs struct {
	Page any
	PerPage any
	ResourceType any
	VpcId any
}

var Vpc = ubx.DataSourceBinding{
	WireType: "digitalocean_vpc",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"ResourceType": ubx.FieldSpec{WireName: "resource_type"},
		"VpcId": ubx.FieldSpec{WireName: "vpc_id"},
	},
}
