// Code generated by `ubx sdk gen` from digitalocean_access_point_get_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface PointGetResponse_AccessPoint_AccessPolicy {
  /** GID used for squashed users. Currently only 65534 is supported. */
  anongid: number | Computed<number>;
  /** UID used for squashed users. Currently only 65534 is supported. */
  anonuid: number | Computed<number>;
  /** Whether identity enforcement is enabled for this export. */
  identityEnforcementEnabled: boolean | Computed<boolean>;
  /** Allowed NFS protocols for this export. */
  protocols: string[] | Computed<string[]>;
  /** The squash mode applied to the access point export. */
  squashConfig: string | Computed<string>;
}

export interface PointGetResponse_AccessPoint {
  /** Provider-agnostic NFS access policy for an access point. Network CIDRs are managed by attach, detach, and managed-access workflows and are not part of this policy. */
  accessPolicy: PointGetResponse_AccessPoint_AccessPolicy | Computed<PointGetResponse_AccessPoint_AccessPolicy>;
  /** The timestamp when the access point was created. */
  createdAt?: string | Computed<string>;
  /** The unique identifier of the access point. */
  id?: string | Computed<string>;
  /** Whether this is the share's default access point. */
  isDefault?: boolean | Computed<boolean>;
  /** The human-readable name of the access point. Must be unique per share. */
  name: string | Computed<string>;
  /** The export sub-path for this access point (always starts with `/`). */
  path: string | Computed<string>;
  /** The unique identifier of the share this access point belongs to. */
  shareId?: string | Computed<string>;
  /** The current lifecycle status of an access point. There is no ACCESS_POINT_DELETING state: DELETE soft-deletes the access point synchronously (mirroring share deletion); the response of a delete request returns the access point already in ACCESS_POINT_DELETED. */
  status?: string | Computed<string>;
  /** The timestamp when the access point was last updated. May be empty while the access point is still being created. */
  updatedAt?: string | Computed<string>;
  /** The VPC this access point is pinned to. Omitted on the default access point. Every non-default access point owns its own storage gateway in this VPC and is independent of the parent share's VPC lifecycle. */
  vpcId?: string | Computed<string>;
}

export interface PointGetResponseConfig {
  accessPointId: string | Computed<string>;
}

export interface PointGetResponseAttrs {
  /** Represents an NFS access point resource. */
  accessPoint: PointGetResponse_AccessPoint;
  accessPointId: string;
}

export const PointGetResponse: DataSourceBinding<PointGetResponseConfig, PointGetResponseAttrs> = {
  wireType: "digitalocean_access_point_get_response",
  fields: {
    accessPointId: "access_point_id",
  },
};
