// Code generated by `ubx sdk gen` from digitalocean_namespace. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Namespace_Namespaces {
  apiHost?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  key?: string | Computed<string>;
  label?: string | Computed<string>;
  namespace?: string | Computed<string>;
  region?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  uuid?: string | Computed<string>;
}

export interface NamespaceConfig {
}

export interface NamespaceAttrs {
  namespaces: Namespace_Namespaces[];
}

export const Namespace: DataSourceBinding<NamespaceConfig, NamespaceAttrs> = {
  wireType: "digitalocean_namespace",
  fields: {
  },
};
