# Code generated by `ubx sdk gen` from digitalocean_vectordb_get_vector_dbadmin_credentials_response. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VectordbGetVectorDbadminCredentialsResponseConfig:
    id: Any = None

@dataclasses.dataclass
class VectordbGetVectorDbadminCredentialsResponseAttrs:
    # API token for that user.
    api_token: Any = None
    id: Any = None
    # Database user id from the cluster secret (opaque; matches what was provisioned).
    user_id: Any = None

VectordbGetVectorDbadminCredentialsResponse = ubx.DataSourceBinding(
    wire_type="digitalocean_vectordb_get_vector_dbadmin_credentials_response",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
    },
)
