// Code generated by `ubx sdk gen` from digitalocean_volume. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Volume_Volume_Region {
  available?: boolean | Computed<boolean>;
  features?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  sizes?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
}

export interface Volume_Volume {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  dropletIds?: number[] | Computed<number[]>;
  filesystemLabel?: string | Computed<string>;
  filesystemType?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  region?: Volume_Volume_Region | Computed<Volume_Volume_Region>;
  sizeGigabytes?: number | Computed<number>;
  tags?: string[] | Computed<string[]>;
}

export interface VolumeConfig {
  /** path parameter, not part of the API's own resource representation */
  volumeId: string | Computed<string>;
}

export interface VolumeAttrs {
  volume: Volume_Volume;
  /** path parameter, not part of the API's own resource representation */
  volumeId: string;
}

export const Volume: ResourceBinding<VolumeConfig, VolumeAttrs> = {
  wireType: "digitalocean_volume",
  fields: {
    volumeId: "volume_id",
  },
};
