// Code generated by `ubx sdk gen` from digitalocean_dedicated_inference. DO NOT EDIT.
package dedicated

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Inference_DedicatedInference_Endpoints struct {
	// Private VPC FQDN of the Dedicated Inference instance.
	PrivateEndpointFqdn any
	// Public FQDN of the Dedicated Inference instance.
	PublicEndpointFqdn any
}

type Inference_DedicatedInference_PendingDeploymentSpec_ModelDeployments_Accelerators struct {
	AcceleratorSlug any
	Scale any
	Status any
	Type any
}

type Inference_DedicatedInference_PendingDeploymentSpec_ModelDeployments struct {
	Accelerators any
	ModelId any
	ModelProvider any
	ModelSlug any
	WorkloadConfig any
}

type Inference_DedicatedInference_PendingDeploymentSpec_Vpc struct {
	// VPC UUID for the Dedicated Inference.
	Uuid any
}

type Inference_DedicatedInference_PendingDeploymentSpec struct {
	CreatedAt any
	// Whether to expose a public LLM endpoint.
	EnablePublicEndpoint any
	// Deployment UUID.
	Id any
	// At least one model deployment is required.
	ModelDeployments any
	// Name of the Dedicated Inference. Must be unique within the team.
	Name any
	Status any
	UpdatedAt any
	// Spec version.
	Version any
	Vpc any
}

type Inference_DedicatedInference_Spec struct {
	// Whether to expose a public LLM endpoint.
	EnablePublicEndpoint any
	// At least one model deployment is required.
	ModelDeployments any
	// Name of the Dedicated Inference. Must be unique within the team.
	Name any
	// DigitalOcean region where the Dedicated Inference is hosted.
	Region any
	// Spec version.
	Version any
	Vpc any
}

type Inference_DedicatedInference struct {
	// When the Dedicated Inference was created.
	CreatedAt any
	Endpoints any
	// Unique ID of the Dedicated Inference.
	Id any
	// Pending deployment when status is provisioning or updating.
	PendingDeploymentSpec any
	// DigitalOcean region where the Dedicated Inference is hosted.
	Region any
	// Structured configuration for a Dedicated Inference deployment.
	Spec any
	// Current state of the Dedicated Inference.
	Status any
	// When the Dedicated Inference was last updated.
	UpdatedAt any
	// VPC UUID of the Dedicated Inference.
	VpcUuid any
}

var Inference_DedicatedInference_PendingDeploymentSpec_ModelDeployments_AcceleratorsFields = ubx.FieldMap{
		"AcceleratorSlug": ubx.FieldSpec{WireName: "accelerator_slug"},
		"Scale": ubx.FieldSpec{WireName: "scale"},
		"Status": ubx.FieldSpec{WireName: "status"},
		"Type": ubx.FieldSpec{WireName: "type"},
	}

var Inference_DedicatedInference_PendingDeploymentSpec_ModelDeploymentsFields = ubx.FieldMap{
		"Accelerators": ubx.FieldSpec{
			WireName: "accelerators",
			Kind: "list",
			Fields: Inference_DedicatedInference_PendingDeploymentSpec_ModelDeployments_AcceleratorsFields,
		},
		"ModelId": ubx.FieldSpec{WireName: "model_id"},
		"ModelProvider": ubx.FieldSpec{WireName: "model_provider"},
		"ModelSlug": ubx.FieldSpec{WireName: "model_slug"},
		"WorkloadConfig": ubx.FieldSpec{WireName: "workload_config"},
	}

var Inference_DedicatedInference_PendingDeploymentSpec_VpcFields = ubx.FieldMap{
		"Uuid": ubx.FieldSpec{WireName: "uuid"},
	}

var Inference_DedicatedInference_SpecFields = ubx.FieldMap{
		"EnablePublicEndpoint": ubx.FieldSpec{WireName: "enable_public_endpoint"},
		"ModelDeployments": ubx.FieldSpec{
			WireName: "model_deployments",
			Kind: "list",
			Fields: Inference_DedicatedInference_PendingDeploymentSpec_ModelDeploymentsFields,
		},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Region": ubx.FieldSpec{WireName: "region"},
		"Version": ubx.FieldSpec{WireName: "version"},
		"Vpc": ubx.FieldSpec{
			WireName: "vpc",
			Kind: "object",
			Fields: Inference_DedicatedInference_PendingDeploymentSpec_VpcFields,
		},
	}

type InferenceConfig struct {
	// Key-value pairs for provider tokens (e.g. Hugging Face).
	AccessTokens any
	// Structured configuration for a Dedicated Inference deployment.
	Spec any
	// path parameter, not part of the API's own resource representation
	DedicatedInferenceId any
}

type InferenceAttrs struct {
	// Key-value pairs for provider tokens (e.g. Hugging Face).
	AccessTokens any
	// A Dedicated Inference instance.
	DedicatedInference any
	// Structured configuration for a Dedicated Inference deployment.
	Spec any
	// path parameter, not part of the API's own resource representation
	DedicatedInferenceId any
}

var Inference = ubx.ResourceBinding{
	WireType: "digitalocean_dedicated_inference",
	Fields: ubx.FieldMap{
		"AccessTokens": ubx.FieldSpec{WireName: "access_tokens"},
		"Spec": ubx.FieldSpec{
			WireName: "spec",
			Kind: "object",
			Fields: Inference_DedicatedInference_SpecFields,
		},
		"DedicatedInferenceId": ubx.FieldSpec{WireName: "dedicated_inference_id"},
	},
}
