// Code generated by `ubx sdk gen` from digitalocean_project. DO NOT EDIT.
package project

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Project_Project struct {
	CreatedAt any
	Description any
	Environment any
	Id any
	IsDefault any
	Name any
	OwnerId any
	OwnerUuid any
	Purpose any
	UpdatedAt any
}

type ProjectConfig struct {
	// path parameter, not part of the API's own resource representation
	ProjectId any
}

type ProjectAttrs struct {
	Project any
	// path parameter, not part of the API's own resource representation
	ProjectId any
}

var Project = ubx.ResourceBinding{
	WireType: "digitalocean_project",
	Fields: ubx.FieldMap{
		"ProjectId": ubx.FieldSpec{WireName: "project_id"},
	},
}
