# Code generated by `ubx sdk gen` from digitalocean_alert. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Alert_Alert_Notifications_Slack:
    channel: Any = None
    url: Any = None

@dataclasses.dataclass
class Alert_Alert_Notifications:
    email: Any = None
    slack: Any = None

@dataclasses.dataclass
class Alert_Alert:
    comparison: Any = None
    id: Any = None
    name: Any = None
    notifications: Any = None
    period: Any = None
    threshold: Any = None
    type: Any = None

@dataclasses.dataclass
class AlertConfig:
    alert_id: Any = None
    check_id: Any = None

@dataclasses.dataclass
class AlertAttrs:
    alert: Any = None
    alert_id: Any = None
    check_id: Any = None

Alert = ubx.DataSourceBinding(
    wire_type="digitalocean_alert",
    fields={
        "alert_id": ubx.FieldSpec(wire_name="alert_id"),
        "check_id": ubx.FieldSpec(wire_name="check_id"),
    },
)
