// Code generated by `ubx sdk gen` from digitalocean_replica. DO NOT EDIT.
package replica

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Replica_Replica_Connection struct {
	Database any
	Host any
	Password any
	Port any
	Ssl any
	Uri any
	User any
}

type Replica_Replica_DoSettings struct {
	ServiceCnames any
}

type Replica_Replica struct {
	Connection any
	// A time value given in ISO8601 combined date and time format that represents when the database cluster was created.
	CreatedAt any
	DoSettings any
	// A unique ID that can be used to identify and reference a database replica.
	Id any
	// The name to give the read-only replicating
	Name any
	PrivateConnection any
	// A string specifying the UUID of the VPC to which the read-only replica will be assigned. If excluded, the replica will be assigned to your account's default VPC for the region. <br><br>Requires `vpc:read` scope.
	PrivateNetworkUuid any
	// A slug identifier for the region where the read-only replica will be located. If excluded, the replica will be placed in the same region as the cluster.
	Region any
	// A slug identifier representing the size of the node for the read-only replica. The size of the replica must be at least as large as the node size for the database cluster from which it is replicating.
	Size any
	// A string representing the current status of the database cluster.
	Status any
	// Additional storage added to the cluster, in MiB. If null, no additional storage is added to the cluster, beyond what is provided as a base amount from the 'size' and any previously added additional storage.
	StorageSizeMib any
	// A flat array of tag names as strings applied to the read-only replica.<br><br>Requires `tag:read` scope.
	Tags any
}

type ReplicaConfig struct {
	// path parameter, not part of the API's own resource representation
	DatabaseClusterUuid any
	// path parameter, not part of the API's own resource representation
	ReplicaName any
}

type ReplicaAttrs struct {
	Replica any
	// path parameter, not part of the API's own resource representation
	DatabaseClusterUuid any
	// path parameter, not part of the API's own resource representation
	ReplicaName any
}

var Replica = ubx.ResourceBinding{
	WireType: "digitalocean_replica",
	Fields: ubx.FieldMap{
		"DatabaseClusterUuid": ubx.FieldSpec{WireName: "database_cluster_uuid"},
		"ReplicaName": ubx.FieldSpec{WireName: "replica_name"},
	},
}
