// Code generated by `ubx sdk gen` from digitalocean_load_balancer. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LoadBalancer_LoadBalancer_Domains {
  certificateId?: string | Computed<string>;
  isManaged?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
}

export interface LoadBalancer_LoadBalancer_Firewall {
  allow?: string[] | Computed<string[]>;
  deny?: string[] | Computed<string[]>;
}

export interface LoadBalancer_LoadBalancer_ForwardingRules {
  certificateId?: string | Computed<string>;
  entryPort?: number | Computed<number>;
  entryProtocol?: string | Computed<string>;
  targetPort?: number | Computed<number>;
  targetProtocol?: string | Computed<string>;
  tlsPassthrough?: boolean | Computed<boolean>;
}

export interface LoadBalancer_LoadBalancer_GlbSettings_Cdn {
  isEnabled?: boolean | Computed<boolean>;
}

export interface LoadBalancer_LoadBalancer_GlbSettings {
  cdn?: LoadBalancer_LoadBalancer_GlbSettings_Cdn | Computed<LoadBalancer_LoadBalancer_GlbSettings_Cdn>;
  failoverThreshold?: number | Computed<number>;
  regionPriorities?: Record<string, number> | Computed<Record<string, number>>;
  targetPort?: number | Computed<number>;
  targetProtocol?: string | Computed<string>;
}

export interface LoadBalancer_LoadBalancer_HealthCheck {
  checkIntervalSeconds?: number | Computed<number>;
  healthyThreshold?: number | Computed<number>;
  path?: string | Computed<string>;
  port?: number | Computed<number>;
  protocol?: string | Computed<string>;
  responseTimeoutSeconds?: number | Computed<number>;
  unhealthyThreshold?: number | Computed<number>;
}

export interface LoadBalancer_LoadBalancer_Region {
  available?: boolean | Computed<boolean>;
  features?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  sizes?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
}

export interface LoadBalancer_LoadBalancer_StickySessions {
  cookieName?: string | Computed<string>;
  cookieTtlSeconds?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface LoadBalancer_LoadBalancer {
  algorithm?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  disableLetsEncryptDnsRecords?: boolean | Computed<boolean>;
  domains?: LoadBalancer_LoadBalancer_Domains[] | Computed<LoadBalancer_LoadBalancer_Domains[]>;
  dropletIds?: number[] | Computed<number[]>;
  enableBackendKeepalive?: boolean | Computed<boolean>;
  enableProxyProtocol?: boolean | Computed<boolean>;
  firewall?: LoadBalancer_LoadBalancer_Firewall | Computed<LoadBalancer_LoadBalancer_Firewall>;
  forwardingRules?: LoadBalancer_LoadBalancer_ForwardingRules[] | Computed<LoadBalancer_LoadBalancer_ForwardingRules[]>;
  glbSettings?: LoadBalancer_LoadBalancer_GlbSettings | Computed<LoadBalancer_LoadBalancer_GlbSettings>;
  healthCheck?: LoadBalancer_LoadBalancer_HealthCheck | Computed<LoadBalancer_LoadBalancer_HealthCheck>;
  httpIdleTimeoutSeconds?: number | Computed<number>;
  id?: string | Computed<string>;
  ip?: string | Computed<string>;
  ipv6?: string | Computed<string>;
  name?: string | Computed<string>;
  network?: string | Computed<string>;
  networkStack?: string | Computed<string>;
  projectId?: string | Computed<string>;
  redirectHttpToHttps?: boolean | Computed<boolean>;
  region?: LoadBalancer_LoadBalancer_Region | Computed<LoadBalancer_LoadBalancer_Region>;
  size?: string | Computed<string>;
  sizeUnit?: number | Computed<number>;
  status?: string | Computed<string>;
  stickySessions?: LoadBalancer_LoadBalancer_StickySessions | Computed<LoadBalancer_LoadBalancer_StickySessions>;
  tag?: string | Computed<string>;
  targetLoadBalancerIds?: string[] | Computed<string[]>;
  tlsCipherPolicy?: string | Computed<string>;
  type?: string | Computed<string>;
  vpcUuid?: string | Computed<string>;
}

export interface LoadBalancerConfig {
  /** path parameter, not part of the API's own resource representation */
  lbId: string | Computed<string>;
}

export interface LoadBalancerAttrs {
  /** The Load Balancer's own real, current representation. (AI-inferred) */
  loadBalancer: LoadBalancer_LoadBalancer;
  /** path parameter, not part of the API's own resource representation */
  lbId: string;
}

export const LoadBalancer: ResourceBinding<LoadBalancerConfig, LoadBalancerAttrs> = {
  wireType: "digitalocean_load_balancer",
  fields: {
    lbId: "lb_id",
  },
};
