// Code generated by `ubx sdk gen` from digitalocean_project. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Project_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Project_Meta {
  total?: number | Computed<number>;
}

export interface Project_Projects {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  environment?: string | Computed<string>;
  id?: string | Computed<string>;
  isDefault?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
  ownerId?: number | Computed<number>;
  ownerUuid?: string | Computed<string>;
  purpose?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
}

export interface ProjectConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface ProjectAttrs {
  links: Project_Links;
  meta: Project_Meta;
  page: number;
  perPage: number;
  projects: Project_Projects[];
}

export const Project: DataSourceBinding<ProjectConfig, ProjectAttrs> = {
  wireType: "digitalocean_project",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
