// Code generated by `ubx sdk gen` from digitalocean_sinks_response. DO NOT EDIT.
package sinks

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Response_Sinks_Destination_Config_Credentials struct {
	Password any
	Username any
}

type Response_Sinks_Destination_Config struct {
	ClusterName any
	ClusterUuid any
	Credentials any
	Endpoint any
	Id any
	IndexName any
	RetentionDays any
}

type Response_Sinks_Destination struct {
	Config any
	Id any
	Name any
	Type any
}

type Response_Sinks_Resources struct {
	Name any
	Urn any
}

type Response_Sinks struct {
	Destination any
	Resources any
}

type ResponseConfig struct {
	// The uniform resource name (URN) for the resource in the format do:resource_type:resource_id.
	ResourceId any
}

type ResponseAttrs struct {
	// The uniform resource name (URN) for the resource in the format do:resource_type:resource_id.
	ResourceId any
	// List of sinks identified by their URNs.
	Sinks any
}

var Response = ubx.DataSourceBinding{
	WireType: "digitalocean_sinks_response",
	Fields: ubx.FieldMap{
		"ResourceId": ubx.FieldSpec{WireName: "resource_id"},
	},
}
