# Code generated by `ubx sdk gen` from digitalocean_vectordb_get_vector_dbresponse. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GetVectorDbresponse_VectorDb_Config:
    # Default vector compression for new collections: rq, pq, bq, or sq. Empty means platform default (rq).
    default_quantization: Any = None
    enable_auto_schema: Any = None
    # The Vector Database version running on the cluster.
    weaviate_version: Any = None

@dataclasses.dataclass
class GetVectorDbresponse_VectorDb_Endpoints:
    # Endpoint for gRPC connections (e.g. "my-db-tor1-a1b2c3d4-grpc.weaviate.ondigitalocean.com:443").
    grpc: Any = None
    # Endpoint for HTTPS connections (e.g. "https://my-db-tor1-a1b2c3d4.weaviate.ondigitalocean.com").
    http: Any = None

@dataclasses.dataclass
class GetVectorDbresponse_VectorDb:
    # VectorDBConfig holds optional, advanced cluster settings.
    config: Any = None
    created_at: Any = None
    # VectorDBEndpoints contains the connection endpoints for a vector database instance.
    endpoints: Any = None
    # ID of the vector database this instance was forked from. Empty when the instance was created directly via CreateVectorDB. Read-only and set by the platform at fork time; never modifiable through UpdateVectorDB.
    forked_from_id: Any = None
    id: Any = None
    # Backup_id of the most recent restore initiated against this instance. Empty if no restore has ever been triggered. Lets callers recover the identifier of an in-flight or last-completed restore without having to retain the RestoreBackupResponse themselves. Use it with GetRestoreStatus to fetch the live status.
    last_restore_id: Any = None
    name: Any = None
    owner_uuid: Any = None
    # Project this database belongs to.
    project_id: Any = None
    region: Any = None
    # Resource tier: small, medium, or large.
    size: Any = None
    # Lifecycle state: pending, creating, active, errored, or deleting.
    status: Any = None
    tags: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class GetVectorDbresponseConfig:
    # Required. Human-readable name for the database.
    name: Any = None
    # Required. ID of the project to create the vector database in.
    project_id: Any = None
    # Required. Region slug where the database will be provisioned.
    region: Any = None
    # Required. Resource tier: small, medium, or large.
    size: Any = None
    # A set of arbitrary tags to organize your vector database
    tags: Any = None
    # path parameter, not part of the API's own resource representation
    id: Any = None

@dataclasses.dataclass
class GetVectorDbresponseAttrs:
    # Required. Human-readable name for the database.
    name: Any = None
    # Required. ID of the project to create the vector database in.
    project_id: Any = None
    # Required. Region slug where the database will be provisioned.
    region: Any = None
    # Required. Resource tier: small, medium, or large.
    size: Any = None
    # A set of arbitrary tags to organize your vector database
    tags: Any = None
    # VectorDB represents a provisioned vector database instance.
    vector_db: Any = None
    # path parameter, not part of the API's own resource representation
    id: Any = None

GetVectorDbresponse = ubx.ResourceBinding(
    wire_type="digitalocean_vectordb_get_vector_dbresponse",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "project_id": ubx.FieldSpec(wire_name="project_id"),
        "region": ubx.FieldSpec(wire_name="region"),
        "size": ubx.FieldSpec(wire_name="size"),
        "tags": ubx.FieldSpec(wire_name="tags"),
        "id": ubx.FieldSpec(wire_name="id"),
    },
)
