# Code generated by `ubx sdk gen` from digitalocean_credential. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Credential_Credentials_Credentials:
    # basic authentication password for metrics HTTP endpoint
    basic_auth_password: Any = None
    # basic authentication username for metrics HTTP endpoint
    basic_auth_username: Any = None

@dataclasses.dataclass
class Credential_Credentials:
    credentials: Any = None

@dataclasses.dataclass
class CredentialConfig:
    pass

@dataclasses.dataclass
class CredentialAttrs:
    credentials: Any = None

Credential = ubx.DataSourceBinding(
    wire_type="digitalocean_credential",
    fields={
    },
)
