# Code generated by `ubx sdk gen` from digitalocean_kafka_schema_verbose. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class KafkaSchemaVerbose_Subjects:
    schema: Any = None
    schema_id: Any = None
    schema_type: Any = None
    subject_name: Any = None

@dataclasses.dataclass
class KafkaSchemaVerboseConfig:
    database_cluster_uuid: Any = None

@dataclasses.dataclass
class KafkaSchemaVerboseAttrs:
    database_cluster_uuid: Any = None
    subjects: Any = None

KafkaSchemaVerbose = ubx.DataSourceBinding(
    wire_type="digitalocean_kafka_schema_verbose",
    fields={
        "database_cluster_uuid": ubx.FieldSpec(wire_name="database_cluster_uuid"),
    },
)
