// Code generated by `ubx sdk gen` from digitalocean_model. DO NOT EDIT.
package serverlessinference

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Model_Data struct {
	Created any
	Id      any
	Object  any
	OwnedBy any
}

type ModelConfig struct {
}

type ModelAttrs struct {
	// The list of available models.
	Data any
	// The object type, which is always "list".
	Object any
}

var Model = ubx.DataSourceBinding{
	WireType: "digitalocean_model",
	Fields:   ubx.FieldMap{},
}
