// Code generated by `ubx sdk gen` from digitalocean_snapshot. DO NOT EDIT.
package snapshot

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Snapshot_Snapshot struct {
	CreatedAt any
	Id any
	MinDiskSize any
	Name any
	Regions any
	ResourceId any
	ResourceType any
	SizeGigabytes any
	Tags any
}

type SnapshotConfig struct {
	SnapshotId any
}

type SnapshotAttrs struct {
	Snapshot any
	SnapshotId any
}

var Snapshot = ubx.DataSourceBinding{
	WireType: "digitalocean_snapshot",
	Fields: ubx.FieldMap{
		"SnapshotId": ubx.FieldSpec{WireName: "snapshot_id"},
	},
}
