# Code generated by `ubx sdk gen` from digitalocean_droplet. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Droplet_Droplets_DiskInfo_Size:
    amount: Any = None
    unit: Any = None

@dataclasses.dataclass
class Droplet_Droplets_DiskInfo:
    size: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplets_GpuInfo:
    count: Any = None
    model: Any = None
    vram: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Image:
    created_at: Any = None
    description: Any = None
    distribution: Any = None
    error_message: Any = None
    id: Any = None
    min_disk_size: Any = None
    name: Any = None
    public: Any = None
    regions: Any = None
    size_gigabytes: Any = None
    slug: Any = None
    status: Any = None
    tags: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Kernel:
    id: Any = None
    name: Any = None
    version: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Networks_V4:
    gateway: Any = None
    ip_address: Any = None
    netmask: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Networks_V6:
    gateway: Any = None
    ip_address: Any = None
    netmask: Any = None
    type: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Networks:
    v4: Any = None
    v6: Any = None

@dataclasses.dataclass
class Droplet_Droplets_NextBackupWindow:
    end: Any = None
    start: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Region:
    available: Any = None
    features: Any = None
    name: Any = None
    sizes: Any = None
    slug: Any = None

@dataclasses.dataclass
class Droplet_Droplets_Size:
    available: Any = None
    description: Any = None
    disk: Any = None
    disk_info: Any = None
    gpu_info: Any = None
    memory: Any = None
    price_hourly: Any = None
    price_monthly: Any = None
    regions: Any = None
    slug: Any = None
    transfer: Any = None
    vcpus: Any = None

@dataclasses.dataclass
class Droplet_Droplets:
    backup_ids: Any = None
    created_at: Any = None
    disk: Any = None
    disk_info: Any = None
    features: Any = None
    gpu_info: Any = None
    id: Any = None
    image: Any = None
    kernel: Any = None
    locked: Any = None
    memory: Any = None
    name: Any = None
    networks: Any = None
    next_backup_window: Any = None
    region: Any = None
    size: Any = None
    size_slug: Any = None
    snapshot_ids: Any = None
    status: Any = None
    tags: Any = None
    vcpus: Any = None
    volume_ids: Any = None
    vpc_uuid: Any = None

@dataclasses.dataclass
class Droplet_Links:
    pages: Any = None

@dataclasses.dataclass
class Droplet_Meta:
    total: Any = None

@dataclasses.dataclass
class DropletConfig:
    name: Any = None
    page: Any = None
    per_page: Any = None
    tag_name: Any = None
    type: Any = None

@dataclasses.dataclass
class DropletAttrs:
    droplets: Any = None
    links: Any = None
    meta: Any = None
    name: Any = None
    page: Any = None
    per_page: Any = None
    tag_name: Any = None
    type: Any = None

Droplet = ubx.DataSourceBinding(
    wire_type="digitalocean_droplet",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "tag_name": ubx.FieldSpec(wire_name="tag_name"),
        "type": ubx.FieldSpec(wire_name="type"),
    },
)
