# Code generated by `ubx sdk gen` from digitalocean_api_custom_model. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApiCustomModel_Links_Pages:
    # First page
    first: Any = None
    # Last page
    last: Any = None
    # Next page
    next: Any = None
    # Previous page
    previous: Any = None

@dataclasses.dataclass
class ApiCustomModel_Links:
    # Information about how to reach other pages
    pages: Any = None

@dataclasses.dataclass
class ApiCustomModel_Meta:
    # The current page
    page: Any = None
    # Total number of pages
    pages: Any = None
    # Total amount of items over all pages
    total: Any = None

@dataclasses.dataclass
class ApiCustomModel_Models_ActiveDeployments_Endpoints:
    private_endpoint_fqdn: Any = None
    public_endpoint_fqdn: Any = None

@dataclasses.dataclass
class ApiCustomModel_Models_ActiveDeployments:
    created_at: Any = None
    endpoints: Any = None
    id: Any = None
    name: Any = None
    region_slug: Any = None
    state: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class ApiCustomModel_Models_SourceRef:
    access_type: Any = None
    bucket: Any = None
    commit_sha: Any = None
    hf_token: Any = None
    prefix: Any = None
    region: Any = None
    repo_id: Any = None

@dataclasses.dataclass
class ApiCustomModel_Models_Tags:
    tags: Any = None

@dataclasses.dataclass
class ApiCustomModel_Models:
    active_deployments: Any = None
    architecture: Any = None
    config_json: Any = None
    context_length: Any = None
    cost_estimate_per_month: Any = None
    created_at: Any = None
    description: Any = None
    error_message: Any = None
    file_count: Any = None
    input_modalities: Any = None
    license: Any = None
    name: Any = None
    output_modalities: Any = None
    parameters: Any = None
    source_ref: Any = None
    source_type: Any = None
    status: Any = None
    storage_region: Any = None
    tags: Any = None
    team_id: Any = None
    total_size_bytes: Any = None
    updated_at: Any = None
    uuid: Any = None

@dataclasses.dataclass
class ApiCustomModelConfig:
    page: Any = None
    per_page: Any = None
    status: Any = None

@dataclasses.dataclass
class ApiCustomModelAttrs:
    # Links to other pages
    links: Any = None
    # Maximum number of custom models allowed for this team's tier
    max_threshold: Any = None
    # Meta information about the data set
    meta: Any = None
    # List of custom models
    models: Any = None
    page: Any = None
    per_page: Any = None
    status: Any = None

ApiCustomModel = ubx.DataSourceBinding(
    wire_type="digitalocean_api_custom_model",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "status": ubx.FieldSpec(wire_name="status"),
    },
)
