# Code generated by `ubx sdk gen` from digitalocean_api_open_aiapikey_info. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos_Models_Agreement:
    description: Any = None
    name: Any = None
    url: Any = None
    uuid: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos_Models_Endpoints:
    capabilities: Any = None
    endpoint: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos_Models_Modalities:
    input: Any = None
    output: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos_Models_Settings:
    default_string: Any = None
    default_value: Any = None
    max: Any = None
    min: Any = None
    name: Any = None
    options: Any = None
    step: Any = None
    type: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos_Models_Version:
    major: Any = None
    minor: Any = None
    patch: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos_Models:
    agreement: Any = None
    benchmark_score: Any = None
    capabilities: Any = None
    context_window: Any = None
    created_at: Any = None
    endpoints: Any = None
    inference_name: Any = None
    inference_version: Any = None
    is_foundational: Any = None
    kb_default_chunk_size: Any = None
    kb_max_chunk_size: Any = None
    kb_min_chunk_size: Any = None
    lifecycle_status: Any = None
    metadata: Any = None
    modalities: Any = None
    name: Any = None
    parameter_count: Any = None
    parent_uuid: Any = None
    provider: Any = None
    reasoning_efforts: Any = None
    settings: Any = None
    thinking: Any = None
    type: Any = None
    updated_at: Any = None
    upload_complete: Any = None
    url: Any = None
    usecases: Any = None
    uuid: Any = None
    version: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_ApiKeyInfos:
    created_at: Any = None
    created_by: Any = None
    deleted_at: Any = None
    models: Any = None
    name: Any = None
    updated_at: Any = None
    uuid: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_Links_Pages:
    # First page
    first: Any = None
    # Last page
    last: Any = None
    # Next page
    next: Any = None
    # Previous page
    previous: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_Links:
    # Information about how to reach other pages
    pages: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfo_Meta:
    # The current page
    page: Any = None
    # Total number of pages
    pages: Any = None
    # Total amount of items over all pages
    total: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfoConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class ApiOpenAiapikeyInfoAttrs:
    # Api key infos
    api_key_infos: Any = None
    # Links to other pages
    links: Any = None
    # Meta information about the data set
    meta: Any = None
    page: Any = None
    per_page: Any = None

ApiOpenAiapikeyInfo = ubx.DataSourceBinding(
    wire_type="digitalocean_api_open_aiapikey_info",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
