# Code generated by `ubx sdk gen` from digitalocean_api_get_model_catalog_card_output. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_CodeSnippets:
    curl: Any = None
    javascript: Any = None
    python: Any = None
    sdk: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_Modalities:
    input: Any = None
    output: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_Pricing:
    # Per-million cache read rate for standard chat models (token_type "cache read input"). Multimodal models use text_cache_read_input_price_per_million / image_cache_read_input_price_per_million instead.
    cache_read_input_price_per_million: Any = None
    # Price per million tokens written to the prompt cache with a 1-hour lifetime.
    cache_write_1h_input_price_per_million: Any = None
    # Price per million tokens written to the prompt cache with a 5-minute lifetime.
    cache_write_5m_input_price_per_million: Any = None
    image_cache_read_input_price_per_million: Any = None
    image_input_price_per_million: Any = None
    image_output_price_per_million: Any = None
    # Cache read input price per single token. Equivalent to cache_read_input_price_per_million.
    input_cache_read: Any = None
    input_price_per_million: Any = None
    output_price_per_million: Any = None
    price_per_audio: Any = None
    # Unit-based pricing for non-token models (e.g., Fal AI image/video/audio generation, speech models). At most one of these is typically populated per model. Token-based models (chat, embeddings) leave all of these at 0 and populate input_price_per_million / output_price_per_million instead.
    price_per_image: Any = None
    price_per_megapixel: Any = None
    price_per_second: Any = None
    price_per_thousand_characters: Any = None
    price_per_video: Any = None
    # Price per million reasoning tokens. 0 if the model does not charge separately for reasoning tokens.
    reasoning_price_per_million: Any = None
    text_cache_read_input_price_per_million: Any = None
    # Per-million token rates for models that bill text vs image tokens separately (e.g. OpenAI gpt-image-2). Standard chat models leave these at 0 and use input_price_per_million / output_price_per_million instead. Values align with usage token_type / internal/usage.Type string values for each meter.
    text_input_price_per_million: Any = None
    text_output_price_per_million: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_PricingDetail_Variants_ScaledPricing_Intervals:
    end_time: Any = None
    prices: Any = None
    start_time: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_PricingDetail_Variants_ScaledPricing:
    intervals: Any = None
    max_prices: Any = None
    min_prices: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_PricingDetail_Variants:
    currency: Any = None
    label: Any = None
    mode: Any = None
    prices: Any = None
    scaled_pricing: Any = None
    tier: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data_PricingDetail:
    # Each available pricing variant for the model.
    variants: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutput_Data:
    availability: Any = None
    # Badges for models
    badges: Any = None
    # Benchmark scores for this model, stored as arbitrary JSON
    benchmark_score: Any = None
    capabilities: Any = None
    # Code examples for using the model
    code_snippets: Any = None
    # Specs (same as Entry)
    context_window: Any = None
    # Model creator/developer (e.g., "Meta", "Anthropic", "OpenAI")
    creator: Any = None
    # Card-specific
    description: Any = None
    # The Hugging Face repository ID (e.g. "meta-llama/Llama-3.3-70B-Instruct") the model is based on, when applicable. Omitted for models not sourced from Hugging Face.
    hugging_face_id: Any = None
    # Identity (same as Entry)
    id: Any = None
    # The maximum number of output tokens the model can generate in a single response.
    max_output_tokens: Any = None
    # Input/output modalities
    modalities: Any = None
    # Model identifier used for API calls (e.g., "llama3.1-70b-instruct")
    model_id: Any = None
    name: Any = None
    parameter_count: Any = None
    # Pricing per million tokens (aligns with existing ModelPrice pattern)
    pricing: Any = None
    # The complete set of prices for a model, covering every available variant.
    pricing_detail: Any = None
    provider: Any = None
    short_description: Any = None
    type: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutputConfig:
    id: Any = None
    model_id: Any = None

@dataclasses.dataclass
class ApiGetModelCatalogCardOutputAttrs:
    # Detail view for GetModelCatalogCard
    data: Any = None
    id: Any = None
    model_id: Any = None

ApiGetModelCatalogCardOutput = ubx.DataSourceBinding(
    wire_type="digitalocean_api_get_model_catalog_card_output",
    fields={
        "id": ubx.FieldSpec(wire_name="id"),
        "model_id": ubx.FieldSpec(wire_name="model_id"),
    },
)
