# Code generated by `ubx sdk gen` from digitalocean_options. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Options_Options_AdvancedMysql_Layouts:
    num_nodes: Any = None
    sizes: Any = None

@dataclasses.dataclass
class Options_Options_AdvancedMysql:
    layouts: Any = None
    regions: Any = None
    versions: Any = None

@dataclasses.dataclass
class Options_Options:
    advanced_mysql: Any = None
    advanced_pg: Any = None
    kafka: Any = None
    mongodb: Any = None
    mysql: Any = None
    opensearch: Any = None
    pg: Any = None
    redis: Any = None
    valkey: Any = None

@dataclasses.dataclass
class Options_VersionAvailability_AdvancedMysql:
    end_of_availability: Any = None
    end_of_life: Any = None
    version: Any = None

@dataclasses.dataclass
class Options_VersionAvailability:
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    advanced_mysql: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    advanced_pg: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    kafka: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    mongodb: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    mysql: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    opensearch: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    pg: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    redis: Any = None
    # An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
    valkey: Any = None

@dataclasses.dataclass
class OptionsConfig:
    pass

@dataclasses.dataclass
class OptionsAttrs:
    options: Any = None
    version_availability: Any = None

Options = ubx.DataSourceBinding(
    wire_type="digitalocean_options",
    fields={
    },
)
