# Code generated by `ubx sdk gen` from digitalocean_tag. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Tag_Links:
    pages: Any = None

@dataclasses.dataclass
class Tag_Meta:
    total: Any = None

@dataclasses.dataclass
class Tag_Tags:
    compressed_size_bytes: Any = None
    manifest_digest: Any = None
    registry_name: Any = None
    repository: Any = None
    size_bytes: Any = None
    tag: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class TagConfig:
    page: Any = None
    per_page: Any = None
    registry_name: Any = None
    repository_name: Any = None

@dataclasses.dataclass
class TagAttrs:
    links: Any = None
    meta: Any = None
    page: Any = None
    per_page: Any = None
    registry_name: Any = None
    repository_name: Any = None
    tags: Any = None

Tag = ubx.DataSourceBinding(
    wire_type="digitalocean_tag",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "registry_name": ubx.FieldSpec(wire_name="registry_name"),
        "repository_name": ubx.FieldSpec(wire_name="repository_name"),
    },
)
