// Code generated by `ubx sdk gen` from digitalocean_dedicated_inference_accelerator. DO NOT EDIT.
package dedicated

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type InferenceAcceleratorConfig struct {
	AcceleratorId any
	DedicatedInferenceId any
}

type InferenceAcceleratorAttrs struct {
	AcceleratorId any
	CreatedAt any
	DedicatedInferenceId any
	// Unique ID of the accelerator.
	Id any
	// Name of the accelerator.
	Name any
	// Role of the accelerator (e.g. prefill_decode).
	Role any
	// DigitalOcean GPU slug.
	Slug any
	// Status of the accelerator.
	Status any
}

var InferenceAccelerator = ubx.DataSourceBinding{
	WireType: "digitalocean_dedicated_inference_accelerator",
	Fields: ubx.FieldMap{
		"AcceleratorId": ubx.FieldSpec{WireName: "accelerator_id"},
		"DedicatedInferenceId": ubx.FieldSpec{WireName: "dedicated_inference_id"},
	},
}
