// Code generated by `ubx sdk gen` from digitalocean_replica. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Replica_Replica_Connection {
  database?: string | Computed<string>;
  host?: string | Computed<string>;
  password?: string | Computed<string>;
  port?: number | Computed<number>;
  ssl?: boolean | Computed<boolean>;
  uri?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface Replica_Replica_DoSettings {
  serviceCnames?: string[] | Computed<string[]>;
}

export interface Replica_Replica {
  connection?: Replica_Replica_Connection | Computed<Replica_Replica_Connection>;
  /** A time value given in ISO8601 combined date and time format that represents when the database cluster was created. */
  createdAt?: string | Computed<string>;
  doSettings?: Replica_Replica_DoSettings | Computed<Replica_Replica_DoSettings>;
  /** A unique ID that can be used to identify and reference a database replica. */
  id?: string | Computed<string>;
  /** The name to give the read-only replicating */
  name: string | Computed<string>;
  privateConnection?: Replica_Replica_Connection | Computed<Replica_Replica_Connection>;
  /** A string specifying the UUID of the VPC to which the read-only replica will be assigned. If excluded, the replica will be assigned to your account's default VPC for the region. <br><br>Requires `vpc:read` scope. */
  privateNetworkUuid?: string | Computed<string>;
  /** A slug identifier for the region where the read-only replica will be located. If excluded, the replica will be placed in the same region as the cluster. */
  region?: string | Computed<string>;
  /** A slug identifier representing the size of the node for the read-only replica. The size of the replica must be at least as large as the node size for the database cluster from which it is replicating. */
  size?: string | Computed<string>;
  /** A string representing the current status of the database cluster. */
  status?: string | Computed<string>;
  /** Additional storage added to the cluster, in MiB. If null, no additional storage is added to the cluster, beyond what is provided as a base amount from the 'size' and any previously added additional storage. */
  storageSizeMib?: number | Computed<number>;
  /** A flat array of tag names as strings applied to the read-only replica.<br><br>Requires `tag:read` scope. */
  tags?: string[] | Computed<string[]>;
}

export interface ReplicaConfig {
  /** path parameter, not part of the API's own resource representation */
  databaseClusterUuid: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  replicaName: string | Computed<string>;
}

export interface ReplicaAttrs {
  replica: Replica_Replica;
  /** path parameter, not part of the API's own resource representation */
  databaseClusterUuid: string;
  /** path parameter, not part of the API's own resource representation */
  replicaName: string;
}

export const Replica: ResourceBinding<ReplicaConfig, ReplicaAttrs> = {
  wireType: "digitalocean_replica",
  fields: {
    databaseClusterUuid: "database_cluster_uuid",
    replicaName: "replica_name",
  },
};
