// Code generated by `ubx sdk gen` from digitalocean_invoice. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface InvoiceConfig {
  invoiceUuid: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface InvoiceAttrs {
  invoiceUuid: string;
  page: number;
  perPage: number;
}

export const Invoice: DataSourceBinding<InvoiceConfig, InvoiceAttrs> = {
  wireType: "digitalocean_invoice",
  fields: {
    invoiceUuid: "invoice_uuid",
    page: "page",
    perPage: "per_page",
  },
};
