// Code generated by `ubx sdk gen` from digitalocean_attachment. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Attachment_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Attachment_Meta {
  total?: number | Computed<number>;
}

export interface Attachment_PartnerAttachments_Bgp {
  localAsn?: number | Computed<number>;
  localRouterIp?: string | Computed<string>;
  peerAsn?: number | Computed<number>;
  peerRouterIp?: string | Computed<string>;
}

export interface Attachment_PartnerAttachments {
  bgp?: Attachment_PartnerAttachments_Bgp | Computed<Attachment_PartnerAttachments_Bgp>;
  children?: string[] | Computed<string[]>;
  connectionBandwidthInMbps?: number | Computed<number>;
  createdAt?: string | Computed<string>;
  id?: string | Computed<string>;
  naasProvider?: string | Computed<string>;
  name?: string | Computed<string>;
  parentUuid?: string | Computed<string>;
  region?: string | Computed<string>;
  state?: string | Computed<string>;
  vpcIds?: string[] | Computed<string[]>;
}

export interface AttachmentConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface AttachmentAttrs {
  links: Attachment_Links;
  meta: Attachment_Meta;
  page: number;
  partnerAttachments: Attachment_PartnerAttachments[];
  perPage: number;
}

export const Attachment: DataSourceBinding<AttachmentConfig, AttachmentAttrs> = {
  wireType: "digitalocean_attachment",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
