# Code generated by `ubx sdk gen` from digitalocean_attachment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Attachment_Bgp:
    # BGP Auth Key
    auth_key: Any = None
    # IP of the DO router
    local_router_ip: Any = None
    # ASN of the peer router
    peer_router_asn: Any = None
    # IP of the Naas Provider router
    peer_router_ip: Any = None

_Attachment_BgpFields = {
    "auth_key": ubx.FieldSpec(wire_name="auth_key"),
    "local_router_ip": ubx.FieldSpec(wire_name="local_router_ip"),
    "peer_router_asn": ubx.FieldSpec(wire_name="peer_router_asn"),
    "peer_router_ip": ubx.FieldSpec(wire_name="peer_router_ip"),
}

@dataclasses.dataclass
class AttachmentConfig:
    # Optional BGP configurations
    bgp: Any = None
    # Bandwidth (in Mbps) of the connection.
    connection_bandwidth_in_mbps: Any = None
    naas_provider: Any = None
    # The name of the partner attachment. Must be unique and may only contain alphanumeric characters, dashes, and periods.
    name: Any = None
    # Optional associated partner attachment UUID
    parent_uuid: Any = None
    # Optional redundancy zone for the partner attachment.
    redundancy_zone: Any = None
    # The region to create the partner attachment.
    region: Any = None
    # An array of VPCs IDs.
    vpc_ids: Any = None
    # path parameter, not part of the API's own resource representation
    pa_id: Any = None

@dataclasses.dataclass
class AttachmentAttrs:
    # Optional BGP configurations
    bgp: Any = None
    # Bandwidth (in Mbps) of the connection.
    connection_bandwidth_in_mbps: Any = None
    naas_provider: Any = None
    # The name of the partner attachment. Must be unique and may only contain alphanumeric characters, dashes, and periods.
    name: Any = None
    # Optional associated partner attachment UUID
    parent_uuid: Any = None
    # Optional redundancy zone for the partner attachment.
    redundancy_zone: Any = None
    # The region to create the partner attachment.
    region: Any = None
    # An array of VPCs IDs.
    vpc_ids: Any = None
    # path parameter, not part of the API's own resource representation
    pa_id: Any = None

Attachment = ubx.ResourceBinding(
    wire_type="digitalocean_attachment",
    fields={
        "bgp": ubx.FieldSpec(
            wire_name="bgp",
            kind="object",
            fields=_Attachment_BgpFields,
        ),
        "connection_bandwidth_in_mbps": ubx.FieldSpec(wire_name="connection_bandwidth_in_mbps"),
        "naas_provider": ubx.FieldSpec(wire_name="naas_provider"),
        "name": ubx.FieldSpec(wire_name="name"),
        "parent_uuid": ubx.FieldSpec(wire_name="parent_uuid"),
        "redundancy_zone": ubx.FieldSpec(wire_name="redundancy_zone"),
        "region": ubx.FieldSpec(wire_name="region"),
        "vpc_ids": ubx.FieldSpec(wire_name="vpc_ids"),
        "pa_id": ubx.FieldSpec(wire_name="pa_id"),
    },
)
