// Code generated by `ubx sdk gen` from digitalocean_vectordb_get_vector_dbadmin_credentials_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface GetVectorDbadminCredentialsResponseConfig {
  id: string | Computed<string>;
}

export interface GetVectorDbadminCredentialsResponseAttrs {
  /** API token for that user. */
  apiToken: string;
  id: string;
  /** Database user id from the cluster secret (opaque; matches what was provisioned). */
  userId: string;
}

export const GetVectorDbadminCredentialsResponse: DataSourceBinding<GetVectorDbadminCredentialsResponseConfig, GetVectorDbadminCredentialsResponseAttrs> = {
  wireType: "digitalocean_vectordb_get_vector_dbadmin_credentials_response",
  fields: {
    id: "id",
  },
};
