// Code generated by `ubx sdk gen` from digitalocean_byoip_prefix. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ByoipPrefix_ByoipPrefixes_Validations {
  name?: string | Computed<string>;
  note?: string | Computed<string>;
  status?: string | Computed<string>;
}

export interface ByoipPrefix_ByoipPrefixes {
  advertised?: boolean | Computed<boolean>;
  failureReason?: string | Computed<string>;
  locked?: boolean | Computed<boolean>;
  name?: string | Computed<string>;
  prefix?: string | Computed<string>;
  projectId?: string | Computed<string>;
  region?: string | Computed<string>;
  status?: string | Computed<string>;
  uuid?: string | Computed<string>;
  validations?: ByoipPrefix_ByoipPrefixes_Validations[] | Computed<ByoipPrefix_ByoipPrefixes_Validations[]>;
}

export interface ByoipPrefix_Links {
  pages?: unknown | Computed<unknown>;
}

export interface ByoipPrefix_Meta {
  total?: number | Computed<number>;
}

export interface ByoipPrefixConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface ByoipPrefixAttrs {
  byoipPrefixes: ByoipPrefix_ByoipPrefixes[];
  links: ByoipPrefix_Links;
  meta: ByoipPrefix_Meta;
  page: number;
  perPage: number;
}

export const ByoipPrefix: DataSourceBinding<ByoipPrefixConfig, ByoipPrefixAttrs> = {
  wireType: "digitalocean_byoip_prefix",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
