// Code generated by `ubx sdk gen` from digitalocean_ip. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Ip_Ips {
  assignedAt?: string | Computed<string>;
  byoip?: string | Computed<string>;
  id?: number | Computed<number>;
  region?: string | Computed<string>;
  resource?: string | Computed<string>;
}

export interface Ip_Links {
  pages?: unknown | Computed<unknown>;
}

export interface Ip_Meta {
  total?: number | Computed<number>;
}

export interface IpConfig {
  byoipPrefixUuid: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface IpAttrs {
  byoipPrefixUuid: string;
  ips: Ip_Ips[];
  links: Ip_Links;
  meta: Ip_Meta;
  page: number;
  perPage: number;
}

export const Ip: DataSourceBinding<IpConfig, IpAttrs> = {
  wireType: "digitalocean_ip",
  fields: {
    byoipPrefixUuid: "byoip_prefix_uuid",
    page: "page",
    perPage: "per_page",
  },
};
