# Code generated by `ubx sdk gen` from digitalocean_volume. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Volume_Links:
    pages: Any = None

@dataclasses.dataclass
class Volume_Meta:
    total: Any = None

@dataclasses.dataclass
class Volume_Volumes_Region:
    available: Any = None
    features: Any = None
    name: Any = None
    sizes: Any = None
    slug: Any = None

@dataclasses.dataclass
class Volume_Volumes:
    created_at: Any = None
    description: Any = None
    droplet_ids: Any = None
    filesystem_label: Any = None
    filesystem_type: Any = None
    id: Any = None
    name: Any = None
    region: Any = None
    size_gigabytes: Any = None
    tags: Any = None

@dataclasses.dataclass
class VolumeConfig:
    name: Any = None
    page: Any = None
    per_page: Any = None
    # The slug identifier for the region where the resource will initially be available.
    region: Any = None

@dataclasses.dataclass
class VolumeAttrs:
    links: Any = None
    meta: Any = None
    name: Any = None
    page: Any = None
    per_page: Any = None
    # The slug identifier for the region where the resource will initially be available.
    region: Any = None
    # Array of volumes.
    volumes: Any = None

Volume = ubx.DataSourceBinding(
    wire_type="digitalocean_volume",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "region": ubx.FieldSpec(wire_name="region"),
    },
)
