// Code generated by `ubx sdk gen` from digitalocean_accelerator. DO NOT EDIT.
package dedicatedinference

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Accelerator_Accelerators struct {
	CreatedAt any
	Id        any
	Name      any
	Role      any
	Slug      any
	Status    any
}

type Accelerator_Links struct {
	Pages any
}

type Accelerator_Meta struct {
	Total any
}

type AcceleratorConfig struct {
	DedicatedInferenceId any
	Page                 any
	PerPage              any
	Slug                 any
}

type AcceleratorAttrs struct {
	Accelerators         any
	DedicatedInferenceId any
	Links                any
	Meta                 any
	Page                 any
	PerPage              any
	Slug                 any
}

var Accelerator = ubx.DataSourceBinding{
	WireType: "digitalocean_accelerator",
	Fields: ubx.FieldMap{
		"DedicatedInferenceId": ubx.FieldSpec{WireName: "dedicated_inference_id"},
		"Page":                 ubx.FieldSpec{WireName: "page"},
		"PerPage":              ubx.FieldSpec{WireName: "per_page"},
		"Slug":                 ubx.FieldSpec{WireName: "slug"},
	},
}
