// Code generated by `ubx sdk gen` from digitalocean_dedicated_inference_size. DO NOT EDIT.
package dedicatedinference

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Size_Sizes struct {
	Currency     any
	GpuSlug      any
	PricePerHour any
	Region       any
}

type SizeConfig struct {
}

type SizeAttrs struct {
	// Regions where Dedicated Inference is available.
	EnabledRegions any
	Sizes          any
}

var Size = ubx.DataSourceBinding{
	WireType: "digitalocean_dedicated_inference_size",
	Fields:   ubx.FieldMap{},
}
