# Code generated by `ubx sdk gen` from digitalocean_organization_team. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class OrganizationTeam_Teams:
    company: Any = None
    email: Any = None
    id: Any = None
    joined_organization_at: Any = None
    member_count: Any = None
    name: Any = None
    status: Any = None
    uuid: Any = None

@dataclasses.dataclass
class OrganizationTeamConfig:
    pass

@dataclasses.dataclass
class OrganizationTeamAttrs:
    teams: Any = None

OrganizationTeam = ubx.DataSourceBinding(
    wire_type="digitalocean_organization_team",
    fields={
    },
)
