// Code generated by `ubx sdk gen` from digitalocean_options. DO NOT EDIT.
package options

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Options_Options_AdvancedMysql_Layouts struct {
	NumNodes any
	Sizes any
}

type Options_Options_AdvancedMysql struct {
	Layouts any
	Regions any
	Versions any
}

type Options_Options struct {
	AdvancedMysql any
	AdvancedPg any
	Kafka any
	Mongodb any
	Mysql any
	Opensearch any
	Pg any
	Redis any
	Valkey any
}

type Options_VersionAvailability_AdvancedMysql struct {
	EndOfAvailability any
	EndOfLife any
	Version any
}

type Options_VersionAvailability struct {
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	AdvancedMysql any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	AdvancedPg any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Kafka any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Mongodb any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Mysql any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Opensearch any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Pg any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Redis any
	// An array of objects, each indicating the version end-of-life, end-of-availability for various database engines
	Valkey any
}

type OptionsConfig struct {
}

type OptionsAttrs struct {
	Options any
	VersionAvailability any
}

var Options = ubx.DataSourceBinding{
	WireType: "digitalocean_options",
	Fields: ubx.FieldMap{
	},
}
