// Code generated by `ubx sdk gen` from digitalocean_nfs_response. DO NOT EDIT.
package nfs

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Response_Shares_AccessPoints_AccessPolicy struct {
	Anongid any
	Anonuid any
	IdentityEnforcementEnabled any
	Protocols any
	SquashConfig any
}

type Response_Shares_AccessPoints struct {
	AccessPolicy any
	CreatedAt any
	Id any
	IsDefault any
	Name any
	Path any
	ShareId any
	Status any
	UpdatedAt any
	VpcId any
}

type Response_Shares struct {
	AccessPoints any
	CreatedAt any
	Host any
	Id any
	MountPath any
	Name any
	PerformanceTier any
	Region any
	SizeGib any
	Status any
	VpcIds any
}

type ResponseConfig struct {
	Region any
}

type ResponseAttrs struct {
	Region any
	Shares any
}

var Response = ubx.DataSourceBinding{
	WireType: "digitalocean_nfs_response",
	Fields: ubx.FieldMap{
		"Region": ubx.FieldSpec{WireName: "region"},
	},
}
