// Code generated by `ubx sdk gen` from digitalocean_vectordb_backup. DO NOT EDIT.
package vectordb

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Backup_Backups struct {
	BackupId any
	CompletedAt any
	StartedAt any
	Status any
}

type BackupConfig struct {
	Id any
}

type BackupAttrs struct {
	// List of available backups.
	Backups any
	Id any
}

var Backup = ubx.DataSourceBinding{
	WireType: "digitalocean_vectordb_backup",
	Fields: ubx.FieldMap{
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
