// Code generated by `ubx sdk gen` from digitalocean_vectordb_get_restore_status_response. DO NOT EDIT.
package vectordb

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type GetRestoreStatusResponseConfig struct {
	BackupId any
	Id any
}

type GetRestoreStatusResponseAttrs struct {
	BackupId any
	// Error message if the restore failed.
	Error any
	Id any
	// Current status: STARTED, TRANSFERRING, TRANSFERRED, FINALIZING, SUCCESS, FAILED, CANCELLING, CANCELED.
	Status any
}

var GetRestoreStatusResponse = ubx.DataSourceBinding{
	WireType: "digitalocean_vectordb_get_restore_status_response",
	Fields: ubx.FieldMap{
		"BackupId": ubx.FieldSpec{WireName: "backup_id"},
		"Id": ubx.FieldSpec{WireName: "id"},
	},
}
