// Code generated by `ubx sdk gen` from digitalocean_vectordb_vector_db. DO NOT EDIT.
package vectordb

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type VectorDb_VectorDbs_Config struct {
	DefaultQuantization any
	EnableAutoSchema any
	WeaviateVersion any
}

type VectorDb_VectorDbs_Endpoints struct {
	Grpc any
	Http any
}

type VectorDb_VectorDbs struct {
	Config any
	CreatedAt any
	Endpoints any
	ForkedFromId any
	Id any
	LastRestoreId any
	Name any
	OwnerUuid any
	ProjectId any
	Region any
	Size any
	Status any
	Tags any
	UpdatedAt any
}

type VectorDbConfig struct {
	Page any
	PerPage any
}

type VectorDbAttrs struct {
	Page any
	PerPage any
	Total any
	VectorDbs any
}

var VectorDb = ubx.DataSourceBinding{
	WireType: "digitalocean_vectordb_vector_db",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
