// Code generated by `ubx sdk gen` from digitalocean_reserved_ipv6. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Reservedipv6_ReservedIpv6_Droplet_DiskInfo_Size {
  amount?: number | Computed<number>;
  unit?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_DiskInfo {
  size?: Reservedipv6_ReservedIpv6_Droplet_DiskInfo_Size | Computed<Reservedipv6_ReservedIpv6_Droplet_DiskInfo_Size>;
  type?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_GpuInfo {
  count?: number | Computed<number>;
  model?: string | Computed<string>;
  vram?: Reservedipv6_ReservedIpv6_Droplet_DiskInfo_Size | Computed<Reservedipv6_ReservedIpv6_Droplet_DiskInfo_Size>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Image {
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  distribution?: string | Computed<string>;
  errorMessage?: string | Computed<string>;
  id?: number | Computed<number>;
  minDiskSize?: number | Computed<number>;
  name?: string | Computed<string>;
  public?: boolean | Computed<boolean>;
  regions?: string[] | Computed<string[]>;
  sizeGigabytes?: number | Computed<number>;
  slug?: string | Computed<string>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  type?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Kernel {
  id?: number | Computed<number>;
  name?: string | Computed<string>;
  version?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Networks_V4 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Networks_V6 {
  gateway?: string | Computed<string>;
  ipAddress?: string | Computed<string>;
  netmask?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Networks {
  v4?: Reservedipv6_ReservedIpv6_Droplet_Networks_V4[] | Computed<Reservedipv6_ReservedIpv6_Droplet_Networks_V4[]>;
  v6?: Reservedipv6_ReservedIpv6_Droplet_Networks_V6[] | Computed<Reservedipv6_ReservedIpv6_Droplet_Networks_V6[]>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_NextBackupWindow {
  end?: string | Computed<string>;
  start?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Region {
  available?: boolean | Computed<boolean>;
  features?: string[] | Computed<string[]>;
  name?: string | Computed<string>;
  sizes?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6_Droplet_Size {
  available?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: Reservedipv6_ReservedIpv6_Droplet_DiskInfo[] | Computed<Reservedipv6_ReservedIpv6_Droplet_DiskInfo[]>;
  gpuInfo?: Reservedipv6_ReservedIpv6_Droplet_GpuInfo | Computed<Reservedipv6_ReservedIpv6_Droplet_GpuInfo>;
  memory?: number | Computed<number>;
  priceHourly?: number | Computed<number>;
  priceMonthly?: number | Computed<number>;
  regions?: string[] | Computed<string[]>;
  slug?: string | Computed<string>;
  transfer?: number | Computed<number>;
  vcpus?: number | Computed<number>;
}

export interface Reservedipv6_ReservedIpv6_Droplet {
  backupIds?: number[] | Computed<number[]>;
  createdAt?: string | Computed<string>;
  disk?: number | Computed<number>;
  diskInfo?: Reservedipv6_ReservedIpv6_Droplet_DiskInfo[] | Computed<Reservedipv6_ReservedIpv6_Droplet_DiskInfo[]>;
  features?: string[] | Computed<string[]>;
  gpuInfo?: Reservedipv6_ReservedIpv6_Droplet_GpuInfo | Computed<Reservedipv6_ReservedIpv6_Droplet_GpuInfo>;
  id?: number | Computed<number>;
  image?: Reservedipv6_ReservedIpv6_Droplet_Image | Computed<Reservedipv6_ReservedIpv6_Droplet_Image>;
  kernel?: Reservedipv6_ReservedIpv6_Droplet_Kernel | Computed<Reservedipv6_ReservedIpv6_Droplet_Kernel>;
  locked?: boolean | Computed<boolean>;
  memory?: number | Computed<number>;
  name?: string | Computed<string>;
  networks?: Reservedipv6_ReservedIpv6_Droplet_Networks | Computed<Reservedipv6_ReservedIpv6_Droplet_Networks>;
  nextBackupWindow?: Reservedipv6_ReservedIpv6_Droplet_NextBackupWindow | Computed<Reservedipv6_ReservedIpv6_Droplet_NextBackupWindow>;
  region?: Reservedipv6_ReservedIpv6_Droplet_Region | Computed<Reservedipv6_ReservedIpv6_Droplet_Region>;
  size?: Reservedipv6_ReservedIpv6_Droplet_Size | Computed<Reservedipv6_ReservedIpv6_Droplet_Size>;
  sizeSlug?: string | Computed<string>;
  snapshotIds?: number[] | Computed<number[]>;
  status?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  vcpus?: number | Computed<number>;
  volumeIds?: string[] | Computed<string[]>;
  vpcUuid?: string | Computed<string>;
}

export interface Reservedipv6_ReservedIpv6 {
  droplet?: Reservedipv6_ReservedIpv6_Droplet | Computed<Reservedipv6_ReservedIpv6_Droplet>;
  /** The public IP address of the reserved IPv6. It also serves as its identifier. */
  ip?: string | Computed<string>;
  /** The region that the reserved IPv6 is reserved to. When you query a reserved IPv6,the region_slug will be returned. */
  regionSlug?: string | Computed<string>;
  /** The date and time when the reserved IPv6 was reserved. */
  reservedAt?: string | Computed<string>;
}

export interface Reservedipv6Config {
  /** The slug identifier for the region the reserved IPv6 will be reserved to. */
  regionSlug: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation (renamed from "reserved_ipv6": that name is already used by a differently-typed, real response attribute) */
  reservedIpv6Path: string | Computed<string>;
}

export interface Reservedipv6Attrs {
  /** The slug identifier for the region the reserved IPv6 will be reserved to. */
  regionSlug: string;
  reservedIpv6: Reservedipv6_ReservedIpv6;
  /** path parameter, not part of the API's own resource representation (renamed from "reserved_ipv6": that name is already used by a differently-typed, real response attribute) */
  reservedIpv6Path: string;
}

export const Reservedipv6: ResourceBinding<Reservedipv6Config, Reservedipv6Attrs> = {
  wireType: "digitalocean_reserved_ipv6",
  fields: {
    regionSlug: "region_slug",
    reservedIpv6Path: "reserved_ipv6_path",
  },
};
